### ISSUE TITLE
提交提交订票的时候checkUser的messages是空,返回false，需不需要立刻重新登录？

### ISSUE THREAD

**Issue by Flyingon** [testerSunshine/12306#10]
接口返回：{'validateMessagesShowId': '_validatorMessage', 'status': True, 'httpstatus': 200, 'data': {'flag': False}, 'messages': [], 'validateMessages': {}}， 请大神用空指点下，急着抢票回家呐！

**Comment by Flyingon** [comment]
看到python2版本了，是需要重新登录的啊，已经按这个修改了...好像python3有些地方没有更新呐～

**Comment by testerSunshine** [comment]
建议使用2版本，3的暂时没更新，这几天比较忙，稍后会更新的

**Comment by Flyingon** [comment]
嗯，好的，不过最近几天登录不上了，一直返回 登录失败: 系统忙，请稍后重试，但我12306网站可以登录，是不是接口变了呀？

**Comment by testerSunshine** [comment]
下载最新dev分支，已修改好
