### ISSUE TITLE
发生下列错误: 拒绝访问。 (0x80070005) 发生下列错误: 服务尚未启动。 (0x80070426) 发生下列错误: 拒绝访问。 (0x80070005) 发生系统错误 5。

### ISSUE THREAD

**Issue by LoyaltyLu** [testerSunshine/12306#102]
![image](https://user-images.githubusercontent.com/19270075/50763817-dc863000-12ab-11e9-8906-84ccfaf4e5ef.png)

**Comment by qinya0** [comment]
过一会就好了，windows 2.7.15 可以跑
