### ISSUE TITLE
有偿求大神给个在服务器端运行的详细教程

### ISSUE THREAD

**Issue by haha50** [testerSunshine/12306#106]

**Comment by qinya0** [comment]
windows 7 专业版
1. 安装python 2.7.15 https://www.python.org/downloads/release/python-2715/
2. 配置环境变量（如果没有）
3. 安装依赖包：请看readme.md
4. 注册若快，充1块钱
5. 修改配置文件config/ticket_config.yaml（注意格式）
6. 我用的PyCharm社区版，https://www.jetbrains.com/pycharm/download/download-thanks.html?platform=windows&code=PCC
7. 运行run.py（作者大佬已经把.idea都放在库上了）
7. 祝你好运

坑1：
电脑上原来安装时python3.4 安装插件老是报错，卸载重装的python
坑2：
开始时会有报错：https://github.com/testerSunshine/12306/issues/102
ntp同步时间？没看代码是在干嘛，等一会就行了

**Comment by haha50** [comment]
这种方法我会啊，我想知道的是怎么在租赁的虚拟服务器上用docker运行，难道你们一直挂电脑吗

**Comment by jingzhao-falcon** [comment]
可以用树莓派一直挂着

**Comment by Cyrus-Jiang** [comment]
> 这种方法我会啊，我想知道的是怎么在租赁的虚拟服务器上用docker运行，难道你们一直挂电脑吗

步骤差不多，只不过在linux上安装环境而已

**Comment by Haoshenqi0123** [comment]
> 这种方法我会啊，我想知道的是怎么在租赁的虚拟服务器上用docker运行，难道你们一直挂电脑吗

升级python 到2.7（服务器好多2.6的）
git clone 
安装依赖
python run.py
