### ISSUE TITLE
限制运行时间的建议

### ISSUE THREAD

**Issue by JiangXL** [testerSunshine/12306#109]
你好，我发现 run.py 在非售票时间也在运行，导致若快帐号很快就空了。请问能限制以下程序进行刷票的时间区间吗？

![image](https://user-images.githubusercontent.com/5670700/50803857-738fce00-1326-11e9-8459-8974865b35c3.png)

**Comment by haha50** [comment]
这个必须有，我的快豆也很快被用完了

**Comment by testerSunshine** [comment]
@JiangXL 你这个是潜艇的代码吗？昨天的打码已经修复这个问题啦

**Comment by JiangXL** [comment]
谢谢，有劳了。我更新试试。
