### ISSUE TITLE
一直登陆失败，不知道啥原因

### ISSUE THREAD

**Issue by junySong** [testerSunshine/12306#11]
候选购买车次：K751,K282
未开始刷票间隔时间：0.3
僵尸票关小黑屋时长：3

********************
[*] 获取Cookie 
[*] 下载验证码... 
[*] 验证码通过,开始登录.. 
[!] 登录失败: 系统忙，请稍后重试 
[*] 获取Cookie 
[*] 下载验证码... 
[*] 验证码通过,开始登录.. 
[!] 登录失败: 系统忙，请稍后重试 
[*] 获取Cookie 
[*] 下载验证码... 
[*] 验证码通过,开始登录.. 
[!] 登录失败: 系统忙，请稍后重试 
[*] 获取Cookie 
[*] 下载验证码... 
[*] 验证码通过,开始登录.. 
[!] 登录失败: 系统忙，请稍后重试 
[*] 获取Cookie 
[*] 下载验证码... 
[*] 验证码通过,开始登录.. 
[!] 登录失败: 系统忙，请稍后重试 
[*] 获取Cookie 
[*] 下载验证码...

**Comment by legend404** [comment]
我也登陆失败 。。。   打码兔还是扣分了

**Comment by jhbpxx** [comment]
接口有变化在，修改 ing

**Comment by testerSunshine** [comment]
下载最新dev分支，已修改好
