### ISSUE TITLE
验证通过但一直登录失败

### ISSUE THREAD

**Issue by duncanx0816** [testerSunshine/12306#113]
init/login.py 
    line73 -> 登录失败：登录失败
    line60 -> tresult对应值：{'result_message': '登录失败', 'result_code': 1}

验证码验证通过，就是一直无法登录，不明白是什么原因？

**Comment by testerSunshine** [comment]
ip有问题

**Comment by duncanx0816** [comment]
> ip有问题

关闭了cdn，还是无法登录；请问有什么解决的思路呢？
