### ISSUE TITLE
pip install 安装依赖

### ISSUE THREAD

**Issue by zcp6835** [testerSunshine/12306#116]
Cleaning up...
Command /bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-SIh0JQ-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/Pillow
Storing debug log for failure in /root/.pip/pip.log

**Comment by cy920820** [comment]
进入requirements.txt所在根目录，然后运行(必要时加sudo)
```shell
pip install -r requirements.txt
```
