### ISSUE TITLE
尝试提交订单，显示未找到常用联系人

### ISSUE THREAD

**Issue by cy920820** [testerSunshine/12306#118]
![image](https://user-images.githubusercontent.com/21211512/50811850-3a1d8980-134b-11e9-8ec8-c018becba252.png)

**Comment by cy920820** [comment]
ticke_peoples字段所填写的姓名 确定在 常用联系人列表中

**Comment by SishangLi** [comment]
同上，换了好几个联系人也是这样子

**Comment by caoyi0905** [comment]
请在网页端12306查看联系人是否存在

**Comment by SishangLi** [comment]
> 请在网页端12306查看联系人是否存在

有的啊，肯定要先确认联系人中有的

**Comment by cy920820** [comment]
@testerSunshine

**Comment by testerSunshine** [comment]
这个是登录状态掉线了，你要测试一下你的ip登录会不会掉线，在买票，如果一直登录掉线，要换ip才行

**Comment by messi612** [comment]
怎么测试登录会不会掉线啊 就只会提示“重试次数达到上限“，然后就提示“查找到常用联系人, 请查证后添加!“
