### ISSUE TITLE
登录时验证码数不出来,显示的图片是你刷新的图片显示过快,请稍后重试

### ISSUE THREAD

**Issue by GuiyangZhao** [testerSunshine/12306#12]
使用:`codeimg = 'https://kyfw.12306.cn/otn/passcodeNew/getPassCodeNew?module=login&rand=sjrand&%s' % random.random()`得到的图片时**刷新的图片显示过快,请稍后重试**

当使用URL:`codeiamge = https://kyfw.12306.cn/passport/captcha/captcha-image?login_site=E&module=login&rand=sjrand&% random.random()`获取验证图片时,能获取到,但是登录时**显示系统繁忙**

**Comment by testerSunshine** [comment]
下载最新dev分支，已修改好
