### ISSUE TITLE
有没有用python3的?

### ISSUE THREAD

**Issue by lolkt** [testerSunshine/12306#121]
新手不太懂怎么python2-->python3修改

**Comment by WeMadeCode** [comment]
朋友 python3啊

**Comment by wickywe** [comment]
请问python3 怎么支持？

**Comment by lolkt** [comment]
> 请问python3 怎么支持？

我也是新手，没运行起来

**Comment by sherlockwhite** [comment]
支持python3要作者写一个新的版本，下个python2吧

**Comment by lolkt** [comment]
> 支持python3要作者写一个新的版本，下个python2吧

好的  谢谢

**Comment by testerSunshine** [comment]
已经支持

**Comment by wickywe** [comment]
> 已经支持

是源代码里面就支持了，还是新项目里？  求链接
