### ISSUE TITLE
请问捡漏模式的刷新时间间隔在哪里改？

### ISSUE THREAD

**Issue by QuenceyTang** [testerSunshine/12306#122]
0.5~3秒有点慢。 市面上免费的低速抢票大概是一秒30多次。
另外，请问0.5~3这个间隔是测试得出的吗？

**Comment by testerSunshine** [comment]
init/select_ticket_info.py

**Comment by QuenceyTang** [comment]
谢谢。昨天找到了。  改成了0.5~1.5  整体速度提升也不大。
