### ISSUE TITLE
明明12306上有票，但是查询无票？

### ISSUE THREAD

**Issue by wild-jie** [testerSunshine/12306#124]

**Comment by wild-jie** [comment]
正在第99次查询 随机停留时长：1.87 乘车日期: 2019-02-06 车次：G57 查询无票 cdn轮询IP：None当前cdn总数：88 总耗时：270.434ms
当前请求cdn为111.161.22.16

**Comment by testerSunshine** [comment]
你看看是不是车次设置或者日期设置写错了

**Comment by wild-jie** [comment]
> 你看看是不是车次设置或者日期设置写错了

车次/日期 贴出来了，没有错误啊，单日、单车次

**Comment by juzhiyuan** [comment]
有可能你看到的是CDN缓存

**Comment by animebing** [comment]
@juzhiyuan 这个是什么意思呢？我自己查都有票，但是这里提示没票。

**Comment by juzhiyuan** [comment]
@animebing 12306 查票页面的数据，是从 CDN 上过来的，这个数据不是实时的。

**Comment by animebing** [comment]
@juzhiyuan 我们可以清除缓存吗？谢谢啦

**Comment by wild-jie** [comment]
> 有可能你看到的是CDN缓存

找到原因了，我用的python3，部分条件判断出问题了，显示无票

**Comment by animebing** [comment]
@wild-jie 像问下是哪些条件判断出问题了呢？

**Comment by wild-jie** [comment]
> @wild-jie 想问下是哪些条件判断出问题了呢？

用的python3，我修改的部分大都是encode()之类的问题

**Comment by animebing** [comment]
@wild-jie  谢谢了

**Comment by leeyoshinari** [comment]
我用的也是python3，和你情况一样，有票却查询无票，请问哪个地方判断出问题了？谢谢~
