### ISSUE TITLE
怎么1月9日还没到就更新了

### ISSUE THREAD

**Issue by soap-man** [testerSunshine/12306#127]
你好，我看Update.md，2019.1.9更新了，可是今天才8号，我有强迫症

**Comment by lb0629** [comment]
hahahah，我也发现了。

**Comment by soap-man** [comment]
@lb0629  是吧，哈哈哈


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by pleuvoir** [comment]
> 你好，我看Update.md，2019.1.9更新了，可是今天才8号，我有强迫症

可以修改本地时间吧
