### ISSUE TITLE
查到票时一直提交不成功

### ISSUE THREAD

**Issue by kuanghy** [testerSunshine/12306#13]
一直提交不成功：

车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有
正在尝试提交订票...
12306接口无响应，正在重试
车次: D2001 始发车站: 北京 终点站: 运城 二等座:有

**Comment by testerSunshine** [comment]
这个可能是用户登录失败了，用新版的dev分支试下
