### ISSUE TITLE
windows 读取文件格式错误

### ISSUE THREAD

**Issue by xiaohe920** [testerSunshine/12306#132]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 40: illegal multibyte sequence

好多读取文件的地方都会出现编码问题

windows系统

**Comment by wosenbo** [comment]
命令CHCP：显示或设置活动代码页编号

　　CHCP [code]

　　code指定代码页编号。不加参数键入 CHCP 显示活动代码页编号。加参数会更改当前编码。

 

MS-DOS为以下国家和语言提供字符集：


编号 | 语言 | 编号 | 语言
-- | -- | -- | --
1258 | 越南语 | 1257 | 波罗的语
1256 | 阿拉伯语 | 1255 | 希伯来语
1254 | 土耳其语 | 1253 | 希腊语
1252 | 拉丁字符 (ANSI) | 1251 | 西里尔语
1250 | 中欧语言 | 950 | 繁体中文
949 | 朝鲜语 | 936 | 简体中文（默认）
932 | 日语 | 874 | 泰国语
850 | 多语种 (Latin1) | 437 | 美国英语
65001 | UTF-8 |   |  

如果想正确显示UTF-8字符，可以按照以下步骤操作：

1、打开CMD.exe命令行窗口

2、通过 chcp命令改变代码页，UTF-8的代码页为65001：chcp 65001

执行该操作后，代码页就被变成UTF-8了。如果窗口中仍旧不能正确显示UTF-8字符，继续...下一步

3、修改窗口属性，改变字体

在命令行标题栏上点击右键，选择"属性"->"字体"，将字体修改为True Type字体"Lucida Console"，然后点击确定将属性应用到当前窗口。这时使用type命令就可以显示UTF-8文本文件的内容了：

type filename.txt

4、若内容显示不完全。可以先最小化，然后最大化命令行窗口。
