### ISSUE TITLE
请问mac下能用吗？

### ISSUE THREAD

**Issue by miles-wang** [testerSunshine/12306#133]

**Comment by wosenbo** [comment]
Mac 下可以用的，先检查一下 Python 版本：python --version。如果版本不在 2.7.10 - 2.7.15 内，需要安装对应版本的 python 后再使用。

**Comment by miles-wang** [comment]
谢谢告知，已安装成功。

**Comment by miles-wang** [comment]
> Mac 下可以用的，先检查一下 Python 版本：python --version。如果版本不在 2.7.10 - 2.7.15 内，需要安装对应版本的 python 后再使用。

谢谢告知，已安装成功。

**Comment by henekod** [comment]
求教Mac下使用教程，小白一枚

**Comment by xrhou** [comment]
> 求教Mac下使用教程，小白一枚

mac 下安装 pycharm python IDE 直接 打开项目，修改yaml文件就可以了。
