### ISSUE TITLE
解决163邮箱给QQ邮箱发送失败，系统退信

### ISSUE THREAD

**Issue by kai2ou** [testerSunshine/12306#135]
抱歉，您的邮件被退回来了……
出错原因：该邮件内容涉嫌大量群发，并且被多数用户投诉为垃圾邮件。
解决办法：修改 config/emailConf.py里面subject = '恭喜，您已订票成功'，将subject改为任意主题，比如：subject = '12306订票成功，请及时付款'
自己修改个性主题即可。

**Comment by jianglangcaisheng** [comment]
确实存在这个问题，run里Email的测试也是失败的。

不改subject，只改内容也可以，例如只发一个“OK”即可。

**Comment by kai2ou** [comment]
> 确实存在这个问题，run里Email的测试也是失败的。
> 
> 不改subject，只改内容也可以，例如只发一个“OK”即可。

是的。
