### ISSUE TITLE
docker 启动后查询log 显示是报错的

### ISSUE THREAD

**Issue by fulln** [testerSunshine/12306#136]
[root@localhost 12306]# docker logs 12306-ticket
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found
sh: 1: ntpdate: not found

**Comment by fulln** [comment]
ntpdate显示不存在   把服务器时间同步到镜像中啊

**Comment by MonsterTan** [comment]
> ntpdate显示不存在 把服务器时间同步到镜像中啊

忽略即可，容器内的镜像会采用宿主机的镜像，若采用抢票模式确保你宿主机的时间是准确的。
