### ISSUE TITLE
安装项目依赖包 requirements.txt报错

### ISSUE THREAD

**Issue by lx775289883** [testerSunshine/12306#138]
Command "D:\Python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\77528\\appdata\\local\\temp\\pip-build-2bbxkc\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\77528\appdata\local\temp\pip-vrpe5g-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\77528\appdata\local\temp\pip-build-2bbxkc\Pillow

**Comment by Hibiki-Spring** [comment]
在项目目录内pip实施
