### ISSUE TITLE
提交订单成功！出票失败！

### ISSUE THREAD

**Issue by followmejoy** [testerSunshine/12306#139]
![image](https://user-images.githubusercontent.com/41257601/50899783-1abb5500-144e-11e9-8d07-ee6fdc853aec.png)

**Comment by armoour** [comment]
这个猜测就像是我们手动提交订单，然后进入排队，排了几分钟之后提示说售罄那种情况吧

**Comment by kai2ou** [comment]
我也是这种问题，将快速出票换成普通出票就可以，应该是快速出票的问题
