### ISSUE TITLE
ip网络异常，查询url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-02-07&leftTicketDTO.from_station=VUQ&leftTicketDTO.to_station=GZQ&purpose_codes=ADULT, 可以手动查询是否有票

### ISSUE THREAD

**Issue by linjohn527** [testerSunshine/12306#140]
ip网络异常，查询url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-02-08&leftTicketDTO.from_station=VUQ&leftTicketDTO.to_station=GZQ&purpose_codes=ADULT, 可以手动查询是否有票

**Comment by kun-guo** [comment]
成功没显示，失败会显示，这个地方输出下成功请求会好点

**Comment by yijigao** [comment]
最近ip网络异常频率好高啊

**Comment by chenglei12345** [comment]
我关掉了家里的无线网，用手机开热点，Mac连上热点，这个问题就不见了

**Comment by zhjwong** [comment]
> 问题+1...

公司网络出现上述问题， 回家偶尔遇到，概率接近8%   可以接受。

**Comment by wangcai-a** [comment]
我在阿里云上跑就是这个,在本地就不会
