### ISSUE TITLE
本地虚拟机ubuntu18很快，云上不行，求释疑

### ISSUE THREAD

**Issue by dreamsleet** [testerSunshine/12306#143]
本地虚拟机ubuntu18很快成功下单，放到腾讯云centos7 上运行开始报几十条  ip网络异常  ，过一会儿查到余票后  又报  未查找到常用联系人   未成功过；
求释疑

**Comment by testerSunshine** [comment]
ip被封了，限制你下单

**Comment by dreamsleet** [comment]
@testerSunshine   3q

**Comment by likohank** [comment]
IDC、云机房 基本不能用的。 所有刷票软件的通病。 用带拨号的vps试试。 最好还是在本地电脑。

**Comment by dreamsleet** [comment]
@likohank 谢谢，确实如此，我也估计12306对这些云机房的IP段做了限制

**Comment by Cyrus-Jiang** [comment]
> IDC、云机房 基本不能用的。 所有刷票软件的通病。 用带拨号的vps试试。 最好还是在本地电脑。

国外的vps影响吗

**Comment by likohank** [comment]
@

> > IDC、云机房 基本不能用的。 所有刷票软件的通病。 用带拨号的vps试试。 最好还是在本地电脑。
> 
> 国外的vps影响吗

更加不能用了。。。。。
