### ISSUE TITLE
有票都买不着不知道为什么

### ISSUE THREAD

**Issue by kbvstmd** [testerSunshine/12306#144]
车次坐席查询为空,ip网络异常，查询url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-02-01&leftTicketDTO.from_station=YNG&leftTicketDTO.to_station=HZH&purpose_codes=ADULT, 可以手动查询是否有票
{'message': u'\u91cd\u8bd5\u6b21\u6570\u8fbe\u5230\u4e0a\u9650', 'code': 99999}
未查找到常用联系人, 请查证后添加!!
提交订单成功
排队成功, 当前余票还剩余: 17 张
验证码提交安全期，等待3.97MS
出票失败！
(u'10:00', u'11:30', u'01:30')

**Comment by testerSunshine** [comment]
用普通下单
