### ISSUE TITLE
The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.

### ISSUE THREAD

**Issue by vanquisher1** [testerSunshine/12306#153]
Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: PyYAML, six, urllib3, idna, requests, Pillow, wrapcache, ntplib
  Found existing installation: PyYAML 3.13
Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by testerSunshine** [comment]
yum install zip -y
