### ISSUE TITLE
12306上有票，但是查询却没有票

### ISSUE THREAD

**Issue by animebing** [testerSunshine/12306#155]
我专门在12306上找了三趟有票的车次，但是软件查询时却总说没有票，怎么回事呢，求帮助

**Comment by ZhichangGao** [comment]
12306上显示有延迟，你买张看看

**Comment by ZhichangGao** [comment]
12306上有延迟

> 我专门在12306上找了三趟有票的车次，但是软件查询时却总说没有票，怎么回事呢，求帮助

**Comment by animebing** [comment]
@ZhichangGao 我刚买了，显示余票还有375张，2019-02-02 北京南到天津 G2551

**Comment by testerSunshine** [comment]
设置可能有问题，车次和时间
