### ISSUE TITLE
验证码通过,开始登录.. 登录成功, 用户检查失败，可能未登录，可能session已经失效

### ISSUE THREAD

**Issue by MorningStarJ** [testerSunshine/12306#156]
前两天用这都好好的，今天突然就一只这样。
![image](https://user-images.githubusercontent.com/15356218/51011296-fe750080-1592-11e9-88d2-717f7a657423.png)

**Comment by bennyfreecoding** [comment]
应该是操作太多 被封了

**Comment by UnaMattinaDev** [comment]
现在又可以了。。
