### ISSUE TITLE
ImportError: No module named yaml 

### ISSUE THREAD

**Issue by FFCZ** [testerSunshine/12306#160]
Python 2.7.15，clone了今天的git，运行时候一直出错。尝试了各种办法
-----------------------
 pip install PyYAML
 yum install python-yaml
-----------------------
但还是
`Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/data/software/12306/config/emailConf.py", line 5, in <module>
    from config.ticketConf import _get_yaml
  File "/data/software/12306/config/ticketConf.py", line 4, in <module>
    import yaml
ImportError: No module named yaml`
依赖库
`Looking in indexes: http://pypi.douban.com/simple
Requirement already satisfied: beautifulsoup4==4.5.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (4.5.3)
Requirement already satisfied: bs4==0.0.1 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: PyYAML==3.12 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 3)) (3.12)
Requirement already satisfied: six==1.10.0 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4)) (1.10.0)
Requirement already satisfied: requests==2.18.4 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5)) (2.18.4)
Requirement already satisfied: Pillow==5.0.0 in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 6)) (5.0.0)
Requirement already satisfied: wrapcache==1.0.8 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7)) (1.0.8)
Requirement already satisfied: ntplib==0.3.3 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8)) (0.3.3)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests==2.18.4->-r requirements.txt (line 5)) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests==2.18.4->-r requirements.txt (line 5)) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests==2.18.4->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests==2.18.4->-r requirements.txt (line 5)) (2018.11.29)`

**Comment by zhang-quan-yi** [comment]
我是maos，执行 `sudo python run.py` 也报同样的错误；但改成 `sudo python2 run.py` 就可以执行了；

**Comment by SmithLeroy** [comment]
可以执行sudo apt-get install python-yaml后，再试一下

**Comment by ColorfulGhost** [comment]
我也有这个问题
