### ISSUE TITLE
提交订单时，找不到联系人

### ISSUE THREAD

**Issue by o-water-o** [testerSunshine/12306#165]
{'message': u'\u91cd\u8bd5\u6b21\u6570\u8fbe\u5230\u4e0a\u9650', 'code': 99999}
未查找到常用联系人, 请查证后添加!!
使用自己的名字无法查找到联系人，使用常用联系人中的其他人可以，第一次使用的时候是可以的，但是现在用的时候，提交订单的时候找不到自己的联系人信息

**Comment by XingxingZhang** [comment]
看来是个bug了，我也遇到了。或者12306修改了后台的html代码?

**Comment by o-water-o** [comment]
> 看来是个bug了，我也遇到了。或者12306修改了后台的html代码?

很奇怪的，自己账号自己不行，用别人账号买自己也不行。这个报错，我看代码中，这个报错没有给详细注释。常用联系人列表获取到自己了，但是提交订单的时候就出错了

**Comment by XingxingZhang** [comment]
@o-water-o 我这次抢成功了。在一台新的机子上重新把所有东西都安装一个就可以了。

这次抢票我用了两台机器（A和B，并且在运行前都git pull origin master了一下），A是之前报错的机器，B是所有东西新安装的机器。B抢票成功了，A仍然报相同的错误。

我觉得你把A上的docker删了再装一遍应该也可以。不过我建议你在一个别的机器上再装一个这个软件。

祝好运！同时给这个工具的作者点赞！帮我抢到了票

**Comment by o-water-o** [comment]
> @o-water-o 我这次抢成功了。在一台新的机子上重新把所有东西都安装一个就可以了。
> 
> 这次抢票我用了两台机器（A和B，并且在运行前都git pull origin master了一下），A是之前报错的机器，B是所有东西新安装的机器。B抢票成功了，A仍然报相同的错误。
> 
> 我觉得你把A上的docker删了再装一遍应该也可以。不过我建议你在一个别的机器上再装一个这个软件。
> 
> 祝好运！同时给这个工具的作者点赞！帮我抢到了票

好的，我试试，感觉是缓存问题

**Comment by zjluoyue** [comment]
log：
设置乘车人数为: 1
查询到有余票，尝试提交订单
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
联系人不在列表中，请查证后添加!!
-------------------------------------------------------------------------
这是使用有屏蔽的网络，获取不到联系人，自己和其他人都获取不到，和你报的错好像一样

log：
登录成功
欢迎 XX 登录
正在第1次查询 随机停留时长：1.85 乘车日期:  车次： 查询无票 cdn轮询IP：183.47.216.87当前cdn总数：3 总耗时：994ms
---------------------------------------------------------------------------
换了网络就正常了，测试了几单，感觉还是很给力，还是抢不到票，哈哈

**Comment by daxwang** [comment]
我也遇到这个问题了，5555
