### ISSUE TITLE
打码平台错误: 用户绑定了指定的软件,无法使用其他软件

### ISSUE THREAD

**Issue by daibanshixianglan** [testerSunshine/12306#172]
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
下载验证码...
下载验证码成功
<Response [200]>
打码平台错误: 用户绑定了指定的软件,无法使用其他软件,当前使用的软件ID是:96061, 请登录打码平台查看-http://www.ruokuai.com/client/index?6726
验证码校验失败,信息为空
![image](https://user-images.githubusercontent.com/9823869/51071876-16cc4480-1693-11e9-9c18-d6136c30a96f.png)

若快的保护是关闭状态的。
![image](https://user-images.githubusercontent.com/9823869/51071862-f7cdb280-1692-11e9-9cb2-1c627d69f884.png)

**Comment by Mafoo99** [comment]
![image](https://user-images.githubusercontent.com/42490076/51096051-5cece980-17f4-11e9-8646-8556de37db96.png)
查看若快是否被盗，被别人绑定了其他软件使用

**Comment by testerSunshine** [comment]
打码平台已经取消使用了
