### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by qiuyajun** [testerSunshine/12306#173]
打印出来这个就程序就断掉了

**Comment by qiuyajun** [comment]
![screenshot from 2019-01-12 20-40-07](https://user-images.githubusercontent.com/43778144/51073345-55212e00-16aa-11e9-8d86-525600046492.png)
![screenshot from 2019-01-12 20-40-07](https://user-images.githubusercontent.com/43778144/51073357-a16c6e00-16aa-11e9-9d3a-081a264ebd14.png)

**Comment by qiuyajun** [comment]
这种情况是因为什么

**Comment by LuhangRui** [comment]
这个问题刚刚得到了结果，更新代码就行了。

**Comment by LuhangRui** [comment]
@qiuyajun

**Comment by qiuyajun** [comment]
好的 谢谢啦

**Comment by henekod** [comment]
pull 了新代码，这个“车次坐席查询为空，ip网络异常...”出现还是很频繁
