### ISSUE TITLE
无座的票买不到

### ISSUE THREAD

**Issue by soap-man** [testerSunshine/12306#174]
无座的票充足，程序也查询到了无座有票，但日志提示：您选择了1位乘车人，但本次列车硬座仅剩0张，下面是日志

车次: D9743 始发车站: 广州南 终点站: 新会 无座: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
缓存中找到联系人信息: [{u'code': u'5', u'passenger_type_name': u'\u6210\u4eba', u'passenger_id_type_code': u'1', u'passenger_id_no': u'421087199302203716', u'gat_born_date': u'', u'gat_valid_date_end': u'', u'passenger_flag': u'0', u'mobile_no': u'13094215172', u'country_code': u'CN', u'sex_name': u'\u7537', u'email': u'soap555@dingtalk.com', u'first_letter': u'', u'gat_valid_date_start': u'', u'passenger_type': u'1', u'address': u'', u'postalcode': u'', u'passenger_id_type_name': u'\u4e2d\u56fd\u5c45\u6c11\u8eab\u4efd\u8bc1', u'sex_code': u'M', u'total_times': u'99', u'gat_version': u'', u'recordCount': u'13', u'index_id': u'0', u'phone_no': u'', u'born_date': u'1993-02-20 00:00:00', u'passenger_name': u'\u4ed8\u5f3a'}]
您选择了1位乘车人，但本次列车硬座仅剩0张。
(u'14:00', u'14:32', u'00:32')

**Comment by testerSunshine** [comment]
没有票了，这个无座是缓存的票
