### ISSUE TITLE
系统运行登录成功后，不再运行

### ISSUE THREAD

**Issue by zhang-quan-yi** [testerSunshine/12306#175]
如图，显示登录成功了，但程序就停止了。
最后一行信息 `u'\u5e38\u5dde\u7ad9'` 为 `常州站`：

![image](https://user-images.githubusercontent.com/12481444/51074077-7b989680-16b5-11e9-8944-60c46e2b1eec.png)

**Comment by testerSunshine** [comment]
看看你的系统时间是不是北京时间？
是否开了预售
