### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by huangaoxin** [testerSunshine/12306#18]
提交订票的时候，接口无响应

> self.token = re.search(token_name, initdc_result).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

另外，我使用的时候登录不稳定，验证码通过之后就接口无响应，有时候要重复登录十几次才能成功一次，不知道什么原因

**Comment by testerSunshine** [comment]
已修正，用最新master分支
