### ISSUE TITLE
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！

### ISSUE THREAD

**Issue by waterasice** [testerSunshine/12306#186]
设置乘车人数为: 1
查询到有余票，尝试提交订单
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
警告：您的账号可能买票有问题，获取不到联系人，请测试是否能正常下单，在捡漏或者购票！！！
联系人不在列表中，请查证后添加!!

用 app 测试可以订票，请问为什么会报这个警告？

**Comment by 151438611** [comment]
我的也是出现这个提示，明明是帐号本人的名字，也是出现，不知道啥情况？

**Comment by sdhmdhr123** [comment]
好像是因为本身12306这个时间也是崩溃的状态。。。登进去都是超时。。手动也没法买

**Comment by sdhmdhr123** [comment]
同  而且我现在手动登入常用联系人会显示网络错误

**Comment by 96506926** [comment]
可能是你的IP给封了,导致获取失败哦

**Comment by wubingyang** [comment]
同遇到这个问

**Comment by mutable-Linus** [comment]
> 你的已登录就出现这个问题的话应该是ip有问题了

您好！ 请问什么能登录就是不能获取 乘车联系人呢？再说如果获取不到联系人是不是应该直接退出呢？
