### ISSUE TITLE
能做一个邮箱测试的功能吗 不知道邮箱配置是否正确

### ISSUE THREAD

**Issue by lakakala** [testerSunshine/12306#188]

**Comment by Mafoo99** [comment]
你随便找一天买一张高铁票就可以测试出来了

**Comment by henekod** [comment]
run.py 里面有测试邮箱的方法

**Comment by wosenbo** [comment]
执行下面的命令就可以测试了：

`
cd 项目目录/config

python emailConf.py
`

**Comment by sherlockwhite** [comment]
> _No description provided._

run.py下面有email(),把run()注释
