### ISSUE TITLE
docker 启动报错

### ISSUE THREAD

**Issue by c2ch** [testerSunshine/12306#194]
![image](https://user-images.githubusercontent.com/35028011/51161976-73b43e80-18cf-11e9-92e6-ea370fd07120.png)
启动报错，怎么解决啊。

**Comment by c2ch** [comment]
已解决，Centos7情况。
1、在控制台里面输入 setenforce 0 关闭 selinux 
2、 在docker 文档里面发现了 –privileged=true 但是，我是写的docker-compose.yml 举一反三。docker-compose 是docker命令的集合 
在docker-compose 服务 里面 增加 privileged: true 
 原文地址：https://blog.csdn.net/yoloyy/article/details/80205279

**Comment by MonsterTan** [comment]
@c2ch 
已解决写入compose文件里。
