### ISSUE TITLE
循环查询余票时忽略 config\ticket_config.yaml 中 station_dates 未来的日期。Skip requesting if date > today.

### ISSUE THREAD

**Issue by lqm678** [testerSunshine/12306#202]
完全可以不用查询未来日期（如 明天、后天）的票。

**Comment by testerSunshine** [comment]
我的理解是你填了那天就去查那天的啊，你的意思是最多查询大于三十天的日期嘛？

**Comment by lqm678** [comment]
不是大于30天，**而是希望支持在配置文件中写未来的日期，同时在查询时会自动略过（不查）未来的日期。**
比如：假设今天12306开始售2019-02-01的票，明天才可以订2019-02-02的票。
希望在配置文件中可以写: 2019-02-01,  2019-02-02 2019-02-03
但查询时不会请求**未来日期** 2019-02-02 及 02-03 的票。

我是根据 log 发现请求未来日期如 **2019-02-02** 的票:
https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=**2019-02-02**&leftTicketDTO.from_station=BJP&leftTicketDTO.to_station=WHN&purpose_codes=ADULT

**Comment by testerSunshine** [comment]
这样不填不就可以啦。。

**Comment by lqm678** [comment]
不支持也行，只是麻烦点，每天改。

**Comment by testerSunshine** [comment]
像官网他都是不让你输入大于30填的日期

**Comment by lqm678** [comment]
不是大于30 。。。是 **开始放票日之后的日期**
