### ISSUE TITLE
下载验证码失败

### ISSUE THREAD

**Issue by li-dw** [testerSunshine/12306#203]
![default](https://user-images.githubusercontent.com/20960402/51235983-de3aac80-19ab-11e9-89b1-4f55495a6193.png)

**Comment by networkextension** [comment]
可能IP 被ban 了，到浏览器上看看，建议刷之前路由器重新拨号

**Comment by li-dw** [comment]
确实是这样的，关闭程序，过一会重新运行就可以了



876650824@qq.com
 
发件人： abigt
发送时间： 2019-01-18 11:03
收件人： testerSunshine/12306
抄送： lidwt; Author
主题： Re: [testerSunshine/12306] 下载验证码失败 (#203)
可能IP 被ban 了，到浏览器上看看，建议刷之前路由器重新拨号

**Comment by ZhaoWenHao1** [comment]
我换了几个IP都不行啊，还是显示下载验证码失败，怎么办？
