### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by suxg001** [testerSunshine/12306#206]
代码执行后如下，快豆已充值，验证码校验失败，请帮看一下，谢谢
*************************************************
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
下载验证码...
下载验证码成功
('Connection aborted.', BadStatusLine("''",))
验证码校验失败,信息为空
下载验证码...
下载验证码成功
('Connection aborted.', BadStatusLine("''",))
验证码校验失败,信息为空
下载验证码...
下载验证码成功
('Connection aborted.', BadStatusLine("''",))
验证码校验失败,信息为空
下载验证码...

**Comment by networkextension** [comment]
用ruokuai.com啊

**Comment by suxg001** [comment]
> 用ruokuai.com啊

用的就是ruokuai.com , 钱花了，快豆也扣了，还是报错，qq群也加不上，说要什么答案，不清楚为什么
('Connection aborted.', BadStatusLine("''",))
验证码校验失败,信息为空
下载验证码...

**Comment by testerSunshine** [comment]
这个是连接不上服务器，可以手动ping api.ruokuai.com ，看能否ping通

**Comment by suxg001** [comment]
PING api.ruokuai.com (120.55.197.145): 56 data bytes
64 bytes from 120.55.197.145: icmp_seq=0 ttl=86 time=35.120 ms
64 bytes from 120.55.197.145: icmp_seq=1 ttl=86 time=34.904 ms
64 bytes from 120.55.197.145: icmp_seq=2 ttl=86 time=34.865 ms
64 bytes from 120.55.197.145: icmp_seq=3 ttl=86 time=34.958 ms

可以ping ，并且联系ruokuai客服查了后天，下载并扣费
