### ISSUE TITLE
我在App上可以成功下单买到某趟车的票, 但是通过该项目却查不到这趟车的票.

### ISSUE THREAD

**Issue by MQL9011** [testerSunshine/12306#211]
我在App上查询到  1月21号 D7371车有票, 并成下单,但是在项目里成功跑起来后却查不到.

![image](https://user-images.githubusercontent.com/11871158/51302622-e1966c80-1a6d-11e9-8e85-27c44027105e.png)

**Comment by huyingya** [comment]
截图看下
