### ISSUE TITLE
pip安装Pillow失败

### ISSUE THREAD

**Issue by daxwang** [testerSunshine/12306#213]
![image](https://user-images.githubusercontent.com/19586089/51315833-15818a00-1a8e-11e9-95ca-a2ed107edd4b.png)

**Comment by xh2015** [comment]
pip版本太低了，如果是mac需要解除sip模式后升级pip

**Comment by networkextension** [comment]
这明显是ubuntu ，装apt install libjpeg-dev

**Comment by ec000** [comment]
apt-get install libjpeg-dev zlib1g-dev
