### ISSUE TITLE
关于12306候补购票的问题

### ISSUE THREAD

**Issue by lilinyuanvr** [testerSunshine/12306#216]
今年12306对于某些路线增加了候补购票功能，不知道是否是有票会优先分配给在进行候补购票的人，我挂了很久一次都没查到有票，然后候补购票有人数限制，每次点都说当前候补人数过多，能否增加加入候补购票的功能。

**Comment by testerSunshine** [comment]
这个用软件点候补，和手动点有啥子区别啊？

**Comment by lilinyuanvr** [comment]
因为候补购票有人数限制   人数太多就不能加入候补  只能等有人候补成功了  然后申请候补

**Comment by testerSunshine** [comment]
已实现
