### ISSUE TITLE
用户名或密码错误 验证码校验失败,信息为空 打码兔未连接

### ISSUE THREAD

**Issue by bengdan** [testerSunshine/12306#22]
正在获取cookie
下载验证码...
用户名或密码错误.
验证码校验失败,信息为空
正在获取cookie
下载验证码...
帐号或密码连续错误，请173秒后重试。
验证码校验失败,信息为空
正在获取cookie
下载验证码...
帐号或密码连续错误，请168秒后重试。
验证码校验失败,信息为空

**Comment by testerSunshine** [comment]
aotu_code_type=1 才是打码兔，2是若快，改下就好
