### ISSUE TITLE
国人的悲哀，原则上讲为了和别人竞争的抢票属于技术作恶

### ISSUE THREAD

**Issue by a358003542** [testerSunshine/12306#220]
国人的悲哀，原则上讲为了和别人竞争的抢票属于技术作恶

**Comment by JackEHolmes** [comment]
不是作恶，类似于织布机抢了织布工人的饭碗。织布工人可以选择忍受低廉的劳动报酬或者改行做其他事，不用抢票软件的人也可以考虑付出时间成本手动抢票或者选择其他交通工具。

当然根源还是票价过低，跟旺盛的需求不对等。

**Comment by vegaoqiang** [comment]
这不是票价低不低的问题, 这是我国现阶段国情问题!

**Comment by DonotAnswer** [comment]
动辄上纲上线，你见过几个国人了？

**Comment by adaaaaaa** [comment]
大概是个撒币，大家别理他。。。到处发这样的帖子。。。

**Comment by testerSunshine** [comment]
只是供人学习而已，不要扯到什么国情，什么票价
