### ISSUE TITLE
【feature】 已验证票自动打码，请合并下！

### ISSUE THREAD

**Issue by Hareis** [testerSunshine/12306#223]
你的项目pull request 不太会用
我在我的仓库新建了一个同名的项目
这个打码接口是免费的，没有次数限制。

https://github.com/Hareis/12306

请帮忙合并下 【网页打码】这个分支
-----------------------------------------

利用了CSDN中 
https://blog.csdn.net/weixin_41578580/article/details/80052065
请大家感谢下博主

**Comment by Hawken94** [comment]
还是建议你按照贡献代码的流程来，对于原作者也是比较方便的

**Comment by Hareis** [comment]
已经发送了
