### ISSUE TITLE
python版本问题

### ISSUE THREAD

**Issue by Sibylzx0** [testerSunshine/12306#229]
我的Python版本是3.5.2，但是说只支持2.7。但是日志还是接着打印了，登录成功啊，cdn查询啊，会导致什么问题吗？这样的日志是正常运行的吧？还是说我还是要重新装2,7版本

**Comment by testerSunshine** [comment]
2.7的支持是最好的，3.6应该是也是支持，如果有哪里错误，自行修改一下就很好用

**Comment by lvtu0316** [comment]
使用 docker 跑的程序，默认的镜像使用的Python 2.7.15，运行报错，

`Collecting matplotlib>=3.0.2 (from -r requirements.txt (line 13))
  Could not find a version that satisfies the requirement matplotlib>=3.0.2 (from -r requirements.txt (line 13)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4)
No matching distribution found for matplotlib>=3.0.2 (from -r requirements.txt (line 13))
You are using pip version 19.0.3, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'ticket' failed to build: The command '/bin/sh -c pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyspider --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`
![image](https://user-images.githubusercontent.com/29847918/61849087-be4bee80-aee2-11e9-916b-be3e8131664a.png)
Matplotlib 3.0.2 版本要求 3.5 以上啊！
