### ISSUE TITLE
早上6点程序没有自动运行。。。

### ISSUE THREAD

**Issue by 60ke** [testerSunshine/12306#235]
早上6点程序没有自动运行。。。

**Comment by testerSunshine** [comment]
看看你电脑的本地时间

**Comment by 60ke** [comment]
> 看看你电脑的本地时间
电脑是mac的，本地时间正确 周末在家跑的时候还是可以的，但是在公司这两天早上9点多到程序没运行，第一次以为可能是中途断网的缘故，今天10点多看到还是没自动运行
