### ISSUE TITLE
关于open打开本地文件的问题

### ISSUE THREAD

**Issue by achievejia** [testerSunshine/12306#236]
1、在ticketConf.py文件中增加utf-8配置，如图
![image](https://user-images.githubusercontent.com/12773008/51581402-e0988b80-1f02-11e9-934c-0a931bba317c.png)
2、在select_ticket_info.py文件中增加utf-8配置，如图
![image](https://user-images.githubusercontent.com/12773008/51581431-fefe8700-1f02-11e9-894d-e5e910869733.png)

**Comment by achievejia** [comment]
我本地运行python代码，缺少这两个配置会报字符串编译错误，加上就可运行正常

**Comment by BlancRay** [comment]
请确认python版本号
