### ISSUE TITLE
使用缓存中查找的联系人信息之后报错

### ISSUE THREAD

**Issue by forever-xiaoyu** [testerSunshine/12306#241]
![image](https://user-images.githubusercontent.com/26760933/51812653-70687c00-22ed-11e9-9fbc-1d8a2bf89fee.png)
不知道究竟是什么原因，求问

**Comment by testerSunshine** [comment]
这个不是联系人信息出错了，ioError可以参照https://github.com/testerSunshine/12306/issues/159
