### ISSUE TITLE
网址有改了，这回是query

### ISSUE THREAD

**Issue by s917421909** [testerSunshine/12306#250]
如题，出现ip异常可以再看看，是不是又改了

**Comment by Gmle7** [comment]
我也遇到了，还说可能是时间设置得不对

**Comment by Gmle7** [comment]
主要是手动查询url，也打不开地址

**Comment by s917421909** [comment]
> 主要是手动查询网址，也打不开地址

嗯嗯，目前好像还是没变~现在还挂着呢

**Comment by Gmle7** [comment]
**
![``%DMAY7C04F2AFIEYEI2M9](https://user-images.githubusercontent.com/24665995/55150452-1c600380-5187-11e9-875f-8a343e11b429.png)
**把这个文件改一下，好像就可以了。来自交流7群

**Comment by ahlblzk** [comment]
![微信图片_20190421121935](https://user-images.githubusercontent.com/7858842/56465441-bede7000-642f-11e9-8481-6d27d863b48c.png)
更新了最新的代码之后，登录还是有问题，有谁碰到过
