### ISSUE TITLE
时间范围查票，会查询到时间范围外的票

### ISSUE THREAD

**Issue by 1244791720** [testerSunshine/12306#256]
如题

**Comment by testerSunshine** [comment]
看看你的时间范围配置

**Comment by 1244791720** [comment]
时间范围设置 最早时间 11：00 
最晚到达时间 21：00
take_time 2:00
is_by_time True
然后会抢到22：00之后的票

**Comment by testerSunshine** [comment]
他是不是到达时间是早上11点以后，也就是夸天的，比如2019.4.5晚上22：00出发。第二天早上12点到，看下是那趟车

**Comment by 1244791720** [comment]
不是啊，就是22点到第二天24点

**Comment by testerSunshine** [comment]
他这个跨天的计算有点问题
22：00点是符合最早出发时间，所以为True
00：15是符合最晚抵达时间的，所以也为True
我想办法改下这里

**Comment by 1244791720** [comment]
好的，谢谢。感谢您的分享。

**Comment by testerSunshine** [comment]
已修复
