### ISSUE TITLE
登录失效

### ISSUE THREAD

**Issue by xiangshu129** [testerSunshine/12306#260]
**************************************************
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,149
验证码通过,开始登录..
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,77,184,77,184,149
验证码校验失败
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为184,77,256,149
验证码通过,开始登录..
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,77,184,77
验证码通过,开始登录..

**Comment by xiangshu129** [comment]
这个似乎和前段时间登陆失效的问题类似

**Comment by testerSunshine** [comment]
我这边测试了一下，是可以，要拉取 https://github.com/testerSunshine/12306/commit/ccde952432d5dd1f25f46c2ff01a8ff5ded52cf8 这个歌提交的代码，才可以 @253

**Comment by xiangshu129** [comment]
我使用的是最新的代码，但是不行。刚才我又试了下，还是不行，同样的错误。

commit 5f4f5d0fd55b5c41a215b8bcc4f9195041a6d01b (HEAD -> master, origin/master, origin/HEAD)
Author: wenxianping <931128603@qq.com>
Date:   Sun Apr 7 22:30:28 2019 +0800

    修复跨天时间计算问题 #256
