### ISSUE TITLE
login 返回参数为空

### ISSUE THREAD

**Issue by BlancRay** [testerSunshine/12306#261]
验证码识别成功后仍需要验证码
```验证码识别坐标为40,77,184,77
验证码通过,开始登录..
需要验证码
下载验证码...
```
log文件中可以看到
```url: /passport/web/login 返回参数为空 (logger.py:61)```
从urlConf文件中可以确认是login的登录接口问题

**Comment by BlancRay** [comment]
参照[py12306](https://github.com/pjialin/py12306/issues/155#issuecomment-481082916)的issue，应该是cookie里RAIL_DEVICEID的计算发生了变化

**Comment by testerSunshine** [comment]
嗯，应该是要计算了，但是我这边的RAIL_DEVICEID是动态更新的。你这边的代码需要更新下 #255

**Comment by BlancRay** [comment]
是master分支最新的commit: 5f4f5d0吗？

**Comment by BlancRay** [comment]
> 嗯，应该是要计算了，但是我这边的RAIL_DEVICEID是动态更新的。你这边的代码需要更新下 #255

是master分支最新的commit: 5f4f5d0吗？

**Comment by testerSunshine** [comment]
这个是最新的，你拉下来还会出现登不上去吗？

**Comment by BlancRay** [comment]
> 这个是最新的，你拉下来还会出现登不上去吗？

是的，我看了计算出来的值和浏览器cookie的值，是不一样的
用浏览器的cookie替换后就可以登录上了

**Comment by testerSunshine** [comment]
那暂时手动替换一下吧，我这边再想想办法看能自动获取不
