### ISSUE TITLE
我这边测试了一下，是可以，要拉取 https://github.com/testerSunshine/12306/commit/ccde952432d5dd1f25f46c2ff01a8ff5ded52cf8 这个歌提交的代码，才可以 @253

### ISSUE THREAD

**Issue by xiangshu129** [testerSunshine/12306#262]
我使用的是最新的代码，但是不行。刚才我又试了下，还是不行，同样的错误。

commit 5f4f5d0 (HEAD -> master, origin/master, origin/HEAD)
Author: wenxianping 931128603@qq.com
Date: Sun Apr 7 22:30:28 2019 +0800

修复跨天时间计算问题 #256

**Comment by testerSunshine** [comment]
你这个是要说啥子，兄弟

**Comment by xiangshu129** [comment]
@testerSunshine 

登陆失效的问题，我即使使用最新的代码，还是反复下载验证码尝试登陆：

**************************************************
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,149
验证码通过,开始登录..
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,77,184,77,184,149
验证码校验失败
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为184,77,256,149
验证码通过,开始登录..
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为112,77,184,77
验证码通过,开始登录..

**Comment by testerSunshine** [comment]
奥，你是说后面的那些版本都等登录不上去吗？

**Comment by xiangshu129** [comment]
不是100%登陆不上，我刚才在调试的时候，就成功过一次。

        else:
  -------------这个地方没有输出，所以看不见原因，建议把tresult或tresult['result_message']输出。要不然在极端的情况下，看到验证码都识别成功了，但是一直在重复登陆
            return False

**Comment by OLOrz9527** [comment]
遇到了相同的情况

**Comment by xiangshu129** [comment]
如果把对应的message打印出来的话，可以到这个失败是因为”重试次数达到上限“， @testerSunshine 可以帮着解决下吗？

开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
需要验证码
下载验证码...
下载验证码成功
<Response [200]>
验证码识别坐标为40,77,184,77
验证码通过,开始登录..
{'message': u'\u91cd\u8bd5\u6b21\u6570\u8fbe\u5230\u4e0a\u9650', 'code': 99999}
NA
NA
重试次数达到上限
需要验证码
下载验证码...
下载验证码成功
