### ISSUE TITLE
快豆消耗的太快了，一次要43.75个快豆？充了10000的豆子，一天多就用没了？

### ISSUE THREAD

**Issue by aiaiaiaiaiai** [testerSunshine/12306#263]
![2222222222](https://user-images.githubusercontent.com/25001192/56465191-85a40100-642b-11e9-9644-29aa262c2b1e.png)
![33333333](https://user-images.githubusercontent.com/25001192/56465205-b126eb80-642b-11e9-9da9-8eeeeab46dba.png)
19号晚上充的，今天21号早上就没有了，是不是有问题啊？

**Comment by Google4g** [comment]
我也觉得有问题，去年抢回家的票5块钱可以用一个多星期，现在3天5块，有点恐怖。

**Comment by testerSunshine** [comment]
是由于登录接口失效的问题导致，抱歉，感觉devicesId的有效期过短，需要自己试试更新devicesId才能保证登录顺畅
