### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by DamonChow** [testerSunshine/12306#268]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/8411901/56786328-3f83de80-682b-11e9-9450-7f0bfcec2a53.png">

**Comment by ifirework** [comment]
全是这个问题

**Comment by Zero0Infinite** [comment]
config文件夹下urlConf.py的142行代码替换一下：
"req_url": "/otn/HttpZF/logdevice?algID=3MNPnalpAK&hashCode=Xe2OuO_OAeAxORrKsoUUm-nfpeSmIVr4eEQB88KL_mw&FMQw=1&q4f3=zh-CN&VPIf=1&custID=133&VEek=unknown&dzuS=0&yD16=0&EOQP=49a9fbfe2beb0490836324ceb234fef4&lEnu=167772687&jp76=52d67b2a5aa5e031084733d5006cc664&hAqN=Win32&platform=WEB&ks0Q=d22ca0b81584fbea62237b14bd04c866&TeRS=760x1280&tOHY=24xx800x1280&Fvje=i1l1o1s1&q5aJ=-8&wNLf=99115dfb07133750ba677d055874de87&0aew=Mozilla/5.0%20(Windows%20NT%206.1)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/73.0.3683.103%20Safari/537.36&E3gR=d3b553e59408679e9cefa2ddea8ff44c&timestamp={0}",

这个url是由一个js动态生成的，可能需要定期的更换一下。最好自己下一个fiddler通过浏览器对12306进行抓包获取，抓包前记得清除下浏览器的cookie。

**Comment by testerSunshine** [comment]
自己可以去浏览器抓取RAIL_DEVICEID，填入即可解决问题，已更新教程 @Zero0Infinite 这个同学的教程也可以
