### ISSUE TITLE
验证通过但是登录不了，无限循环

### ISSUE THREAD

**Issue by DeemoASCII** [testerSunshine/12306#272]
![image](https://user-images.githubusercontent.com/22360953/57497531-a9f84c80-730a-11e9-8d38-c7ae809bc535.png)
 我使用的是 python3.7.2，mac 系统，用若快打码，验证码应该通过了但是一直登录不了，请问这个怎么办。

**Comment by Chenmu2016** [comment]
一样的问题

**Comment by 908875137** [comment]
我也出现这个问题了

**Comment by wyy919** [comment]
我也是

**Comment by wyy919** [comment]
解决了，注意导入PyYaml的版本号：：：PyYAML==4.2b1

**Comment by Chenmu2016** [comment]
config文件夹下urlConf.py的142行代码替换一下：
"req_url": "/otn/HttpZF/logdevice?algID=
12306重新抓个包，把logdevice?algID=后面的内容替换一下，记得先清一下cookie

**Comment by whoyao** [comment]
> config文件夹下urlConf.py的142行代码替换一下：
> "req_url": "/otn/HttpZF/logdevice?algID=
> 12306重新抓个包，把logdevice?algID=后面的内容替换一下，记得先清一下cookie

测试有效 @skipjackcn 你应该是没有修改timestamp，注意把timestamp改成{0}

**Comment by zhangleiDev** [comment]
确实是,一直输入验证码,一直又让重新输入,明明已经输入正确了

**Comment by testerSunshine** [comment]
自己可以去浏览器抓取RAIL_DEVICEID，填入即可解决问题
