### ISSUE TITLE
打码平台错误: 内部处理发生故障

### ISSUE THREAD

**Issue by GeTuojian** [testerSunshine/12306#275]
配置应该都没问题，打码平台也有余额，但是显示：
**************************************************
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
None
需要验证码
下载验证码...
下载验证码成功
None
<Response [200]>
打码平台错误: 内部处理发生故障，如果频繁出现此提示请联系客服。api c.Do:Post http://172.16.218.46/create.json: dial tcp 172.16.218.46:80: connectex: No connection could be made because the target machine actively refused it., 请登录打码平台查看-http://www.ruokuai.com/client/index?6726

有哪位大神遇到过么..

**Comment by masterwangf** [comment]
碰到了  据说是跑路了  不知道真的假的

**Comment by Ding-Fan** [comment]
同。遇到这个问题好几天了。

**Comment by testerSunshine** [comment]
改成本地识别了，试试
