### ISSUE TITLE
opencv-python 的兼容性问题

### ISSUE THREAD

**Issue by zwc456baby** [testerSunshine/12306#280]
最近发现在 requirements.txt 新增了 opencv-python 和 tensorflow 的依赖库。
这是神经网络识别相关的库。但是 opencv-python 似乎只有 x86 和 amd 架构。。
也就是说，如果 linux 是运行在 arm 架构上（比如我的 树莓派，不知道 mips 架构是怎样的），需要从源码编译安装 opencv-python 。
否则会出现下面的错误：
>ERROR: Could not find a version that satisfies the requirement opencv-python (from -r requirements.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for opencv-python (from -r requirements.txt (line 10))

而原来的只需要 pull 下来，执行 `pip install -r requirements.txt` 就可以直接运行。
显然，最近的更新对 x86 和 amd 架构以外的系统很不友好。。。因为不能直接从仓库安装 opencv-python 库。做不到开箱即用

**Comment by zwc456baby** [comment]
python 版本是 2.7.13

**Comment by Clinan** [comment]
所以你最后是怎么操作的
