### ISSUE TITLE
Unable to open file

### ISSUE THREAD

**Issue by skartwang** [testerSunshine/12306#281]
Message: '出参：b\'/**/jQuery19108016482864806321_1554298927290({"image":"/9j/4AAQSkZJRgABAgAAAQABAAD/*****************************","result_message":"\\xe7\\x94\\x9f\\xe6\\x88\\x90\\xe9\\xaa\\x8c\\xe8\\xaf\\x81\\xe7\\xa0\\x81\\xe6\\x88\\x90\\xe5\\x8a\\x9f","result_code":"0"});\''
Arguments: ()
下载验证码成功
Unable to open file (unable to open file: name = 'D:\github\12306\model.v2.0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
None

**Comment by testerSunshine** [comment]
你要下载model.v2.0.h5 这个文件放到D:\github\12306\目录下

**Comment by testerSunshine** [comment]
模型下载链接:https://pan.baidu.com/s/1rS155VjweWVWIJogakechA  密码:bmlm
