### ISSUE TITLE
使用本地验证码识别，配置文件如何设置呢？

### ISSUE THREAD

**Issue by lvtu0316** [testerSunshine/12306#282]
使用本地验证码识别，配置文件如何设置呢？

![image](https://user-images.githubusercontent.com/29847918/61842948-8cc82880-aecc-11e9-8d6e-977357bcba3d.png)

**Comment by lvtu0316** [comment]
若快已经无法使用了，

**Comment by testerSunshine** [comment]
本地识别，这个地方填2就行，替代若快是识别
