### ISSUE TITLE
python run.py 报错

### ISSUE THREAD

**Issue by zwc456baby** [testerSunshine/12306#283]
运行环境:python 3.5.3

```
  File "/home/pi/software/12306/verify/pretreatment.py", line 26
    with open(f'{PATH}/{fn}.jpg', 'wb') as fp:
                               ^
SyntaxError: invalid syntax
```

**解决办法**
修改 `verify/pretreatment.py` 文件第26行，将 `open(f'{PATH}/{fn}.jpg', 'wb')` 改成 `open('{PATH}/{fn}.jpg', 'wb')` ，也就是把字符串前面的 `f` 移除的就好了

没有测试这种修改方式在python 2.7 或者 3.6 等版本会怎么样。所以只提出了解决方法

**Comment by zwc456baby** [comment]
看了一下，在字符串前加 f 是python 3.6 以后加入的新功能。

**Comment by testerSunshine** [comment]
你升级到3.6试试，这个确实是3.6的功能
