### ISSUE TITLE
查询有余票，但是提交订单时提示余票不足

### ISSUE THREAD

**Issue by kmosi0** [testerSunshine/12306#288]
手机查询有票，但是程序提交订单时提示余票不足，尝试过两个下单接口都无法正常提交订单。

**Comment by kmosi0** [comment]
车次: * 始发车站: * 终点站: * 硬座: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
I0816 21:23:32.986885 18004 logger.py:61] url: /otn/leftTicket/submitOrderReques
t
入参: [('secretStr', 'CwYuBOOdH+KgLRj7XimJRBMELUtmGh2Isb/imM+Y0c04t+fzcWq+btiFxj
tZ4worBrxnY+n403sK\nfcrn5FXjOyC/UwOCgEqxzW9PSvMATg8KfNIYng/habHlCjBb6cCjyfBHElRl
E15qhEm6ycPDcbxr\nIHf/ei9tHoKLl1XSj4rwjL2v/SBKFkB2yswhefxOqMTSukPUWu7ZPWtpPPAJNu
3UTb0zi/JAOHET\n5mXBllfrUkrYqQ8MQSZLUMcYjVXjs4+7hnKziD6QN9RUWdoO+62n8U89lLHL1FUL
OtKzRuSjHS1c\nMbSwoA=='), ('train_date', '2019-08-27'), ('back_train_date', '201
9-08-16'), ('tour_flag', 'dc'), ('purpose_codes', 'ADULT'), ('query_from_station
_name', 'WN'), ('query_to_station_name', 'SZ')]
请求方式: post

I0816 21:23:34.301960 18004 logger.py:61] 出参：b'{"validateMessagesShowId":"_va
lidatorMessage","status":true,"httpstatus":200,"data":"N","messages":[],"validat
eMessages":{}}'
I0816 21:23:35.522030 18004 logger.py:61] url: /otn/confirmPassenger/checkOrderI
nfo
入参: OrderedDict([('passengerTicketStr', '1,0,1,*,*,,N'), ('oldPassengerStr', '*,1,*,1_'), ('REPEAT_SUBMIT
_TOKEN', '710b7d44a641e2c816c4b414b3981639'), ('randCode', ''), ('cancel_flag',
2), ('bed_level_order_num', '000000000000000000000000000000'), ('tour_flag', 'dc
'), ('_json_att', '')])
请求方式: post

I0816 21:23:35.907052 18004 logger.py:61] 出参：b'{"validateMessagesShowId":"_va
lidatorMessage","status":true,"httpstatus":200,"data":{"errMsg":"\xe4\xbd\x99\xe
7\xa5\xa8\xe4\xb8\x8d\xe8\xb6\xb3\xef\xbc\x81","submitStatus":false},"messages":
[],"validateMessages":{}}'
余票不足！

**Comment by SureWho** [comment]
相同的问题，求解
@testerSunshine

**Comment by itsmartkit** [comment]
看到的余票是缓存

**Comment by zsure** [comment]
> 看到的余票是缓存

明明12306购票上也有票，还是显示余票不足，求解 @itsmartkit

**Comment by itsmartkit** [comment]
> > 看到的余票是缓存
> 
> 明明12306购票上也有票，还是显示余票不足，求解 @itsmartkit

这个余票应该是这样的：比如你现在看到了一辆车有10张余票，这10张有可能是已经被人提交订单（但未支付），此时你仍然可以查到余票，也可以提交订单，在提交订单后确认的时候，系统会排队去查真实余票数量（去掉未支付的），此时会显示余票不足。当然还有可能是cdn缓存的原因，但是前者可能性更大。所以git上开源的抢票代码，大部分都有“小黑屋”的功能。

**Comment by itsmartkit** [comment]
> > 看到的余票是缓存
> 
> 明明12306购票上也有票，还是显示余票不足，求解 @itsmartkit

12306采用了cdn加速技术，比如你现在看到了一辆车有10张余票，这10张有可能是已经被人提交订单（但未支付），在一定的时间内你仍然可以查到余票，也可以提交订单，在提交订单后确认的时候，系统会排队去查真实的余票数量，此时会显示余票不足，因为缓存服务器还没有同步真实的余票信息，查到的余票数量是缓存。因此git上开源的抢票项目，大部分都有“小黑屋”的功能。
