### ISSUE TITLE
进入排队失败

### ISSUE THREAD

**Issue by linkoln** [testerSunshine/12306#289]
调用getQueueCountUrl接口老是返回
`"{\"validateMessagesShowId\":\"_validatorMessage\",\"url\":\"/leftTicket/init\",\"status\":false,\"httpstatus\":200,\"messages\":[\"系统忙，请稍后重试\"],\"validateMessages\":{}}"`
，请问应该怎么解决？

在这个步骤之前的接口都可以成功的，前一步checkOrderInfo是成功的，返回数据是，`"{\"validateMessagesShowId\":\"_validatorMessage\",\"status\":true,\"httpstatus\":200,\"data\":{\"ifShowPassCode\":\"N\",\"canChooseBeds\":\"N\",\"canChooseSeats\":\"Y\",\"choose_Seats\":\"OM9\",\"isCanChooseMid\":\"N\",\"ifShowPassCodeTime\":\"553\",\"submitStatus\":true,\"smokeStr\":\"\"},\"messages\":[],\"validateMessages\":{}}"`。但getQueueCountUrl这一步就没成功。求教！

**Comment by testerSunshine** [comment]
#288
