### ISSUE TITLE
能不能给我们这些坐直达特快穷孩子一条生路

### ISSUE THREAD

**Issue by DuBaojiang** [testerSunshine/12306#291]
check_train_type 里加一下Z（直达），T（特快），K（快速）吧，测试过 other 里刷不出这些车次。

**Comment by testerSunshine** [comment]
不要按照时间选，按照车次选试试

**Comment by DuBaojiang** [comment]
函数 check_tran_type 里把高铁 G 动车 D 以外的车全部改为其他 O，所以无法购买直达 Z，特快 K 等车次。看着国庆抢票到了，告给你们看能不能帮到其他小伙伴。没人提过看来大家都没这个需求，就我买不起高铁，动车。难过。

**Comment by nowherelanded** [comment]
好狠
