### ISSUE TITLE
求助：illegal hardware instruction

### ISSUE THREAD

**Issue by liangzhdp** [testerSunshine/12306#294]
运行sudo python run.py出现：
Using TensorFlow backend.
zsh: illegal hardware instruction  sudo python run.py

网上说tensorflow的问题，查了下版本：
Name: tensorflow
Version: 1.14.0

版本比网上的低不少，但似乎无法升级了，怎么办？
>>> sudo python -m pip install --upgrade tensorflow
Requirement already up-to-date: tensorflow in /usr/lib/python3.7/site-packages (1.14.0)
Requirement already satisfied, skipping upgrade: protobuf>=3.6.1 in /usr/lib/python3.7/site-packages (from tensorflow) (3.9.1)
Requirement already satisfied, skipping upgrade: wheel>=0.26 in /usr/lib/python3.7/site-packages (from tensorflow) (0.33.6)
Requirement already satisfied, skipping upgrade: gast>=0.2.0 in /usr/lib/python3.7/site-packages (from tensorflow) (0.2.2)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in /usr/lib/python3.7/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in /usr/lib/python3.7/site-packages (from tensorflow) (1.11.2)
Requirement already satisfied, skipping upgrade: termcolor>=1.1.0 in /usr/lib/python3.7/site-packages (from tensorflow) (1.1.0)
Requirement already satisfied, skipping upgrade: absl-py>=0.7.0 in /usr/lib/python3.7/site-packages (from tensorflow) (0.8.0)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in /usr/lib/python3.7/site-packages (from tensorflow) (1.0.8)
Requirement already satisfied, skipping upgrade: grpcio>=1.8.6 in /usr/lib/python3.7/site-packages (from tensorflow) (1.23.0)
Requirement already satisfied, skipping upgrade: astor>=0.6.0 in /usr/lib/python3.7/site-packages (from tensorflow) (0.8.0)
Requirement already satisfied, skipping upgrade: numpy<2.0,>=1.14.5 in /usr/lib/python3.7/site-packages (from tensorflow) (1.17.1)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/lib/python3.7/site-packages (from tensorflow) (1.10.0)
Requirement already satisfied, skipping upgrade: tensorboard<1.15.0,>=1.14.0 in /usr/lib/python3.7/site-packages (from tensorflow) (1.14.0)
Requirement already satisfied, skipping upgrade: tensorflow-estimator<1.15.0rc0,>=1.14.0rc0 in /usr/lib/python3.7/site-packages (from tensorflow) (1.14.0)
Requirement already satisfied, skipping upgrade: google-pasta>=0.1.6 in /usr/lib/python3.7/site-packages (from tensorflow) (0.1.7)
Requirement already satisfied, skipping upgrade: setuptools in /usr/lib/python3.7/site-packages (from protobuf>=3.6.1->tensorflow) (41.0.1)
Requirement already satisfied, skipping upgrade: h5py in /usr/lib/python3.7/site-packages (from keras-applications>=1.0.6->tensorflow) (2.9.0)
Requirement already satisfied, skipping upgrade: werkzeug>=0.11.15 in /usr/lib/python3.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (0.15.5)
Requirement already satisfied, skipping upgrade: markdown>=2.6.8 in /usr/lib/python3.7/site-packages (from tensorboard<1.15.0,>=1.14.0->tensorflow) (3.1.1)

**Comment by testerSunshine** [comment]
我的电脑上也是 1.14.0, 运行着没这个问题
重新装也会有这个问题嘛？

**Comment by liangzhdp** [comment]
tensorflow已经重装过了，还是不行。
