### ISSUE TITLE
验证码校验失败

### ISSUE THREAD

**Issue by AsiaChampion** [testerSunshine/12306#296]
12306.image.model.h5，model.v2.0.h5  两个文件放在根目录下的（与run.py同一位置），但是一直报错

下载验证码成功
Corrupt JPEG data: 12 extraneous bytes before marker 0xd9
Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder_84:0", shape=(3, 3, 1, 64), dtype=float32) is not an element of this graph.
None
验证码校验失败

**Comment by caoliang12121** [comment]
me too

**Comment by pluone** [comment]
下载这两个文件，放到项目根目录下
model.h5
12306.image.model.h5

请阅读项目文档
> 验证码目前可以本地识别，需要下载模型，放于项目根目录，全部代码来源于此项目 传送门，表示感谢
  PS:   1. 模型下载链接:https://pan.baidu.com/s/1rS155VjweWVWIJogakechA  密码:bmlm
     群里面也可以下载

**Comment by AsiaChampion** [comment]
你好。这2个文件我有放在项目根目录下的

[cid:E61990BFB1C24227BDB8489E3B81C5FE]
在 2019年9月2日 +0800 PM10:55，Frank Pei <notifications@github.com>，写道：

下载这两个文件，放到项目根目录下
model.h5
12306.image.model.h5

请阅读项目文档

验证码目前可以本地识别，需要下载模型，放于项目根目录，全部代码来源于此项目 传送门，表示感谢
PS: 1. 模型下载链接:https://pan.baidu.com/s/1rS155VjweWVWIJogakechA 密码:bmlm
群里面也可以下载

**Comment by testerSunshine** [comment]
你装的TensorFlow有问题

**Comment by testerSunshine** [comment]
今天验证了下，不是TensorFlow的问题，是因为有缓存
fb85c552542f2fa7e8099d4a1b71d0260990ae60

**Comment by gctian** [comment]
@testerSunshine mac 还是出现了验证码校验失败的问题

下载验证码...
下载验证码成功
Corrupt JPEG data: 16 extraneous bytes before marker 0xd9
softmax() got an unexpected keyword argument 'axis'
None
验证码校验失败

**Comment by GloryXu** [comment]
@testerSunshine win10还是报错
![image](https://user-images.githubusercontent.com/19256739/65370171-7ea64680-dc88-11e9-9c81-8b4b46e248e8.png)
