### ISSUE TITLE
大佬们为啥不直接出个docker image

### ISSUE THREAD

**Issue by Oyejileo** [testerSunshine/12306#297]
大佬们，为啥不直接出个docker image ，装环境什么的最费时间了0.0

**Comment by majulong** [comment]
不是有dockerfile么
直接docker build 不就有咯

**Comment by xiaochonghao** [comment]
> 不是有dockerfile么
> 直接docker build 不就有咯

直接推到远程，拉下来更方便啊

**Comment by xiaochonghao** [comment]
> 不是有dockerfile么
> 直接docker build 不就有咯

@majulong 直接推到远程，别人拉下来更方便啊
