### ISSUE TITLE
建议支持新推送通道

### ISSUE THREAD

**Issue by Alion548** [testerSunshine/12306#301]
Bark
项目地址：https://github.com/Finb/Bark

**Comment by testerSunshine** [comment]
这个推送布置需要服务端，暂时不考虑

**Comment by Alion548** [comment]
> 这个推送布置需要服务端，暂时不考虑

默认不用搭建服务端
![image](https://user-images.githubusercontent.com/8340545/64529182-e1204e00-d33c-11e9-9478-855e667b4a9e.png)
