### ISSUE TITLE
求解决：登录过程验证码已经识别过了，登录请求返回tresult: {'code': 99999, 'message': '重试次数达到上限'}，网页上登录没有问题！

### ISSUE THREAD

**Issue by gongjiaqiang** [testerSunshine/12306#303]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Admingyu** [comment]
+1

**Comment by testerSunshine** [comment]
更新105版本，改用selenium试试

**Comment by brczo** [comment]
+1
