### ISSUE TITLE
我就想知道下载了怎么用

### ISSUE THREAD

**Issue by effi901** [testerSunshine/12306#304]
今日头条上看过来的，我下载了download zip，怎么用？？？

**Comment by CasWen** [comment]
我也不知道怎么用？pycharm都安装了

**Comment by Admingyu** [comment]
https://github.com/testerSunshine/12306
首页有说明，看了吗？（需要一些基础的，看不懂搜一下相关技术），不要不会用上来就提个`BUG` ...

**Comment by effi901** [comment]
> 我也不知道怎么用？pycharm都安装了

算了 不研究了 搞了两个小时不知道怎么用

**Comment by liaomengge** [comment]
很快就搞定了，顺带刷了张票试了下，还是很不错的，希望能支持更多的推送渠道和方式 ~

![image](https://user-images.githubusercontent.com/12670328/64310889-a2089a80-cfd4-11e9-8ab1-331162c46feb.png)
