### ISSUE TITLE
初始化登录一直302

### ISSUE THREAD

**Issue by liaomengge** [testerSunshine/12306#305]
![image](https://user-images.githubusercontent.com/12670328/64315818-b2754100-cfe5-11e9-8cb8-d45618a59cc1.png)

这个问题怎么处理？

**Comment by testerSunshine** [comment]
更新105版本，改用selenium试试

**Comment by liaomengge** [comment]
> 更新105版本，改用selenium试试

还是不行~

**Comment by testerSunshine** [comment]
那就是你的ip有问题了

**Comment by fanyuexiang** [comment]
应该是IP被封了，在网页端登录12306的时候页面会出错，等一会就好了

**Comment by yxzoro** [comment]
的却是多试一会就好了。。。
