### ISSUE TITLE
ubuntu 18.04 在执行run的时候有个报错

### ISSUE THREAD

**Issue by septnn** [testerSunshine/12306#306]
**ubuntu 18.04 在执行run的时候有个报错，报错信息如下**
ImportError: libSM.so.6: cannot open shared object file:

**需要安装python-qt4**
apt install python-qt4

**无备选**

**报错**
ImportError: libSM.so.6: cannot open shared object file:

**Comment by testerSunshine** [comment]
看起来是你装的库有问题，，不过不需要装qt啊？
libSM.so

**Comment by yrong** [comment]
apt update && apt install -y libsm6 libxext6
pip install opencv-python
