### ISSUE TITLE
有哪位好心人帮帮我嘛，一直报错，依赖我也安装了，也重启了就是不行，下面是信息

### ISSUE THREAD

**Issue by Brandzhao01** [testerSunshine/12306#309]
zhaojundeMacBook-Air:12306-master zhaojun$ pip3 install requests
Requirement already satisfied: requests in /Users/zhaojun/Library/Python/3.7/lib/python/site-packages (2.18.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests) (2019.6.16)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests) (3.0.4)
zhaojundeMacBook-Air:12306-master zhaojun$ sudo python run.py
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.pushbearConf import sendPushBear
  File "/Users/zhaojun/Documents/12306-master/config/pushbearConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/Users/zhaojun/Documents/12306-master/myUrllib/httpUtils.py", line 6, in <module>
    import requests
ImportError: No module named requests
zhaojundeMacBook-Air:12306-master zhaojun$

**Comment by Brandzhao01** [comment]
对了，我用的VS code,嫌麻烦就没有安装phthon IDE了

**Comment by silentbird** [comment]
依赖库没装全吧 在项目根目录`  pip3 install -r requirements.txt  `试试

**Comment by testerSunshine** [comment]
你的依赖库没装好

**Comment by Brandzhao01** [comment]
谢谢各位大佬
解决了，是版本的问题
mac自带python2.7和3.7
依赖安装成功后执行sudo python3 run.py就可以了
