### ISSUE TITLE
chromedriver路径设置问题

### ISSUE THREAD

**Issue by silentbird** [testerSunshine/12306#311]
CHROME_PATH = "/Users/wenxianping/Downloads/chromedriver"
想请教下 这个路径windows环境下要怎么填写   C:/chromedriver 这样吗

**Comment by silentbird** [comment]
问题光速解决了  原来是要把chromedriver放到chrome.exe根目录  环境变量里添加chrome根目录 CHROME_PATH路径写这个
` CHROME_PATH = "C:/Program Files (x86)/Google/Chrome/Application/chromedriver.exe"`

**Comment by lyc-python** [comment]
自问自答秀操作，对于我们小白很有帮助，感谢！
