### ISSUE TITLE
"12306休息时间，本程序自动停止,明天早上六点将自动运行"功能不能正常启动

### ISSUE THREAD

**Issue by superli90** [testerSunshine/12306#312]
**描述问题**
```
系统输出“12306休息时间，本程序自动停止,明天早上六点将自动运行”。但是第二天早上并没有起来
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - linux
 - python3.6.0
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
更新版本1.1.105
