### ISSUE TITLE
在12306的网站上查有有票，但软件提示下单无票  并返回以下提示

### ISSUE THREAD

**Issue by lll423** [testerSunshine/12306#314]
**描述问题**
```
在12306的网站上查有有票，但软件提示下单无票  并返回以下提示
```
**重现步骤**
```
步骤一
```
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
广州-乐昌 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryT?leftTicketDTO.train_date=2019-9-26&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=LCQ&purpose_codes=ADULT, 可以手动查询是否有票
正在第2次查询 随机停留时长：2.74 乘车日期: 2019-9-26 车次：K642  下单无票 无候补机会 耗时：464.844ms

**环境信息**
 - windows 10
 - python3.6.4
 - 订票小助手版本 1.1.105

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
改下日期2019-09-26
