### ISSUE TITLE
Pushbear 推送失效了？

### ISSUE THREAD

**Issue by TimoYoung** [testerSunshine/12306#316]
**描述问题**
```
pushbear配置无误，在run.py中PushbearConf()测试返回正常。 微信无法收到消息。
```

**截图&日志**
```
➜  12306 git:(master) ✗ sudo python run.py
Password:
Using TensorFlow backend.
邮件已通知, 请查收
已下发 pushbear 微信通知, 请查收
```
**环境信息**
 - mac 
 - python3.6.7
 - 订票小助手版本 1.1.105

**额外的备注**

貌似是这个原因：
Pushbear官网：从2019年6月开始，只提供「已经微信认证后的服务号」进行授权后，用其自有接口权限代发。是否可以改用一对一的接口，或增加其他推送方式？

**Comment by mzit** [comment]
没有认证服务号已经收不到消息
是否考虑换用server酱

**Comment by testerSunshine** [comment]
有人提pr了，已合并server酱
