### ISSUE TITLE
带有学生信息的联系人不能抢票

### ISSUE THREAD

**Issue by kongwenyan** [testerSunshine/12306#32]
带有学生信息的联系人会报错 乘客证件类型错误
使用成人信息的联系人则可以直接抢。
请问这个有办法解决吗
![dsfa](http://ww1.sinaimg.cn/large/0060lm7Tly1fnw4m4eub7j316y0p4dr4.jpg)

**Comment by CoCoThink** [comment]
同问

**Comment by testerSunshine** [comment]
已解决
