### ISSUE TITLE
windows验证码检校失败  运行run.py

### ISSUE THREAD

**Issue by ShichaoJin** [testerSunshine/12306#324]
**描述问题**
```
验证码检校失败  运行run.py
```
**重现步骤**
```
步骤一
```
**截图&日志**

![image](https://user-images.githubusercontent.com/28957118/64485692-fff7e500-d255-11e9-8029-f8085f18825f.png)
![image](https://user-images.githubusercontent.com/28957118/64485166-852bcb80-d24f-11e9-8c85-551896c50699.png)

**环境信息**
 - windows
 - python3.6
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by jzz3933** [comment]
在版本1.1.106上也得到同样的错误

**Comment by testerSunshine** [comment]
你的tensorflow没装好，中途有报错了么，还有那个图片检查下是否设置成功
