### ISSUE TITLE
返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by syshlang** [testerSunshine/12306#325]
准备提交候补订单，当前排在30位
错误信息：提交失败，请稍后再试！
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-09-29&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=WCN&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryT?leftTicketDTO.train_date=2019-09-29&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=WCN&purpose_codes=ADULT @返回参数为空, 接口状态码: 302
使用缓存中查找的联系人信息

**Comment by testerSunshine** [comment]
这个只要不是一直出现，就没有问题

**Comment by Liuzhj** [comment]
那要是一直出现是什么原因呢？ 我现在就是一直出现相同的问题。
![image](https://user-images.githubusercontent.com/14147011/65656404-56d12d00-e052-11e9-9c9b-9dda43696f26.png)
