### ISSUE TITLE
FileNotFoundError: [WinError 2] 系统找不到指定的文件

### ISSUE THREAD

**Issue by luozhenghu** [testerSunshine/12306#326]
**描述问题**
```
小白用户，首次使用。Windows+python3.7环境修改完配置后运行python run.py，在提示出现正确的出发站、到达站、乘车日期等信息后，出现如下错误：
**************************************************
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
cookie获取中
Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 20, in <module>
    run()
  File "run.py", line 8, in run
    select_ticket_info.select().main()
  File "D:\Workspace\tests\PythonTest\12306-master\12306-master\init\select_ticket_info.py", line 148, in main
    getDrvicesID(self)
  File "D:\Workspace\tests\PythonTest\12306-master\12306-master\config\getCookie.py", line 19, in getDrvicesID
    driver = webdriver.Chrome(chrome_options=options, executable_path=TickerConfig.CHROME_PATH)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'PythonTestS06-masterS06-master' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
恳请各位大侠帮忙看看，非常感谢！！！
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by syshlang** [comment]
如果COOKIE_TYPE=1，则需配置chromeDriver路径(注意是填你机器本地chromeDriver的路径，这个地方一定要改),下载地址http://chromedriver.storage.googleapis.com/index.html
# chromedriver配置版本只要和chrome的大版本匹配就行

**Comment by luozhenghu** [comment]
> 如果COOKIE_TYPE=1，则需配置chromeDriver路径(注意是填你机器本地chromeDriver的路径，这个地方一定要改),下载地址http://chromedriver.storage.googleapis.com/index.html
> 
> # chromedriver配置版本只要和chrome的大版本匹配就行

谢谢回答。但是在运行之前已经下载了chromedriver_win32.zip并且解压出chromedriver.exe，置于项目同一路径下，并且将该路径加到TickerConfig.py以及环境变量PATH中，始终出现FileNotFoundError，不知何故。
另外，如果将COOKIE_TYPE设为2，可以运行，但验证码校验完毕后登录始终302.
恳请大侠帮忙分析。谢谢！

**Comment by testerSunshine** [comment]
你的ip刷登录接口刷的太厉害了，更换一下ip或者等十分钟左右就能登录了

**Comment by qyjandroid** [comment]
> > 如果COOKIE_TYPE=1，则需配置chromeDriver路径(注意是填你机器本地chromeDriver的路径，这个地方一定要改),下载地址http://chromedriver.storage.googleapis.com/index.html
> > # chromedriver配置版本只要和chrome的大版本匹配就行
> 
> 谢谢回答。但是在运行之前已经下载了chromedriver_win32.zip并且解压出chromedriver.exe，置于项目同一路径下，并且将该路径加到TickerConfig.py以及环境变量PATH中，始终出现FileNotFoundError，不知何故。
> 另外，如果将COOKIE_TYPE设为2，可以运行，但验证码校验完毕后登录始终302.
> 恳请大侠帮忙分析。谢谢！

您好，您的问题解决了吗？我也遇到相同的问题，chromedriver路径设置上了，但是还是一样的报错

**Comment by yangsoqueen** [comment]
我也遇到了同样的问题

**Comment by loma18** [comment]
> > > 如果COOKIE_TYPE=1，则需配置chromeDriver路径(注意是填你机器本地chromeDriver的路径，这个地方一定要改),下载地址http://chromedriver.storage.googleapis.com/index.html
> > > # chromedriver配置版本只要和chrome的大版本匹配就行
> > 
> > 
> > 谢谢回答。但是在运行之前已经下载了chromedriver_win32.zip并且解压出chromedriver.exe，置于项目同一路径下，并且将该路径加到TickerConfig.py以及环境变量PATH中，始终出现FileNotFoundError，不知何故。
> > 另外，如果将COOKIE_TYPE设为2，可以运行，但验证码校验完毕后登录始终302.
> > 恳请大侠帮忙分析。谢谢！
> 
> 您好，您的问题解决了吗？我也遇到相同的问题，chromedriver路径设置上了，但是还是一样的报错
我的配置成这样：CHROME_PATH = "C:\software\chromedriver_win32\chromedriver.exe"，可以了哦
![image](https://user-images.githubusercontent.com/30955346/71503548-96f1b700-28b0-11ea-96db-7d8b80f3da73.png)
