### ISSUE TITLE
unknown error: DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by yulintao** [testerSunshine/12306#327]
**描述问题**
```
获取cookie失败，登陆不成功！
```

**截图&日志**
```
cookie获取中
....
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /opt/google/chrome/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```
**环境信息**
 - ArchLinux
 - python3.7.1
 - 订票小助手版本 1.1.101

**Comment by yulintao** [comment]
options.add_argument("start-maximized");
      options.add_argument("disable-infobars");
      options.add_argument("--disable-extensions");
      options.add_argument("--disable-gpu");
      options.add_argument("--disable-dev-shm-usage");
      options.add_argument("--no-sandbox");
需要添加如上options ， 我的chrome版本是76.0.3809.132   chrome-driver 版本是76.0.3809.126，系统为ArchLinux

**Comment by bigicy** [comment]
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from config.emailConf import sendEmail
  File "/Users/huangbing/Downloads/12306-master/config/emailConf.py", line 4, in <module>
    import TickerConfig
  File "/Users/huangbing/Downloads/12306-master/TickerConfig.py", line 1
SyntaxError: Non-ASCII character '\xe5' in file /Users/huangbing/Downloads/12306-master/TickerConfig.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by fanjindong** [comment]
@yulintao 

```
        from selenium import webdriver
        options = webdriver.ChromeOptions()
        options.add_argument("start-maximized")
        options.add_argument("disable-infobars")
        options.add_argument("--disable-extensions")
        options.add_argument("--disable-gpu")
        options.add_argument("--disable-dev-shm-usage")
        options.add_argument("--no-sandbox")
        cookies = []
        driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH, options=options)
```
没啥用啊，还是报错

**Comment by yzfly** [comment]
> @yulintao
> 
> ```
>         from selenium import webdriver
>         options = webdriver.ChromeOptions()
>         options.add_argument("start-maximized")
>         options.add_argument("disable-infobars")
>         options.add_argument("--disable-extensions")
>         options.add_argument("--disable-gpu")
>         options.add_argument("--disable-dev-shm-usage")
>         options.add_argument("--no-sandbox")
>         cookies = []
>         driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH, options=options)
> ```
> 
> 没啥用啊，还是报错。
> 
> 我使用的版本是：
> Google Chrome 77.0.3865.75
> ChromeDriver 77.0.3865.40

同样的问题

**Comment by yzfly** [comment]
> @yulintao
> 
> ```
>         from selenium import webdriver
>         options = webdriver.ChromeOptions()
>         options.add_argument("start-maximized")
>         options.add_argument("disable-infobars")
>         options.add_argument("--disable-extensions")
>         options.add_argument("--disable-gpu")
>         options.add_argument("--disable-dev-shm-usage")
>         options.add_argument("--no-sandbox")
>         cookies = []
>         driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH, options=options)
> ```
> 
> 没啥用啊，还是报错。
> 
> 我使用的版本是：
> Google Chrome 77.0.3865.75
> ChromeDriver 77.0.3865.40

        from selenium import webdriver
        options = webdriver.ChromeOptions()
        options.add_argument("start-maximized");
        options.add_argument("disable-infobars");
        options.add_argument("--disable-extensions");
        options.add_argument("--disable-gpu");
        options.add_argument("--disable-dev-shm-usage");
        options.add_argument("--no-sandbox");
        options.add_argument("--headless");
        cookies = []
        driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH, options=options)

添加上面的代码后成功，增加了 --headless 参数
