### ISSUE TITLE
验证码下载失败

### ISSUE THREAD

**Issue by JustJia** [testerSunshine/12306#333]
python run.py 日志出现以下：
![截图](https://user-images.githubusercontent.com/33364496/64524828-00fe4480-d332-11e9-9773-0a7fd87d9d4c.JPG)
然后接下来验证环节出现以下：
![截图](https://user-images.githubusercontent.com/33364496/64524544-50904080-d331-11e9-8abb-34aef9b1b818.PNG)

**Comment by testerSunshine** [comment]
等会再试，你可以试试官网能出来不
