### ISSUE TITLE
Mac 启动命令报语法错误

### ISSUE THREAD

**Issue by gloryzgh** [testerSunshine/12306#337]
语法错误

Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/ghzhang/12306-master/config/serverchanConf.py", line 22
    sendServerChanUrls["req_url"] += f'{secret}.send'
                                                    ^
SyntaxError: invalid syntax

**环境信息**
 - Mac os
 - python3.7.4
 - 订票小助手版本 1.1.108

**Comment by zheng401207030** [comment]
调用微信通知这一段，可以不用发送微信试下。

**Comment by SSLoong** [comment]
你好，我也遇到了同样的问题，麻烦问一下最后怎么解决的？

**Comment by truth1024** [comment]
同问

**Comment by truth1024** [comment]
SERVER_CHAN_CONF = {
    "is_server_chan": False,
    "secret": ""
}
这个配置应该不会走到那段代码啊？

**Comment by cy920820** [comment]
今天刚拉的代码，发现依然存在这个问题

**Comment by sev7e0** [comment]
> 今天刚拉的代码，发现依然存在这个问题
> mac os 10.14.6
> Python 3.7.4
> 软件版本 = "1.1.111"

```python
# 把这段代码
sendServerChanUrls["req_url"] += f'{secret}.send'

# 试着改成这样
sendServerChanUrls["req_url"] += secret + ".send"
```

**Comment by truth1024** [comment]
> 今天刚拉的代码，发现依然存在这个问题
> mac os 10.14.6
> Python 3.7.4
> 软件版本 = "1.1.111"

你最好先检查一下系统默认的Python版本。我的电脑上有两个Python版本，默认用的是系统自带的2.7的版本，f这个函数是3.6才支持的。
