### ISSUE TITLE
mac 命令报错

### ISSUE THREAD

**Issue by pan-haos** [testerSunshine/12306#339]
**描述问题**
```
mac 下命令启动程序，去除之前的f“”拼接字符串的错误，这里会提示找不到包
```
**截图&日志**
![image](https://user-images.githubusercontent.com/26356338/64587999-b6350900-d3d3-11e9-96ce-ea6ee3e4d131.png)

**环境信息**
 - windows
 - python3.7.4
 - 订票小助手版本 1.1.108

**额外的备注**
- Add any other context about the problem here.

**Comment by chaotianjiao** [comment]
你 pip install wrapcache 试试3

**Comment by Rain-Huang** [comment]
试了ip install wrapcache，安装成功了模块也不行

**Comment by chaotianjiao** [comment]
报的什么错你要发出来或者说出来啊，你就说个不行，当然不行了。

**Comment by vforbox** [comment]
如果 pip 安装过后依然无法导入模块，尝试 `pip3 install wrapcache`或者手动安装，首先下载 https://pypi.org/project/wrapcache/#files ，解压后运行 `python setup.py install`
