### ISSUE TITLE
有票 但是 不能成功提交 长时间等待排队

### ISSUE THREAD

**Issue by boyonehappy** [testerSunshine/12306#34]
正在尝试提交订票...
出票成功
车票提交通过，正在尝试排队
排队成功, 当前余票还剩余: 1503 张
不需要验证码
提交订单成功！
排队等待时间预计还剩 -22450 ms
排队等待时间预计还剩 -22449 ms
排队等待时间预计还剩 -22448 ms
排队等待时间预计还剩 -22447 ms
排队等待时间预计还剩 -22446 ms
排队等待时间预计还剩 -20011 ms
排队等待时间预计还剩 -20010 ms
排队等待时间预计还剩 -20010 ms
排队等待时间预计还剩 -20009 ms
排队等待时间预计还剩 -20008 ms
排队等待时间预计还剩 -20007 ms
排队等待时间预计还剩 -20006 ms
排队等待时间预计还剩 -20006 ms
排队等待时间预计还剩 -20005 ms
排队等待时间预计还剩 -20004 ms
排队等待时间预计还剩 -20004 ms
排队等待时间预计还剩 -20003 ms
排队等待时间预计还剩 -20002 ms
排队等待时间预计还剩 -20001 ms
排队等待时间预计还剩 -16689 ms
排队等待时间预计还剩 -16689 ms
排队等待时间预计还剩 -16688 ms
排队等待时间预计还剩 -16688 ms
排队等待时间预计还剩 -16687 ms
排队等待时间预计还剩 -16687 ms
排队等待时间预计还剩 -16686 ms
排队等待时间预计还剩 -16685 ms
排队等待时间预计还剩 -16685 ms
排队等待时间预计还剩 -16684 ms
超出排队时间，自动放弃，正在重新刷票
接口 {'Host': 'kyfw.12306.cn', 'Referer': 'https://kyfw.12306.cn/otn/confirmPassenger/initDc', 'is_json': True, 're_time': 0.1, 'req_type': 'post', 'req_url': '/otn/confirmPassenger/confirmSingleForQueue', 'is_logger': True, 're_try': 10} 无响应

**Comment by liuxiang94** [comment]
我也遇到了一样的情况，手动购票可以成功，但是自动购票就会一直排队：

车次: T9 始发车站: 北京 终点站: 达州 硬卧:有
正在尝试提交订票...
出票成功
车票提交通过，正在尝试排队
排队成功, 当前余票还剩余: 28 张
不需要验证码
提交订单成功！
排队等待时间预计还剩 -25823 ms
排队等待时间预计还剩 -25822 ms
排队等待时间预计还剩 -25821 ms
排队等待时间预计还剩 -25820 ms
排队等待时间预计还剩 -25820 ms
排队等待时间预计还剩 -25819 ms
排队等待时间预计还剩 -25817 ms
排队等待时间预计还剩 -25817 ms
排队等待时间预计还剩 -25816 ms
排队等待时间预计还剩 -24556 ms
排队等待时间预计还剩 -24555 ms
排队等待时间预计还剩 -24555 ms
排队等待时间预计还剩 -24554 ms
排队等待时间预计还剩 -24554 ms
排队等待时间预计还剩 -24553 ms
排队等待时间预计还剩 -24552 ms
排队等待时间预计还剩 -24551 ms
排队等待时间预计还剩 -24550 ms
排队等待时间预计还剩 -24550 ms
排队等待时间预计还剩 -24549 ms
排队等待时间预计还剩 -24548 ms
排队等待时间预计还剩 -24548 ms
排队等待时间预计还剩 -24547 ms
排队等待时间预计还剩 -24546 ms
排队等待时间预计还剩 -25563 ms
排队等待时间预计还剩 -25562 ms
排队等待时间预计还剩 -25561 ms
排队等待时间预计还剩 -25561 ms
排队等待时间预计还剩 -25559 ms
超出排队时间，自动放弃，正在重新刷票
接口 {'Host': 'kyfw.12306.cn', 'Referer': 'https://kyfw.12306.cn/otn/confirmPassenger/initDc', 'is_json': True, 're_time': 0.1, 'req_type': 'post', 'req_url': '/otn/confirmPassenger/confirmSingleForQueue', 'is_logger': True, 're_try': 10} 无响应

**Comment by tyzChar** [comment]
我这里显示有很多票但是一直排队
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
车次：G840 出发站：深圳 到达站：赤壁 历时：04:24 商务/特等座：16 一等座：有 二等座：有 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：-- 预订
12:58 17:22 04:24
车次: G840 始发车站: 深圳 终点站: 赤壁 二等座: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
提交订单成功
排队成功, 当前余票还剩余: 684 张
验证码提交安全期，等待3.743MS
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -92 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -91 ms
