### ISSUE TITLE
chromedriver报错

### ISSUE THREAD

**Issue by zzhzero** [testerSunshine/12306#341]
**描述问题**
```
纯命令行环境似乎无法使用chromedriver获得cookie？
```
**重现步骤**
```
步骤一
```
**截图&日志**
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.
**环境信息**
 - ubuntu18.04
 - python3.6
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by solaCQ** [comment]
修改 google-chrome  最后一行加上 --headless

exec -a "$0" "$HERE/chrome" "$@" --no-sandbox --headless

**Comment by flykite6** [comment]
需要装你的chrome版本对应的驱动，在配置文件哪里改一下路径

**Comment by zzhzero** [comment]
options.add_argument('--headless')
ChromeDriver 76.0.3809.126
Google Chrome 76.0.3809.132
CHROME_PATH = "/root/chromedriver"
以上修改均无效

尝试exec后远程连接直接断开

**Comment by dy1945** [comment]
下载最新的chromedriver，然后TickerConfig.py里设置一下CHROME_PATH

**Comment by DanielRWong** [comment]
chromedriver   76.0.3809.12
chrome  76.0.3809.132
这个组合是可以的
