### ISSUE TITLE
ModuleNotFoundError: No module named 'wrapcache'

### ISSUE THREAD

**Issue by freesd** [testerSunshine/12306#343]
WIN7 cmd运行，安装依赖库最后一步出现这个提示
Collecting tensorflow (from -r requirements.txt (line 12))
  Could not find a version that satisfies the requirement tensorflow (from -r re
quirements.txt (line 12)) (from versions: )
No matching distribution found for tensorflow (from -r requirements.txt (line 12
))

运行run.py出现错误

D:\Date\Desktop\12306>run.py
Traceback (most recent call last):
  File "D:\Date\Desktop\12306\run.py", line 4, in <module>
    from init import select_ticket_info
  File "D:\Date\Desktop\12306\init\select_ticket_info.py", line 10, in <module>
    import wrapcache
ModuleNotFoundError: No module named 'wrapcache'

**Comment by Rain-Huang** [comment]
同样的问题，，

**Comment by testerSunshine** [comment]
没装好依赖
