### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by dzf123** [testerSunshine/12306#346]
**描述问题**
Traceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/xxxxx/12306-master/config/serverchanConf.py", line 22
    sendServerChanUrls["req_url"] += f'{secret}.send'
                                                    ^
SyntaxError: invalid syntax

```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
dad76820cbeb454de6a8fd9d8c15757aa96b3583

**Comment by xwdz** [comment]
@testerSunshine  配置方面参考的[dad7682](https://github.com/testerSunshine/12306/commit/dad76820cbeb454de6a8fd9d8c15757aa96b3583) 这次commit 不过该问题还是存在

**Comment by dinggenfeng** [comment]
> @testerSunshine 配置方面参考的[dad7682](https://github.com/testerSunshine/12306/commit/dad76820cbeb454de6a8fd9d8c15757aa96b3583) 这次commit 不过该问题还是存在

你好，这个问题你解决了吗，我也是配置之后还是报错

**Comment by viqbgrg** [comment]
我的debian也有这个问题

**Comment by Gincoeng** [comment]
Ubuntu16.04 Python3.6  在运行的时候同样出现这个问题,不要使用sudo python run.py ,                      使用 python run.py 然后就没有这个问题了.能够成功运行.不知道对你们有没有用

**Comment by lz369525125** [comment]
这是问题是因为的python的版本问题，升级到相应版本即可
