### ISSUE TITLE
登陆失败，提示人脸核验

### ISSUE THREAD

**Issue by pacoblack** [testerSunshine/12306#350]
**描述问题**
```
执行一段时间后提示进行人脸核验，然后就退出，可是我已经通过人脸核验了
```
**重现步骤**
```
步骤一
```
**截图&日志**
当前G512车次二等座席别提交的候补订单较多，可更换车次、席别或稍后重试。
用户检查失败：[]，可能未登录，可能session已经失效, 正在重新登录中
需要验证码
下载验证码...
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-15&leftTicketDTO.from_station=DXP&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
下载验证码成功
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-15&leftTicketDTO.from_station=DXP&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:310: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
题目为['薯条']
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-15&leftTicketDTO.from_station=DXP&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-15&leftTicketDTO.from_station=DXP&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:310: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-15&leftTicketDTO.from_station=DXP&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
1 珊瑚
2 薯条
3 辣椒酱
4 海苔
5 档案袋
6 樱桃
7 烛台
8 档案袋
验证码识别坐标为112,77
112,77
使用缓存中查找的联系人信息
验证码通过,开始登录..
通过人证一致性核验的用户及激活的“铁路畅行”会员可以提交候补需求，请您按照操作说明在铁路12306app.上完成人证核验
**环境信息**
 - mac
 - python3.7.4
 - 订票小助手版本 1.1.110

**额外的备注**
- Add any other context about the problem here.

**Comment by swelltt0576** [comment]
ps人脸能验过么？

**Comment by mail6562** [comment]
楼主可以搞一个，生产人脸gif的程序，提交人脸验证

**Comment by mail6562** [comment]
可以搞一个生成人脸gif图片，提交验证

**Comment by cfanbo** [comment]
也遇到同样的问题，明明已经认证过了，过一会提示这个然后退出来

**Comment by testerSunshine** [comment]
登录问题讨论 #320
