### ISSUE TITLE
使用COOKIE_TYPE 模式1,获取cookie错误,也加载了chromedriver

### ISSUE THREAD

**Issue by lolwsyzc** [testerSunshine/12306#354]
**描述问题**
```
使用COOKIE_TYPE 模式1,获取cookie错误,也加载了chromedriver
```
**重现步骤**
```
步骤一
```
**截图&日志**
![image](https://user-images.githubusercontent.com/44010989/64681649-b0622500-d4b2-11e9-822c-a7421ea92c0c.png)

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
selenium没配置好，这个错误贴百度一分钟解决
