### ISSUE TITLE
登陆时提示账号非法

### ISSUE THREAD

**Issue by xiangjiezhao** [testerSunshine/12306#355]
**描述问题**
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by codeRemoverA** [comment]
我的也是,被封了吗,封多久

**Comment by testerSunshine** [comment]
登录的issues统一在# 320
