### ISSUE TITLE
agency下的cdn_utils.py文件reload方法，未import相应的包

### ISSUE THREAD

**Issue by zheng401207030** [testerSunshine/12306#356]
**描述问题**
```
agency下的cdn_utils.py文件中reload（）方法未import相应的包，导致此文件报错。
```
**重现步骤**
```
步骤一
```
**截图&日志**
`# encoding=utf8
import collections
import json
import os
import re
import sys
import csv
import requests
from config import urlConf

try:
    reload(sys)
    sys.setdefaultencoding('utf-8')
except NameError:
    pass`
**环境信息**
 - mac
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by zheng401207030** [comment]
请作者看下这个文件用到没有，是否需要修改。

**Comment by testerSunshine** [comment]
暂时没用到，到时候清理一下
