### ISSUE TITLE
windows运行，一直循环提示：url: /passport/web/login返回参数为空, 接口状态码: 302，无法登陆

### ISSUE THREAD

**Issue by grrrrr112** [testerSunshine/12306#357]
需要验证码
I0912 08:56:16.848056 10040 logger.py:61] 出参：{"validateMessagesShowId":"_validatorMessage","status":true,"httpstatus":200,"data":{"isstudentDate":false,"is_login_passCode":"Y","is_sweep_login":"Y","psr_qr_code_result":"N","login_url":"resources/login.html","studentDate":["2019-06-01","2019-09-30","2019-12-01","2019-12-31","2019-01-01","2019-03-31"],"stu_control":30,"is_uam_login":"Y","is_login":"N","other_control":30},"messages":[],"validateMessages":{}}
I0912 08:56:16.962735 10040 logger.py:61] url: /passport/web/auth/uamtk-static
入参: {'appid': 'otn'}
请求方式: post

下载验证码...
I0912 08:56:17.120314 10040 logger.py:61] 出参：{"result_message":"用户未登录","result_code":1}
I0912 08:56:17.120314 10040 logger.py:61] url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.09120864692279584&callback=jQuery19108016482864806321_1554298927290&_=1554298927293
入参: None
请求方式: get

I0912 08:56:17.564159 10040 logger.py:61] 出参：/**/jQuery19108016482864806321_1554298927290({"image":"......","result_message":"生成验证码成功","result_code":"0"});
下载验证码成功
F:\Python\python3\venv\lib\site-packages\keras\engine\saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
题目为['剪纸']
1 开瓶器
2 剪纸
3 口哨
4 剪纸
5 锅铲
6 话梅
7 开瓶器
8 蜡烛
验证码识别坐标为112,77,256,77
112,77,256,77
I0912 08:56:18.870695 10040 logger.py:61] url: /passport/web/auth/uamtk-static
入参: {'appid': 'otn'}
请求方式: post

I0912 08:56:19.213824 10040 logger.py:61] 出参：{"result_message":"用户未登录","result_code":1}
I0912 08:56:19.214795 10040 logger.py:61] url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1568249779214
入参: None
请求方式: get

I0912 08:56:19.384342 10040 logger.py:61] 出参：/**/jQuery19108016482864806321_1554298927290({"result_message":"验证码校验成功","result_code":"4"});
I0912 08:56:19.384342 10040 logger.py:61] url: /passport/web/login
入参: OrderedDict([('username', ('*',)), ('password', ('*',)), ('appid', ('otn',)), ('answer', ('112,77,256,77',))])
请求方式: post

验证码通过,开始登录..
I0912 08:56:20.137893 10040 logger.py:61] url: /passport/web/login 返回参数为空
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
I0912 08:56:20.829051 10040 logger.py:61] url: /passport/web/login 返回参数为空
I0912 08:56:20.829051 10040 logger.py:61] url: /otn/login/conf
入参: {}
请求方式: get

环境win10 64
python版本3.6.5
软件版本：RE_VERSION = "1.1.108"
其他设置：COOKIE_TYPE = 1

**Comment by zqfound** [comment]
无法登陆的话,在手机上退出12306登录,重新输密码,人证核验,然后run
一直302可以更换user_agent,应该是user_agent被限制了,更换成功后就OK了

**Comment by grrrrr112** [comment]
> 无法登陆的话,在手机上退出12306登录,重新输密码,人证核验,然后run
> 一直302可以更换user_agent,应该是user_agent被限制了,更换成功后就OK了

谢谢大佬，在config里没有user_agent设置啊，请问下在哪里设置，谢谢

**Comment by zqfound** [comment]
getCookie.py建议写个user_agent集合,换着用,同一个user_agent刷票次数多了之后也会被限制

**Comment by grrrrr112** [comment]
> getCookie.py建议写个user_agent集合,换着用,同一个user_agent刷票次数多了之后也会被限制

感谢大佬，更换user_agent后，可以登陆了。谢谢

**Comment by dzf19927** [comment]
> > getCookie.py建议写个user_agent集合,换着用,同一个user_agent刷票次数多了之后也会被限制
> 
> 感谢大佬，更换user_agent后，可以登陆了。谢谢



> > getCookie.py建议写个user_agent集合,换着用,同一个user_agent刷票次数多了之后也会被限制
> 
> 感谢大佬，更换user_agent后，可以登陆了。谢谢

请问user_agent 值如何获取？换成什么值？有点不太清楚

**Comment by zqfound** [comment]
最新版代码已经加上登录自动更新user_agent功能
![image](https://user-images.githubusercontent.com/55169469/65225582-fa24be00-daf7-11e9-86ae-f90213703ea7.png)
![image](https://user-images.githubusercontent.com/55169469/65225743-38ba7880-daf8-11e9-8a30-c84067c00981.png)

**Comment by Deniffer** [comment]
> 最新版代码已经加上登录自动更新user_agent功能
> ![image](https://user-images.githubusercontent.com/55169469/65225582-fa24be00-daf7-11e9-86ae-f90213703ea7.png)
> ![image](https://user-images.githubusercontent.com/55169469/65225743-38ba7880-daf8-11e9-8a30-c84067c00981.png)
你好怎么修改这个py文件  ？
