### ISSUE TITLE
一定要指定车次才能抢票的么？

### ISSUE THREAD

**Issue by yjhjerry** [testerSunshine/12306#361]
我发现如果不指定车次，然后虽然从一个地方到另一个地方有很多车次可以到达，后面都会说下单无票。但是只要指定一个车次后面就可以顺利下单。

不知道是我设置的问题，还是本身车次必须指定，但是如果是后者，我决得这个就有点麻烦，要抢票还得提前去查询车次，然后填入配置文件...

大佬们能解答一下么？多谢。

**Comment by testerSunshine** [comment]
修改了，不填车次则不判断车次
