### ISSUE TITLE
运行时,出现tensorflow 类型出错

### ISSUE THREAD

**Issue by Joker-smile** [testerSunshine/12306#363]
**描述问题**
```
问题如下图
```
**重现步骤**
```
按照教程装完requirements.txt 要求的依赖
```
**截图&日志**
![2019-09-12 17-04-57屏幕截图](https://user-images.githubusercontent.com/24251648/64770386-ad813600-d57f-11e9-8eb6-39eb6f498555.png)
![2019-09-12 17-05-16屏幕截图](https://user-images.githubusercontent.com/24251648/64770399-b245ea00-d57f-11e9-9aca-c70d832e33c6.png)

**环境信息**
 - Ubuntu18.0.4
 - python3.7.3
 - 订票小助手版本 1.1.112

**额外的备注**

**Comment by EternalSunLhx** [comment]
我的也是这个问题，macos

**Comment by testerSunshine** [comment]
路径改成你自己的ChromeDriver路径
