### ISSUE TITLE
登录失败: 账号非法

### ISSUE THREAD

**Issue by hzh1105** [testerSunshine/12306#364]
**描述问题**
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```
**截图&日志**
![1](https://user-images.githubusercontent.com/30227363/64770609-1668ae00-d580-11e9-9460-cf7ee9e358a2.png)
![) R}1{JLAU@1WG$WIWOE~FH](https://user-images.githubusercontent.com/30227363/64770667-37c99a00-d580-11e9-9127-b6827094081e.jpg)

**环境信息**
 -ubuntu18.10
 - python3.6
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
# 302
