### ISSUE TITLE
概率性出现  url: /otn/login/checkUser返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by wascu** [testerSunshine/12306#366]
**描述问题**
```
登录成功后，在刷票的过程中，概率性出现  url: /otn/login/checkUser返回参数为空, 接口状态码: 302
```
**重现步骤**
```
python run.py直接登录成功后出现
```
**截图&日志**

url: /otn/login/checkUser返回参数为空, 接口状态码: 302
url: /otn/login/checkUser返回参数为空, 接口状态码: 302
正在第220次查询 随机停留时长：2.8 乘车日期: 2019-09-30 车次：K1457  下单无票 无候补机会 耗时：264.035ms
url: /otn/login/checkUser返回参数为空, 接口状态码: 302
url: /otn/login/checkUser返回参数为空, 接口状态码: 302

**环境信息**
 - ubuntu
 - python3.6.8
 - 订票小助手版本 1.1.112

**额外的备注**
- Add any other context about the problem here.

**Comment by syshlang** [comment]
重启之后就好了，但是过一会又会出现，有什么解决办法

**Comment by testerSunshine** [comment]
拉下新代码，修改了checkUser的心跳时长
