### ISSUE TITLE
获取Cookie 失败 selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127

### ISSUE THREAD

**Issue by alonexy** [testerSunshine/12306#368]
**描述问题**
```
Docker运行
```
**重现步骤**

```
sudo ./docker.sh run
```
**截图&日志**
12306ticket | cookie获取中
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 20, in <module>
12306ticket |     run()
12306ticket |   File "run.py", line 8, in run
12306ticket |     select_ticket_info.select().main()
12306ticket |   File "/usr/src/app/init/select_ticket_info.py", line 150, in main
12306ticket |     getDrvicesID(self)
12306ticket |   File "/usr/src/app/config/getCookie.py", line 20, in getDrvicesID
12306ticket |     driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH,chrome_options=chrome_options)
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
12306ticket |     self.service.start()
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 98, in start
12306ticket |     self.assert_process_still_running()
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
12306ticket |     % (self.path, return_code)
12306ticket | selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 127
**环境信息**
 - mac
 - python3.7.4
# 软件版本
RE_VERSION = "1.1.112"

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
chromedriver的path
