### ISSUE TITLE
有个疑问很想请教一下, 这样的py爬虫工具不会被请喝茶吗？

### ISSUE THREAD

**Issue by qmppz** [testerSunshine/12306#369]
很想请教一下, 这样的py爬虫工具不会被请喝茶吗？
毕竟这是在“搞坏事”😂，不知道作者有没有收到12306官方的回应

如果有人用来盈利的话，是不是就算违法行为了

**Comment by MissLIBRA97** [comment]
技术无罪，盈利的不是作者，智行、飞猪什么的不得先喝为敬？
