### ISSUE TITLE
12306 “慢速排队” 拦截

### ISSUE THREAD

**Issue by Neotoxin4365** [testerSunshine/12306#37]
http://www.techweb.com.cn/internet/2018-02-01/2635181.shtml

提交订单后，请求被判定为可疑，进入长时间的“慢速排队”状态。

试用了多个请求脚本，均被该“排队”拦截。作者找到破解的方法了吗？

**Comment by testerSunshine** [comment]
已解决

**Comment by sjfkai** [comment]
可以说一下解决原理吗？ 谢谢

**Comment by sjfkai** [comment]
只是参数吗？包括`cookies`吗？
