### ISSUE TITLE
UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.

### ISSUE THREAD

**Issue by piratf** [testerSunshine/12306#376]
**描述问题**
```
Python 3.6.8 根据 requirements.txt 安装了所有依赖

模型文件 12306.image.model.h5 和 model.v2.0.h5 已经放在项目根目录。

解析验证码过程中不断出现提示
/usr/local/lib64/python3.6/site-packages/keras/engine/saving.py:310: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

```
**重现步骤**
```
直接执行
```
**截图&日志**

![image](https://user-images.githubusercontent.com/9389616/64901841-50e16080-d6d0-11e9-9f9c-94d9b7ad2b5c.png)

**环境信息**
 - Linux iZbp13cr888gyf2a2wfk3nZ 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 - Python 3.6.8
 - 订票小助手版本 1.1.101

**额外的备注**
- 今天(14 号)发现有 “Corrupt JPEG data: 13 extraneous bytes before marker 0xd9” 这样的报错

**Comment by testerSunshine** [comment]
```
今天(14 号)发现有 “Corrupt JPEG data: 13 extraneous bytes before marker 0xd9” 这样的报错
这个是不用管
```
另外的应该是你的模型有问题，没下载好，或者没权限
