### ISSUE TITLE
非节假日（票数充足）测试脚本下单，无法正常下单

### ISSUE THREAD

**Issue by Rain-Huang** [testerSunshine/12306#381]
**描述问题**
一开始抢国庆票发现一直抢不到，就想试试非节假日有票的日子试试脚本能不能抢得到，结果发现一直查询为空，实际上2019-09-25的票数很充足，班次也对的上，我用手机秒下单，脚本就会出现下面的状态，一直显示无票。
```
**重现步骤**
```
步骤一
```

**截图&日志**
车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-25&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=MDQ&purpose_codes=ADULT, 可以手动查询是否有票
正在第50次查询 随机停留时长：1.78 乘车日期: 2019-09-25 车次：D7493.D7191.D7459.D7461.D7465.D7467.D7557.D7499.D7469.D7187.D7471.D7473.D7475.D7477.D7491.D7495.D7193  下单无票 无候补机会 耗时：224.405ms

**环境信息**
 - windows
 - python3.6.5
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
接口没有返回数据，建议换个ip再试

**Comment by Rain-Huang** [comment]
换了个地方，换了个公网IP的了，去查询该天的，依旧不行。有何解决办法吗
车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-25&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=MDQ&purpose_codes=ADULT, 可以手动查询是否有票
正在第15次查询 随机停留时长：1.55 乘车日期: 2019-09-25 车次：D7493.D7191.D7459.D7461.D7465.D7467.D7557.D7499.D7469.D7187.D7471.D7473.D7475.D7477.D7491.D7495.D7193  下单无票 无候补机会 耗时：204.256ms

**Comment by EverydayLearning** [comment]
> 换了个地方，换了个公网IP的了，去查询该天的，依旧不行。有何解决办法吗
> 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-09-25&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=MDQ&purpose_codes=ADULT, 可以手动查询是否有票
> 正在第15次查询 随机停留时长：1.55 乘车日期: 2019-09-25 车次：D7493.D7191.D7459.D7461.D7465.D7467.D7557.D7499.D7469.D7187.D7471.D7473.D7475.D7477.D7491.D7495.D7193 下单无票 无候补机会 耗时：204.256ms

解决了吗 同样的问题

**Comment by vmoeak** [comment]
同样的问题有解决方法吗

**Comment by sharlley** [comment]
同样的问题有解决方法吗

**Comment by tracyfun** [comment]
出现这种问题基本可以确定是填写的车次，日期，出发城市和到达城市和代码里的匹配规则对应不上的原因，除了要着重检查日期格式外，出发城市和到达城市必须精确，比如我本地测试北京和北京西就是两种结果
