### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by kinnoary** [testerSunshine/12306#382]
**描述问题**
```
clone error
```
**重现步骤**
```
步骤一
```
**截图&日志**
C:\windows\system32>git clone https://github.com/kinnoary/12306.git
Cloning into '12306'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (22/22), done.
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
ffatal: the remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed

**环境信息**
 - windows
 - python3.7

各位大神请帮助看下 是什么问题?

**Comment by testerSunshine** [comment]
文件太大，建议download
