### ISSUE TITLE
docker容器运行失败

### ISSUE THREAD

**Issue by duzefu** [testerSunshine/12306#383]
修改了了dockerfile里面的Python版本-> 3.7.4容器能够创建成功。但是运行的时候会报chromedrive错误。
12306ticket | selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. 

但是又不知道怎么把chrome drive塞进去，因为即使后台运行很快容器也会自动挂掉。来不及塞进去

root@ubuntu:/home/minmie/12306# ./docker.sh  run
Starting 12306ticket ... 
Starting 12306ticket ... done
Attaching to 12306ticket
12306ticket | **************************************************
12306ticket | 检查当前版本为: 1.1.113
12306ticket | 检查当前python版本为：3.7.4，目前版本只支持3.6以上
12306ticket | 12306刷票小助手，最后更新于2019.09.15，请勿作为商业用途，交流群号： 1群：286271084(已满)
12306ticket |  2群：649992274(已满)
12306ticket |  3群：632501142(已满)
12306ticket |  4群: 606340519(已满)
12306ticket |  5群: 948526733(已满)
12306ticket |  6群: 608792930(未满)
12306ticket |  7群: 660689659(已满)
12306ticket |  8群: 620629239(未满)
12306ticket | 
12306ticket | 当前配置：
12306ticket | 出发站：深圳
12306ticket | 到达站：厦门
12306ticket | 乘车日期：2019-10-01,2019-09-30
12306ticket | 坐席：一等座,二等座
12306ticket | 是否有票优先提交：True
12306ticket | 乘车人：['林则徐']
12306ticket | 刷新间隔: 随机(1-3S)
12306ticket | 僵尸票关小黑屋时长: 5
12306ticket | 下单接口: 2
12306ticket | 下单模式: 2
12306ticket | 预售踩点时间:13:00:00
12306ticket | **************************************************
12306ticket | cookie获取中
12306ticket | Using TensorFlow backend.
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   np_resource = np.dtype([("resource", np.ubyte, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
12306ticket | /usr/local/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
12306ticket |   np_resource = np.dtype([("resource", np.ubyte, 1)])
12306ticket | Traceback (most recent call last):
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
12306ticket |     stdin=PIPE)
12306ticket |   File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
12306ticket |     restore_signals, start_new_session)
12306ticket |   File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
12306ticket |     raise child_exception_type(errno_num, err_msg, err_filename)
12306ticket | FileNotFoundError: [Errno 2] No such file or directory: '/home/minmie/chromedriver': '/home/minmie/chromedriver'
12306ticket | 
12306ticket | During handling of the above exception, another exception occurred:
12306ticket | 
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 20, in <module>
12306ticket |     run()
12306ticket |   File "run.py", line 8, in run
12306ticket |     select_ticket_info.select().main()
12306ticket |   File "/usr/src/app/init/select_ticket_info.py", line 151, in main
12306ticket |     getDrvicesID(self)
12306ticket |   File "/usr/src/app/config/getCookie.py", line 17, in getDrvicesID
12306ticket |     driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
12306ticket |     self.service.start()
12306ticket |   File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 83, in start
12306ticket |     os.path.basename(self.path), self.start_error_message)
12306ticket | selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
12306ticket | 
12306ticket exited with code 1

**Comment by duzefu** [comment]
COOKIE_TYPE = 1 -> 0
了之后倒是也可以运行。。。但是会卡在登录上面，反复登录不上去
12306ticket | url: /passport/web/login返回参数为空, 接口状态码: 302

**Comment by duzefu** [comment]
过了半小时登上去了。。。好像能用了
anyway , 想知道一下COOKIE_TYPE = 1报错的这个要怎么解决

**Comment by kongminhao** [comment]
> 过了半小时登上去了。。。好像能用了
> anyway , 想知道一下COOKIE_TYPE = 1报错的这个要怎么解决

Docker里面可以使用远程selenium解决，需要改动少许代码。
参见这个项目
https://github.com/SeleniumHQ/docker-selenium

或者可以在Docker里装一个chrome。

**Comment by huos3203** [comment]
python 3.7.0
`sudo sh docker.sh run`

error:
```
Starting 12306ticket ... done
Attaching to 12306ticket
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 3, in <module>
12306ticket |     from config.serverchanConf import sendServerChan
12306ticket |   File "/usr/src/app/config/serverchanConf.py", line 22
12306ticket |     sendServerChanUrls["req_url"] += f'{secret}.send'
12306ticket |                                                     ^
12306ticket | SyntaxError: invalid syntax
12306ticket exited with code 1
```

**Comment by wmm0165** [comment]
> 过了半小时登上去了。。。好像能用了
> anyway , 想知道一下COOKIE_TYPE = 1报错的这个要怎么解决

你现在解决了吗？遇到了同样问题
