### ISSUE TITLE
通过人证一致性核验的用户及激活的“铁路畅行”会员可以提交候补需求，请您按照操作说明在铁路12306app.上完成人证核验

### ISSUE THREAD

**Issue by Yubiao-Li** [testerSunshine/12306#389]
**描述问题**
```
程序运行自动停止，并提示 通过人证一致性核验的用户及激活的“铁路畅行”会员可以提交候补需求，请您按照操作说明在铁路12306app.上完成人证核验，但本人已在12306app人证核验过
```

**截图&日志**
![Screenshot_2019-09-17-12-49-31-400_com MobileTick](https://user-images.githubusercontent.com/39786286/65012392-c015b980-d949-11e9-848c-348a992819e8.png)
url: /otn/afterNate/getSuccessRate返回参数为空, 接口状态码: 302
12306接口无响应，正在重试 can only join an iterable
广州-韶关东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-01&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=SGQ&purpose_codes=ADULT, 可以手动查询是否有票
广州-韶关东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-02&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=SGQ&purpose_codes=ADULT, 可以手动查询是否有票
正在第541次查询 随机停留时长：4.22 乘车日期: 2019-10-01,2019-10-02 车次：K356.K770.K1348.K326.K1172.K776.Z230.K9064.K486.K936.K192.K1008.K814.T170.K600.K932.K688  下单无票 无候补机会 耗时：49.187ms
广州-韶关东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-01&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=SGQ&purpose_codes=ADULT, 可以手动查询是否有票
使用缓存中查找的联系人信息
通过人证一致性核验的用户及激活的“铁路畅行”会员可以提交候补需求，请您按照操作说明在铁路12306app.上完成人证核验
**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**Comment by fjfhlqjtg** [comment]
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
Corrupt JPEG data: 16 extraneous bytes before marker 0xd9
出现同样问题

**Comment by Getthrough** [comment]
确定是人证核验嘛，不是手机核验奥。我一核验成功就能登录了

**Comment by xiaonana-123** [comment]
添加了两个乘客，都人证核验通过了，还是提示这个

**Comment by baibaibai455** [comment]
我的也是，人证核验过了，但是刷一会儿以后程序就会退出，提示这个

**Comment by whitelok** [comment]
肯定是windows用户才出现的问题 亲测MAC没问题 
duplicate https://github.com/testerSunshine/12306/issues/393#issuecomment-532545840

**Comment by baibaibai455** [comment]
> 肯定是windows用户才出现的问题 亲测MAC没问题
> duplicate [#393 (comment)](https://github.com/testerSunshine/12306/issues/393#issuecomment-532545840)

![image](https://user-images.githubusercontent.com/47173675/65122924-b57c2280-da24-11e9-8a0f-9722e895ecd6.png)
![WechatIMG328](https://user-images.githubusercontent.com/47173675/65122971-d2185a80-da24-11e9-8439-67906763ee7b.jpeg)
![image](https://user-images.githubusercontent.com/47173675/65123007-e78d8480-da24-11e9-923c-76f8197b2975.png)
![image](https://user-images.githubusercontent.com/47173675/65123050-02f88f80-da25-11e9-9c92-7351daa42ecc.png)

**Comment by baibaibai455** [comment]
> 肯定是windows用户才出现的问题 亲测MAC没问题
> duplicate [#393 (comment)](https://github.com/testerSunshine/12306/issues/393#issuecomment-532545840)

![image](https://user-images.githubusercontent.com/47173675/65123122-2b808980-da25-11e9-81fb-8487676a6c90.png)
![image](https://user-images.githubusercontent.com/47173675/65123150-3c30ff80-da25-11e9-8807-ab1b61a13298.png)
![WechatIMG328](https://user-images.githubusercontent.com/47173675/65123156-3e935980-da25-11e9-9aeb-4b7e52475418.jpeg)
检查当前版本为: 1.1.113
检查当前python版本为：3.7.3，目前版本只支持3.6以上
macbook pro
大概刷200  -  300 次左右就会出现上述截图问题

**Comment by wo6685662** [comment]
ubuntu也有这个问题有时候60次有时候200多次程序挂掉

**Comment by testerSunshine** [comment]
1.1.115版本不会出现这个问题
