### ISSUE TITLE
无论怎么换IP，都提示 12306接口无响应，正在重试 expected string or buffer

### ISSUE THREAD

**Issue by zjcnew** [testerSunshine/12306#39]
IP被封了吗，换了几个地方都查不了票。

![qq 20180324225550](https://user-images.githubusercontent.com/22335594/37865434-596fbcb8-2fb7-11e8-9fe3-bdb4bf3908bd.jpg)

**Comment by testerSunshine** [comment]
用最新代码，此问题是查询接口变更导致

**Comment by zjcnew** [comment]
最新版一直卡到这里，无日志输出。

![qq 20180328135645](https://user-images.githubusercontent.com/22335594/38011399-e0376892-328f-11e8-8b43-bcd6e3f8e854.png)
