### ISSUE TITLE
验证码校验失败怎么处理？

### ISSUE THREAD

**Issue by phperfan** [testerSunshine/12306#390]
**描述问题**
```
获取cookie: [{'RAIL_EXPIRATION': '1569023830089'}, {'RAIL_DEVICEID': 'cayBTUh9caGqdhBmZxGSEktBqH3u7zOblYX8YDBVyi6wYjtX-RqNc0Wwvg4CLkuoB_qxFc31B27HQOHxXPVXjLODCAXyxgVA8vqJWMYWUVLDxpG0LZ6_kFfftEAjYsNgMWKafoPmJlHkztzMd1DGpLXWdGRdtOFa'}]

cookie获取完成
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 16 extraneous bytes before marker 0xd9
softmax() got an unexpected keyword argument 'axis'
None
验证码校验失败
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 15 extraneous bytes before marker 0xd9
softmax() got an unexpected keyword argument 'axis'
None
```

**截图&日志**
![图片](https://user-images.githubusercontent.com/24542253/65028397-928f3700-d96e-11e9-89fe-cb4197cce18f.png)

**环境信息**
 - windows 10 
 - Python 3.6.9 :: Anaconda, Inc.
 - 订票小助手版本 1.1.113
 - tensorflow             1.3.0

**Comment by whitelok** [comment]
window 下jpeg的库好像有问题 jpeg库的version是啥

**Comment by AlienMarkWong** [comment]
**python第三方库的版本不对，我两台电脑其中一台安装完没问题，另一台安装完之后出现了你这个类似问题，对比安装的依赖库版本，完全跟这个对应之后问题解决，可以一试，其中python==3.7.0**
```python
absl-py              0.8.0
astor                0.8.0
beautifulsoup4       4.5.3
bs4                  0.0.1
certifi              2019.6.16
chardet              3.0.4
cycler               0.10.0
fake-useragent       0.1.11
gast                 0.3.2
google-pasta         0.1.7
grpcio               1.23.0
h5py                 2.10.0
idna                 2.6
joblib               0.13.2
Keras                2.2.5
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.1
ntplib               0.3.3
numpy                1.17.2
opencv-python        4.1.1.26
Pillow               6.1.0
pip                  19.2.3
protobuf             3.9.1
pyparsing            2.4.2
python-dateutil      2.8.0
PyYAML               5.1.1
requests             2.18.4
scikit-learn         0.21.3
scipy                1.3.1
selenium             3.11.0
setuptools           41.2.0
six                  1.10.0
sklearn              0.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
urllib3              1.22
Werkzeug             0.15.6
wheel                0.33.6
wincertstore         0.2
wrapcache            1.0.8
wrapt                1.11.2
```

**Comment by lvztpy** [comment]
jpeg库是指pillow吗

**Comment by GloryXu** [comment]
解决了没？

**Comment by GloryXu** [comment]
> ```python
> wrapcache            
> ```

厉害，照着版本修改了下，成功解决，感谢~

**Comment by smallLabel** [comment]
我的问题类似，但是报错信息不一样，忘了复制了。更新了 `wrapcache `  `selenium`  `pyparsing`  `setuptools`之后问题解决

**Comment by ishen7** [comment]
> **python第三方库的版本不对，我两台电脑其中一台安装完没问题，另一台安装完之后出现了你这个类似问题，对比安装的依赖库版本，完全跟这个对应之后问题解决，可以一试，其中python==3.7.0**
> 
> ```python
> absl-py              0.8.0
> astor                0.8.0
> beautifulsoup4       4.5.3
> bs4                  0.0.1
> certifi              2019.6.16
> chardet              3.0.4
> cycler               0.10.0
> fake-useragent       0.1.11
> gast                 0.3.2
> google-pasta         0.1.7
> grpcio               1.23.0
> h5py                 2.10.0
> idna                 2.6
> joblib               0.13.2
> Keras                2.2.5
> Keras-Applications   1.0.8
> Keras-Preprocessing  1.1.0
> kiwisolver           1.1.0
> Markdown             3.1.1
> matplotlib           3.1.1
> ntplib               0.3.3
> numpy                1.17.2
> opencv-python        4.1.1.26
> Pillow               6.1.0
> pip                  19.2.3
> protobuf             3.9.1
> pyparsing            2.4.2
> python-dateutil      2.8.0
> PyYAML               5.1.1
> requests             2.18.4
> scikit-learn         0.21.3
> scipy                1.3.1
> selenium             3.11.0
> setuptools           41.2.0
> six                  1.10.0
> sklearn              0.0
> tensorboard          1.14.0
> tensorflow           1.14.0
> tensorflow-estimator 1.14.0
> termcolor            1.1.0
> urllib3              1.22
> Werkzeug             0.15.6
> wheel                0.33.6
> wincertstore         0.2
> wrapcache            1.0.8
> wrapt                1.11.2
> ```

按照这个安装，提示`wrapt`没有`1.11.2`版本，最高版本是`1.11.1`

**Comment by AlienMarkWong** [comment]
pypi官网：https://pypi.org/ 搜索该软件包可以找到wrapt1.11.2，如下图
请确认你的pip是最新版本


alienmarkwong@163.com
 
发件人： ishen7
发送时间： 2019-09-25 16:35
收件人： testerSunshine/12306
抄送： Alien M. Wong; Comment
主题： Re: [testerSunshine/12306] 验证码校验失败怎么处理？ (#390)
python第三方库的版本不对，我两台电脑其中一台安装完没问题，另一台安装完之后出现了你这个类似问题，对比安装的依赖库版本，完全跟这个对应之后问题解决，可以一试，其中python==3.7.0
absl-py              0.8.0
astor                0.8.0
beautifulsoup4       4.5.3
bs4                  0.0.1
certifi              2019.6.16
chardet              3.0.4
cycler               0.10.0
fake-useragent       0.1.11
gast                 0.3.2
google-pasta         0.1.7
grpcio               1.23.0
h5py                 2.10.0
idna                 2.6
joblib               0.13.2
Keras                2.2.5
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.0
kiwisolver           1.1.0
Markdown             3.1.1
matplotlib           3.1.1
ntplib               0.3.3
numpy                1.17.2
opencv-python        4.1.1.26
Pillow               6.1.0
pip                  19.2.3
protobuf             3.9.1
pyparsing            2.4.2
python-dateutil      2.8.0
PyYAML               5.1.1
requests             2.18.4
scikit-learn         0.21.3
scipy                1.3.1
selenium             3.11.0
setuptools           41.2.0
six                  1.10.0
sklearn              0.0
tensorboard          1.14.0
tensorflow           1.14.0
tensorflow-estimator 1.14.0
termcolor            1.1.0
urllib3              1.22
Werkzeug             0.15.6
wheel                0.33.6
wincertstore         0.2
wrapcache            1.0.8
wrapt                1.11.2
按照这个安装，提示wrapt没有1.11.2版本，最高版本是1.11.1
