### ISSUE TITLE
/otn/leftTicket/queryA 。302

### ISSUE THREAD

**Issue by asimovsperhub** [testerSunshine/12306#391]
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-1&leftTicketDTO.from_station=SZQ&leftTicketDTO.to_station=XAY&purpose_codes=ADULT返回参数为空, 接口状态码: 302

**Comment by asimovsperhub** [comment]
这个查询url给重定向到err页面了

**Comment by asimovsperhub** [comment]
这个查询接口改了吗？？？

**Comment by kongminhao** [comment]
时间改成2019-10-01

**Comment by asimovsperhub** [comment]
> 时间改成2019-10-01

可以的  没注意到

**Comment by jinliyuelong** [comment]
我的是 url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-05&leftTicketDTO.from_station=JIY&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302 也是302

**Comment by Liuzhj** [comment]
相同的问题，刷几十次后就会一直出现。

**Comment by Liuzhj** [comment]
相同的问题。

**Comment by echooooHsu** [comment]
> 相同的问题，刷几十次后就会一直出现。
解决了吗

**Comment by echooooHsu** [comment]
> 我的是 url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-10-05&leftTicketDTO.from_station=JIY&leftTicketDTO.to_station=BJP&purpose_codes=ADULT返回参数为空, 接口状态码: 302 也是302

解决了吗

**Comment by Thankall** [comment]
一样，，感觉是12306会对频率之类的做控制。。

**Comment by caiycx107820** [comment]
这个问题解决了吗，出现同样的问题
