### ISSUE TITLE
win10报WinError87 参数错误，运行失败

### ISSUE THREAD

**Issue by ultimateHandsomeBoy666** [testerSunshine/12306#394]
![image](https://user-images.githubusercontent.com/16084640/65104521-40005a00-da04-11e9-90a0-11e58fda902a.png)

**Comment by lvztpy** [comment]
我也遇到跟你一样的问题，请问你的解决了吗

**Comment by ultimateHandsomeBoy666** [comment]
我傻了，没有配置chomedriver路径。
![image](https://user-images.githubusercontent.com/16084640/65113087-6c23d700-da14-11e9-95e8-5b1f10743b02.png)
配置好了就成功了
