### ISSUE TITLE
OSError运行不成功

### ISSUE THREAD

**Issue by lvztpy** [testerSunshine/12306#395]
**描述问题**
```配置后运行 run.py,  出现OSError
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
```
**截图&日志**
![12306](https://user-images.githubusercontent.com/52951373/65111018-f5cfa680-da0c-11e9-91bf-f458b47253b3.JPG)

**环境信息**
 - windows 7
 - python3.7.1
 - 订票小助手版本 1.1.113

**额外的备注**
- Add any other context about the problem here.

**Comment by lvztpy** [comment]
第一次提交Issue, 不是太明白规则。 问题是，运行RUN.py以后出现：OSError的报错，希望得到解决的方法

**Comment by whitelok** [comment]
chrome driver地址没填

**Comment by lvztpy** [comment]
谢谢whitelok，我尝试过添加chromedriver的路径到环境变量里面，结果还是同样报错。
n您说的chromedriver地址没填是要在getcookie库里面的函数 里面添加吗？

**Comment by lvztpy** [comment]
oh,明白了，谢谢！

**Comment by lvztpy** [comment]
![捕获](https://user-images.githubusercontent.com/52951373/65131382-b9fb0800-da31-11e9-9213-4da41d5bceba.JPG)
添加chromechromedriver 地址以后，出现Permission ErrorWinError 5,有解决过类似问题吗

**Comment by lvztpy** [comment]
figure out what's happening
