### ISSUE TITLE
python run.py 运行报错 Mac 端  安装了 Python2.7和 Python3.6 版本

### ISSUE THREAD

**Issue by qwopczy** [testerSunshine/12306#407]
raceback (most recent call last):
  File "run.py", line 3, in <module>
    from config.serverchanConf import sendServerChan
  File "/Users/chenyi/Desktop/zUIimge/12306/12306/config/serverchanConf.py", line 4, in <module>
    from myUrllib.httpUtils import HTTPClient
  File "/Users/chenyi/Desktop/zUIimge/12306/12306/myUrllib/httpUtils.py", line 9, in <module>
    from agency.agency_tools import proxy
  File "/Users/chenyi/Desktop/zUIimge/12306/12306/agency/agency_tools.py", line 8, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
然后python3 -m pip install sendServerChan 这些库有报错
Could not find a version that satisfies the requirement sendServerChan (from versions: )
No matching distribution found for sendServerChan
You are using pip version 18.1, however version 19.2.3 is available
然后pip install --upgrade pip =》Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.2.3)
请问怎么解决

**Comment by jian2333** [comment]
你试试 sudo python3 run.py

**Comment by DiggleJone** [comment]
sudo python3 run.py 还是不行，用conda装新的环境，然后试试

**Comment by rickyscoder** [comment]
同求

**Comment by testerSunshine** [comment]
```
启动前请先筛选cdn，这点很重要
python3 run.py c
启动服务
python3 run.py r
如果你不知道如何操作，下面的命令可能会帮助你
python3 run.py -h

——————————————————————————
sage: run.py [-h] operate

positional arguments:
  operate     r: 运行抢票程序, c: 过滤cdn, t: 测试邮箱和server酱，server酱
```

**Comment by testerSunshine** [comment]
你们不看readme吗？
