### ISSUE TITLE
基于docker配置环境时依赖报错

### ISSUE THREAD

**Issue by lytk01** [testerSunshine/12306#409]
**描述问题**
```
基于docker配置环境时依赖报错
```
**重现步骤**
```
sudo ./docker.sh run 
```
**截图&日志**
![image](https://user-images.githubusercontent.com/11850959/65362472-13ce1e80-dc3a-11e9-9d63-cc6f2ebd672a.png)
**环境信息**
 - ubuntu 16.04
 - docker 1.13.1
 - 订票小助手版本 1.1.114

**猜测原因**
- Dockerfile里的基础镜像需要升级为python3

**Comment by GeorgeCh2** [comment]
FROM python:3.7.4
WORKDIR /usr/src/app
ADD . /usr/src/app

Dockerfile 中的 python 环境改为 3.x
