### ISSUE TITLE
为什么一直是cookie获取中

### ISSUE THREAD

**Issue by Zhengtq** [testerSunshine/12306#411]
**描述问题**
能运行成功，但是一直卡在了"cookie获取中"
```
A clear and concise description of what the bug is.
```
**重现步骤**
```
步骤一
编辑：TickerConfig.py
运行：sudo python run.py
```
**截图&日志**
当前配置：                                                        
出发站：{TickerConfig.FROM_STATION}                               
到达站：{TickerConfig.TO_STATION}                                 
车次: {','.join(TickerConfig.STATION_TRAINS) or '所有车次'}       
乘车日期：{','.join(TickerConfig.STATION_DATES)}                  
坐席：{','.join(TickerConfig.SET_TYPE)}                           
是否有票优先提交：{TickerConfig.IS_MORE_TICKET}                   
乘车人：{TickerConfig.TICKET_PEOPLES}                             
刷新间隔: 随机(1-3S)                                              
僵尸票关小黑屋时长: 5                                             
下单接口: 2                                                       
下单模式: 2                                                       
预售踩点时间:13:00:00                                             
**************************************************                
cookie获取中                                                      

**环境信息**
 - linux
 - python3.7.4
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
你这个很多都
