### ISSUE TITLE
大神们能给写个shell脚本，让程序在后台运行，将结果输出到日志文件吗？

### ISSUE THREAD

**Issue by zz803abc** [testerSunshine/12306#413]
这样，手机就可以远程SSH进服务器运行了，运行情况可以通过日志文件查看。这么想主要是因为我登录后经常被踢出，后台已经停了，但是用手机SSH看不到。而且，每次修改配置文件也很麻烦。想弄成这样的：
#!/bin/bash
cd 想要运行文件的路径名
中间再调用 nano /路径名/TickerConfig.py
python3 -u run.py

然后运行./start.sh > result.log &，就可以在后台运行，看日志查结果了。

如果能够这样就方便多了，还请大神们帮忙啊。

**Comment by diaguo** [comment]
./start.sh 前面加个nohup 就可以了

**Comment by zz803abc** [comment]
> ./start.sh 前面加个nohup 就可以了

关键是中间调用的nano或vim编辑完TickerConfig.py后，如何再运行run.py，在脚本里怎么写。
