### ISSUE TITLE
查询接口302

### ISSUE THREAD

**Issue by lilinyuanvr** [testerSunshine/12306#418]
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-9-30&leftTicketDTO.from_station=BXP&leftTicketDTO.to_station=LZJ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
北京西-兰州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-9-30&leftTicketDTO.from_station=BXP&leftTicketDTO.to_station=LZJ&purpose_codes=ADULT, 可以手动查询是否有票

**Comment by VCBE123** [comment]
> url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2019-9-30&leftTicketDTO.from_station=BXP&leftTicketDTO.to_station=LZJ&purpose_codes=ADULT返回参数为空, 接口状态码: 302
> 北京西-兰州 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryA?leftTicketDTO.train_date=2019-9-30&leftTicketDTO.from_station=BXP&leftTicketDTO.to_station=LZJ&purpose_codes=ADULT, 可以手动查询是否有票
我也遇到一样的问题，手动查询有票，可是无法下单
