### ISSUE TITLE
大量出现302

### ISSUE THREAD

**Issue by Mrweiliang** [testerSunshine/12306#419]
当你刷的过程中,输出有大量302的时候,建议停止运行项目,不然会导致你账号被封禁,我亲身经历,现在除了官方12306APP以外,其它任何平台都无法登陆我的12306账号,连web页面都不行

**Comment by deerli123** [comment]
我也是跑到一半开始验证码错误，一直302了，试了几次，看到你这条，关了关了

**Comment by charmingYouYou** [comment]
自己在跑脚本的ip上手动登陆下12306, 获取个验证码, 就不会有302的问题了
