### ISSUE TITLE
sudo ./docker.sh run 后 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Ethanim** [testerSunshine/12306#421]
**描述问题**
```
sudo ./docker.sh run 后 SyntaxError: invalid syntax
```
**重现步骤**
```
步骤一
运行 sudo ./docker.sh run 
出如下错误

```
**截图&日志**

Starting 12306ticket ... done
Attaching to 12306ticket
12306ticket | Traceback (most recent call last):
12306ticket |   File "run.py", line 3, in <module>
12306ticket |     from config.serverchanConf import sendServerChan
12306ticket |   File "/usr/src/app/config/serverchanConf.py", line 22
12306ticket |     sendServerChanUrls["req_url"] += f'{secret}.send'
12306ticket |                                                     ^
12306ticket | SyntaxError: invalid syntax
12306ticket exited with code 1

**环境信息**
 - mac 10.14.6 
 - python3.7.4
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by ptzrluren** [comment]
一样的错误

**Comment by Ha2ryZhang** [comment]
怎么解决的，我遇到同样问题

**Comment by 13037639065** [comment]
同样遇到该问题
