### ISSUE TITLE
运行报错name 'models' is not defined

### ISSUE THREAD

**Issue by Mickls** [testerSunshine/12306#427]
运行run.py之后发现keras库import 的models找不到
新建的虚拟环境
所有的库是根据requirements.txt安装的
在虚拟环境进入python发现form keras import models报错
![QQ图片20190926180148](https://user-images.githubusercontent.com/41884581/65679466-ba298200-e087-11e9-9104-2ce3a9d077d0.png)

**Comment by testerSunshine** [comment]
警告可以无视掉，或降下numpy的版本
