### ISSUE TITLE
验证码通过，登录失败。。。

### ISSUE THREAD

**Issue by allenmtr** [testerSunshine/12306#428]
![Screen Shot 2019-09-26 at 8 59 48 PM](https://user-images.githubusercontent.com/22385373/65690173-0e8d2b80-e0a1-11e9-81c6-75e50ceb67e3.png)

**Comment by zyh001** [comment]
@allenmtr 麻烦提供完整截图信息

**Comment by allenmtr** [comment]
> @allenmtr 麻烦提供完整截图信息

需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 12 extraneous bytes before marker 0xd9
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
题目为['文具盒']
1 文具盒
2 中国结
3 印章
4 高压锅
5 卷尺
6 文具盒
7 黑板
8 电子秤
验证码识别坐标为40,77,112,149
40,77,112,149
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=40,77,112,149&rand=sjrand&login_site=E&_=1569502712999返回参数为空, 接口状态码: 302
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '
题目为['龙舟']
1 蜜蜂
2 海苔
3 棉棒
4 拖把
5 创可贴
6 风铃
7 龙舟
8 龙舟
验证码识别坐标为184,149,256,149
184,149,256,149
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=184,149,256,149&rand=sjrand&login_site=E&_=1569502727756返回参数为空, 接口状态码: 302
登录失败
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
/usr/local/lib/python3.7/site-packages/keras/engine/saving.py:292: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '

**Comment by allenmtr** [comment]
@zyh001 帮忙看一下，谢啦！

**Comment by MinkeHuang** [comment]
和你一样的问题

**Comment by zhtangsh** [comment]
same

**Comment by zhtangsh** [comment]
```
cookie获取中





获取cookie: [{'RAIL_EXPIRATION': '1570071551040'}, {'RAIL_DEVICEID': 'EPvmpRfekqLFfK95wmyyWOBhRR3HzfiMtFO6FWx9fPo4fuPwtqdMgwhamJwVn2yQPwpSX4U2GCc5XqNAhE-2zIG8Ak8wa7SXI6xxxxBIwekjXCpDVFUyGUGAtvZPQIAnwm_g6Wdi9-hUSkZTBzlFXWOW3C'}]
cookie获取完成
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 9 extraneous bytes before marker 0x04
无需加载模型model.v2.0.h5
题目为['绿豆']
1 茶几
2 棉棒
3 红枣
4 绿豆
5 红枣
6 漏斗
7 红枣
8 日历
验证码识别坐标为256,77
256,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
````

**Comment by testerSunshine** [comment]
这种你的网页版本应是登录不上了，用手机登录一下试试

**Comment by hk517j** [comment]
和楼主一样的情况
