### ISSUE TITLE
/passport/web/login返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by chengdongwei** [testerSunshine/12306#430]
**描述问题**
```
/passport/web/login返回参数为空, 接口状态码: 302
```
**重现步骤**
```
运行一会 就提示302，手机app登录一下就好了。过了一会又提示302
```
**截图&日志**

**环境信息**
 - macos
 - python3.7.3
 - 订票小助手版本 1.1.114

**额外的备注**
- 能不能弹出扫码登录，手机app扫验证码，脚本探测扫码确认成功，代表登录成功

**Comment by mushanzi1216** [comment]
session 过期了吧  cookie那些都失效了

**Comment by testerSunshine** [comment]
cookie是会过期，一般都能自己登录上
