### ISSUE TITLE
请问我正常安装一切都正常，但是报了这个错怎么回事啊？

### ISSUE THREAD

**Issue by zhanglei7061** [testerSunshine/12306#431]
**描述问题**
```
A clear and concise description of what the bug is.
```
**重现步骤**
![image](https://user-images.githubusercontent.com/29976846/65751238-b3107b80-e13c-11e9-9d5a-4b478fe79f2a.png)

```
步骤一
```
**截图&日志**
![image](https://user-images.githubusercontent.com/29976846/65751238-b3107b80-e13c-11e9-9d5a-4b478fe79f2a.png)
**环境信息**
 - windows
 - python3.6.1
 - 订票小助手版本 1.1.101

**额外的备注**
- 麻烦帮忙看一下呗，谢谢啦，看着报错难受

**Comment by testerSunshine** [comment]
这个是numpy的版本太高了，降下版本就可以解决
