### ISSUE TITLE
登录运行过一段时间报302

### ISSUE THREAD

**Issue by xiejx618** [testerSunshine/12306#433]
**描述问题**
```
登录过一段时间报302
```
登录过一段时间报302
```
步骤一
```
![{9C989EF4-28B7-4CA0-AE5C-6487B4FD2B22}_20190929091546](https://user-images.githubusercontent.com/2609827/65824376-6d69c500-e29a-11e9-9dbf-e0261262d0e5.jpg)

**环境信息**
 - windows
 - python3.7.4
 - 订票小助手版本 1.1.114

验证码校验失败
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
下载验证码成功
Corrupt JPEG data: 15 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
'_thread._local' object has no attribute 'value'
None
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
验证码校验失败
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
09:12 10:52 01:40
车次: D7191 始发车站: 广州南 终点站: 阳江 二等座: 1
余票数小于乘车人数，当前余票数: 1, 删减人车人数到: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
下载验证码成功
Corrupt JPEG data: 13 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
'_thread._local' object has no attribute 'value'
None
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
验证码校验失败
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302

**Comment by ZhXZhao** [comment]
我也遇到了这个问题。。。

**Comment by testerSunshine** [comment]
你的keras改为2.2.4版本，如果还是不行的话，请更换云打码
