### ISSUE TITLE
请问阿里云 linux上运行,chrome获取cookie报错是ip被封吗

### ISSUE THREAD

**Issue by limboys** [testerSunshine/12306#439]
运行报错如下:
File "/root/12306/config/getCookie.py", line 17, in getDrvicesID
    driver = webdriver.Chrome(executable_path=TickerConfig.CHROME_PATH)
.......
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chr
ome has crashed.)
chrome版本: 77.0.3865.90
chromedriver: 77.0.3865.40
chromedriver已加到/usr/bin/下

**Comment by limboys** [comment]
centos 7.7 
python3.6.4

**Comment by testerSunshine** [comment]
无头浏览器获取的devicesID有问题，另外某云的服务器ip比较敏感，不推荐放某云
