### ISSUE TITLE
邮件配置

### ISSUE THREAD

**Issue by 13551527194** [testerSunshine/12306#448]
**描述问题**
IS_MAIL 参数定义却未使用

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.113

**Comment by testerSunshine** [comment]
IS_MAIL这个参数确实没被使用，因为必须要配置一个通知类型

**Comment by 13551527194** [comment]
我设置了微信的推送的，但是邮件哪儿依然走了进入


 
---原始邮件---
发件人: "zbfzn"<notifications@github.com&gt;
发送时间: 2019年10月8日 10:42:04
收件人: "testerSunshine/12306"<12306@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"13551527194"<1620829248@qq.com&gt;;
主题: Re: [testerSunshine/12306] 邮件配置 (#448)



IS_MAIL这个参数确实没被使用，因为必须要配置一个通知类型
