### ISSUE TITLE
tensorflow==1.15.0rc1这个包找不到

### ISSUE THREAD

**Issue by Ben-SYZ** [testerSunshine/12306#458]
pip3下载包时，报错说找不到这个版本的包。请问怎么解决，是否有其他兼容的版本。

**Comment by xynu617** [comment]
你是32位的python吧？换成64位应该就可以了

**Comment by xynu617** [comment]
> pip3下载包时，报错说找不到这个版本的包。请问怎么解决，是否有其他兼容的版本。

你是32位的python吧？换成64位应该就可以了

**Comment by Ben-SYZ** [comment]
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.architecture()
('64bit', 'ELF')

好像没毛病欸。

**Comment by Ben-SYZ** [comment]
补充一下报错内容 
Could not find a version that satisfies the requirement tensorflow==1.15.0rc1 (from versions: 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)
No matching distribution found for tensorflow==1.15.0rc1

**Comment by testerSunshine** [comment]
那你下载1.14.0rc1，也是可以的
