### ISSUE TITLE
Use headless model to getCookie and login

### ISSUE THREAD

**Issue by SuperFireFoxy** [testerSunshine/12306#459]
**Is your feature request related to a problem? Please describe.**
[url: /passport/web/login返回参数为空, 接口状态码: 302](https://github.com/testerSunshine/12306/issues/320)

**Describe the solution you'd like**
Use headless model to getCookie and login. Currently, when I use chrome headless model to login, it will return 302 when I call `/passport/web/login` endpoint. I don't know if it was caused by chrome headless model.

**Describe alternatives you've considered**
As for many servers, there is no desktop UI to allow us start up  a chrome browser with head 

**Additional context**

**Comment by testerSunshine** [comment]
无头模式获取的devicesID是有问题的，如果你在linux上使用，建议手动复制devicesID
```
# COOKIE_TYPE = 3, 自己打开浏览器在headers-Cookies中抓取RAIL_DEVICEID和RAIL_EXPIRATION，这个就不用配置selenium
```
