### ISSUE TITLE
12306禁止了我ip访问

### ISSUE THREAD

**Issue by JGWCoding** [testerSunshine/12306#46]
我的刷了一整天票没抢到,12306把我ip应该封禁了,同一路由下的网都访问不了12306网站,手机网可以

**Comment by testerSunshine** [comment]
你这边是自己改了刷新间隔么，默认1-3秒应该是不会封禁的

**Comment by JGWCoding** [comment]
没有改刷新间隔哦,也不知道为什么被封了

**Comment by JGWCoding** [comment]
不过一般你过个一两天之后就可以访问官网买票页面,但是现在有点用这个不敢刷,我用飞猪也在抢,会不会是账号多个平台的登录被发现问题

**Comment by testerSunshine** [comment]
> 不过一般你过个一两天之后就可以访问官网买票页面,但是现在有点用这个不敢刷,我用飞猪也在抢,会不会是账号多个平台的登录被发现问题

最好用两个账号刷刷看
