### ISSUE TITLE
requirements.txt的错误

### ISSUE THREAD

**Issue by 459266263** [testerSunshine/12306#462]
1.使用pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt代码安装的时候时候第12行代码报错找不到文件，用本地文件代替然后删除第12行就可以了也没出现问题，建议修改在线requirements.txt或者教程直接使用项目包里的requirements.txt并删掉第12行
不是程序员，第一次写问题，如果有错误请多多包涵

**Comment by testerSunshine** [comment]
#463
