### ISSUE TITLE
配置文件增加车次选择，如Gxxx,Dxxx

### ISSUE THREAD

**Issue by Samspson** [testerSunshine/12306#464]
**Is your feature request related to a problem? Please describe.**
用户只想购买某一车次的票，需要增加车次选择的配置

**Describe the solution you'd like**
现有日志中显示了多车次，K, Z, G都有显示，考虑是否增加指定车次在配置文件中供用户添加，以便用户可以自主选择车次，不会出现多趟列车，默认购买最早的一趟车次。

**Describe alternatives you've considered**

**Comment by testerSunshine** [comment]
配置文件中STATION_TRAINS里面就可以设置你想要的车次
