### ISSUE TITLE
Chrome无法运行

### ISSUE THREAD

**Issue by ForeverOpp** [testerSunshine/12306#472]
# 系统版本:CentOS 7，没有图形界面
# 安装步骤
1. 到谷歌官网下载Linux 64的RPM包
2. yum install google-chrome-stable-xxx.rpm
  
此时运行run.py报错，提示
  
The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.

遂单独运行Chrome看看错误。
# 单独运行Chrome
google-chrome &
报错，似乎权限问题。查了以后更改了/opt/google/chrome/chrome，并且把/opt/google/chrome/chrome-sandbox chown root，chmod 4755之后，用google-chrome —no-sandbox —user-dir-data运行，仍然报错
[1121/142718.123150:ERROR:nacl_helper_linux.cc(311)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly
  
那咋办嘛，查了一下这个问题2015年的Chrome 30就有了，一直持续到现在。
  
问题没有出在图形界面上，我看相似问题有人也没有图形界面仍然安装成功，我没辙了，求大佬救命。

**Comment by testerSunshine** [comment]
可以手动复制devicesId, COOKIE_TYPE设置为3
