### ISSUE TITLE
提示ModuleNotFoundError: No module named 'wrapcache',但我pip install显示已经装了

### ISSUE THREAD

**Issue by moluoyu** [testerSunshine/12306#476]
![image](https://user-images.githubusercontent.com/27038644/69903709-23a37500-13d8-11ea-8bef-52edb49847b8.png)

**Comment by 372620040** [comment]
同样的问题+1

**Comment by hhuang3068** [comment]
sudo -H python3 -m pip install wrapcache

**Comment by hhuang3068** [comment]
sudo -H python3 -m pip install wrapcache

**Comment by hhuang3068** [comment]
sudo -H python3 -m pip install wrapcache
是有安装多个python版本吗？我用这条命令重新安装wrapcache，解决了问题

**Comment by CatEatFishs** [comment]
> sudo -H python3 -m pip install wrapcache
> 是有安装多个python版本吗？我用这条命令重新安装wrapcache，解决了问题

我只有一个版本，还是报这个错
C:\Users\ht\Desktop\12306-master>python run.py r
Traceback (most recent call last):
  File "run.py", line 21, in <module>
    from init import select_ticket_info
  File "C:\Users\ht\Desktop\12306-master\init\select_ticket_info.py", line 10, in <module>
    import wrapcache
ModuleNotFoundError: No module named 'wrapcache'
如何解决呢，谢谢
