### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0

### ISSUE THREAD

**Issue by jclcoder** [testerSunshine/12306#481]
ERROR: Could not find a version that satisfies the requirement tensorflow==2.0.0 (from -r requirements.txt (line 12)) (from versions: none)
ERROR: No matching distribution found for tensorflow==2.0.0 (from -r requirements.txt (line 12))

我已经安装tensorflow了版本也对，为什么出现这个错误就大佬帮忙

**Comment by ccmin** [comment]
Collecting tensorflow==1.15.0rc1 (from -r requirements.txt (line 12))
  Could not find a version that satisfies the requirement tensorflow==1.15.0rc1 (from -r requirements.txt (line 12)) (from versions: 0.12.0rc0, 0.12.0rc1, 0.12.0, 0.12.1, 1.0.0, 1.0.1, 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.1.0, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.3.0, 1.4.0rc0, 1.4.0rc1, 1.4.0, 1.4.1, 1.5.0rc0, 1.5.0rc1, 1.5.0, 1.5.1, 1.6.0rc0, 1.6.0rc1, 1.6.0, 1.7.0rc0, 1.7.0rc1, 1.7.0, 1.7.1, 1.8.0rc0, 1.8.0rc1, 1.8.0, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0rc0, 1.10.0rc1, 1.10.0, 1.10.1, 1.11.0rc0, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.12.0, 1.12.2, 1.12.3, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.13.1, 1.13.2, 1.14.0rc0, 1.14.0rc1, 1.14.0, 2.0.0a0, 2.0.0b0, 2.0.0b1)


No matching distribution found for tensorflow==1.15.0rc1 (from -r requirements.txt (line 12))
我也遇到了这个问题，，目前自己换成1.14.0rc1貌似可以安装。
