### ISSUE TITLE
发布到docker hub

### ISSUE THREAD

**Issue by soap-man** [testerSunshine/12306#489]
可以发布到docker hub咩， 这样就可以很方便拉取image跑起来了 😄

**Comment by amColinzzz** [comment]
我也希望作者能将docker.sh改为直接去docker-hub拉取镜像

**Comment by hhzrz** [comment]
因为配置文件[TickerConfig.py](https://github.com/testerSunshine/12306/blob/master/TickerConfig.py)是必须由用户按各自需求进行修改的，且此配置文件又是一个python代码文件，需要直接和程序配合使用，所以使用自己构建镜像的方式运行更为方便。而且最新的镜像构建代码已经大大优化，基镜像是一个只有50M左右的python:3.7-slim-buster，所以请拉取最新的代码，使用docker-compose运行吧。
