### ISSUE TITLE
乘车人识别问题

### ISSUE THREAD

**Issue by huojicache** [testerSunshine/12306#492]
**描述问题**
```
以下配置:
TICKET_PEOPLES = [
"张三"]
会被识别成 乘车人: ['张三']
```
**重现步骤**
以上配置重复出现
```
步骤一
```
**截图&日志**
![车](https://user-images.githubusercontent.com/37629177/70842233-fcc75300-1e5b-11ea-9657-0fad5b14e9fb.PNG)

**环境信息**
 - windows
 - python3.7.5
 - 订票小助手版本 1.1.101

**额外的备注**
无

**Comment by FizzClown** [comment]
我一直出现那个String识别成byte的错误，看了你的问题，我把乘车人用单引号就可以了
