### ISSUE TITLE
也是登陆成功查询余票返回302（重定向错误，）

### ISSUE THREAD

**Issue by Zhaoxiasi** [testerSunshine/12306#493]
**描述问题**
```
登陆成功，打码成功，但是查询余票失败了，返回302错误，
```
**重现步骤**
```

```
**截图&日志**
验证码通过,开始登录..
登录成功
欢迎 赵夏思 登录
开启cdn查询
本次待筛选cdn总数为1857, 筛选时间大约为5-10min
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第1次查询 随机停留时长：3.2 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：497.211ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第2次查询 随机停留时长：4.79 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：491.636ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第3次查询 随机停留时长：3.75 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：530.293ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第4次查询 随机停留时长：3.85 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：397.606ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第5次查询 随机停留时长：3.74 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：454.376ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第6次查询 随机停留时长：3.33 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：513.243ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第7次查询 随机停留时长：4.75 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：430.58ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第8次查询 随机停留时长：4.02 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：509.542ms
url: /otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT返回参数为空, 接口状态码: 302
成都东-邯郸东 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/query?leftTicketDTO.train_date=2019-12-25&leftTicketDTO.from_station=ICW&leftTicketDTO.to_station=HPP&purpose_codes=ADULT, 可以手动查询是否有票
正在第9次查询 随机停留时长：4.18 乘车日期: 2019-12-25 车次：G1702 下单无票 耗时：496.307ms

**环境信息**
 - windows 10
 - python3.7.1
 - 订票小助手版本 1.1.117

**额外的备注**
我发现通过浏览器手动查票的ip地址是117.27.245.XXX，福建的
我本地的ip是118.123.233.XXX，四川成都
另外request请求里，
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.9
Cache-Control:no-cache
Connection:keep-alive
Cookie:JSESSIONID=AF19D39B9EC468328A399E17F41C31E8; tk=tJmm0KHu65ZypD_u0X3NPYKSuI7nYfi5ijz1z0; _jc_save_fromStation=%u6210%u90FD%2CCDW; _jc_save_toStation=%u90AF%u90F8%2CHDP; _jc_save_wfdc_flag=dc; BIGipServerotn=1440284938.24610.0000; BIGipServerpassport=854065418.50215.0000; RAIL_EXPIRATION=1576596121361; RAIL_DEVICEID=QAEW-WoUkR9zw_cIKYpKMnabgB8GouEJxJvllcVnllU-wgWLmP_81Wo0DvqeY0fgz1_g8OWT9fNFoioesiojtKYi0vva8m3uZRNRFhG-GIonRoCs4k7uUmFS4doUuuB1Xr7GcplVAdp5WnOWrI10w_SkaNTEXxIT; route=9036359bb8a8a461c164a04f8f50b252; _jc_save_toDate=2019-12-14; _jc_save_fromDate=2019-12-25
Host:kyfw.12306.cn
If-Modified-Since:0
Referer:https://kyfw.12306.cn/otn/leftTicket/init?linktypeid=dc&fs=%E6%88%90%E9%83%BD,CDW&ts=%E9%82%AF%E9%83%B8,HDP&date=2019-12-14&flag=N,N,Y
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
X-Requested-With:XMLHttpRequest
--------以上是成功的headers
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.9
Connection:keep-alive
Cookie:JSESSIONID=AF19D39B9EC468328A399E17F41C31E8; tk=tJmm0KHu65ZypD_u0X3NPYKSuI7nYfi5ijz1z0; _jc_save_fromStation=%u6210%u90FD%2CCDW; _jc_save_toStation=%u90AF%u90F8%2CHDP; _jc_save_wfdc_flag=dc; BIGipServerotn=1440284938.24610.0000; BIGipServerpassport=854065418.50215.0000; RAIL_EXPIRATION=1576596121361; RAIL_DEVICEID=QAEW-WoUkR9zw_cIKYpKMnabgB8GouEJxJvllcVnllU-wgWLmP_81Wo0DvqeY0fgz1_g8OWT9fNFoioesiojtKYi0vva8m3uZRNRFhG-GIonRoCs4k7uUmFS4doUuuB1Xr7GcplVAdp5WnOWrI10w_SkaNTEXxIT; route=9036359bb8a8a461c164a04f8f50b252; _jc_save_toDate=2019-12-14; _jc_save_fromDate=2019-12-25
Host:kyfw.12306.cn
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
----以上是失败302的headers

**Comment by iconteral** [comment]
貌似今天查询余票的接口有变，我刚刚在12306上看了下发现多了个O
https://kyfw.12306.cn/otn/leftTicket/**query_O_**?leftTicketDTO.train_date=_station_date_&leftTicketDTO.from_station=_from_station_&leftTicketDTO.to_station=_to_station_&purpose_codes=ADULT

**Comment by LiuWeiren** [comment]
查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下

**Comment by dingqing** [comment]
> 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下

亲试有用

**Comment by shicaiwei123** [comment]
补充一下，如果修改了还不成功，可能是时间格式问题。
我之前时间格式是2019-1-12，就一直不行。然后2019-01-12就好了

**Comment by Thegonedays** [comment]
# 如果COOKIE_TYPE=3, 则需配置RAIL_EXPIRATION、RAIL_DEVICEID的值
RAIL_EXPIRATION = 
RAIL_DEVICEID =

自己登陆12306然后查下cookie就vans

**Comment by hetun125** [comment]
> elect_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试
请问改了接口可以查到票，但又打码失败是什么原因？

**Comment by hetun125** [comment]
> 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下

请问改了接口可以查到票，但又打码失败是什么原因？原来leftTicket/query打码登录是没问题的

**Comment by Nisemono23** [comment]
> 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下

我这边倒是没有效果，

**Comment by Nisemono23** [comment]
> 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下

改了，但是还有问题；
深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-16&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-17&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-18&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
url: /otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-19&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT返回参数为空, 接口状态码: 302

**Comment by hetun125** [comment]
> > 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下
> 
> 改了，但是还有问题；
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-16&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-17&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-18&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> url: /otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-19&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT返回参数为空, 接口状态码: 302

你改成leftTicket/queryA试一下

**Comment by LiuWeiren** [comment]
> > 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下
> 
> 请问改了接口可以查到票，但又打码失败是什么原因？原来leftTicket/query打码登录是没问题的

我也是小白，不是很清楚，你可以把错误贴出来，或者更新一下项目

**Comment by LiuWeiren** [comment]
> > 查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryO"试一下
> 
> 改了，但是还有问题；
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-16&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-17&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> 深圳北-武汉 车次坐席查询为空，查询url: https://kyfw.12306.cn/otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-18&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT, 可以手动查询是否有票
> url: /otn/leftTicket/queryO?leftTicketDTO.train_date=2020-01-19&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT返回参数为空, 接口状态码: 302

接口又变了，前两天新的提交已经支持动态更新接口了，你可以更新一下看看

**Comment by jingtian123** [comment]
查票接口变了，select_ticket_info.py第45行，"leftTicket/query"改成"leftTicket/queryA"试一下

**Comment by yiailake** [comment]
![image](https://user-images.githubusercontent.com/5363570/71227922-a787b780-231b-11ea-9ed8-6faea6747558.png)
