### ISSUE TITLE
接口地址，候补

### ISSUE THREAD

**Issue by Mrgrtt** [testerSunshine/12306#497]
接口地址会经常变化，query后面的一个大写字母会变，如queryO变成queryA，具体是什么可去12306网站查看请求URL。可候补的条件判断不准确，不能候补二等座。据我观察，ticket_info[-8] == 'O'时二等座无候补。

**Comment by xianhaiyuan** [comment]
对的，我也发现二等座不能候补

**Comment by kum1ko** [comment]
[https://github.com/testerSunshine/12306/blob/master/inter/Query.py#L154](url)
候补车票判定有误，ticket_info[37]应该才是候补标记，观察了官网的js
`cR.houbu_train_flag = cN[37];`

而且`if ticket_info[11] == "Y"`表示既可以购买也可以候补（canWebBuy），不应该在elseif中判定是否可以候补

这一块的逻辑没有细看，如有误再讨论

**Comment by testerSunshine** [comment]
https://github.com/testerSunshine/12306/commit/008c7ecd420d563a7cfbd825e74560d8ff04adaa
确实是cN[37]才是可以判断候补，上面这个提交已修复
