### ISSUE TITLE
返回参数为空, 接口状态码: 302

### ISSUE THREAD

**Issue by BetwayM** [testerSunshine/12306#508]
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/web/auth/uamtk-static返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-check?callback=jQuery19108016482864806321_1554298927290&answer=112,77,256,77&rand=sjrand&login_site=E&_=1576546764619返回参数为空, 接口状态码: 302

**Comment by xianhaiyuan** [comment]
我也是这个问题

**Comment by weibeihai** [comment]
我也是啊，偶尔没有，，，很迷

**Comment by testerSunshine** [comment]
更新最新版本可以缓解这个问题
