### ISSUE TITLE
12306接口无响应

### ISSUE THREAD

**Issue by HashWaney** [testerSunshine/12306#512]
python版本 3.7
系统版本：Mac

车次：D2330 出发站：深圳北 到达站：福州 历时：05:44 商务/特等座：-- 一等座：有 二等座：有 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：有 预订
车次：D3340 出发站：深圳北 到达站：福州 历时：05:32 商务/特等座：-- 一等座：7 二等座：有 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：有 预订
车次：D3342 出发站：深圳北 到达站：福州 历时：05:30 商务/特等座：-- 一等座：无 二等座：无 动卧：-- 硬卧：-- 软座：-- 硬座：-- 无座：无 预订
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str
12306接口无响应，正在重试 can only concatenate str (not "dict") to str

**Comment by testerSunshine** [comment]
跟新1.2.001版本
