### ISSUE TITLE
无法登录12306

### ISSUE THREAD

**Issue by znone** [testerSunshine/12306#517]
描述问题

启动后到登录12306阶段循环报告以下错误：

验证码识别坐标为256,77,184,149
256,77,184,149
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302

版本1.2.001下该问题依旧存在

重现步骤

只需要修改配置中的用户名密码，然后启动程序。

步骤一
截图&日志

被重定向的地址是
https://www.12306.cn/mormhweb/logFiles/error.html

日志输出
[2019-12-17 10:44:00,815][ INFO] --- url: /passport/web/login 返回参数为空 (logger.py:61)

环境信息

ubuntu18.4
python3.7.1
订票小助手版本 1.2.001
额外的备注

Windows7下不出现该问题。

**Comment by HeatonZ** [comment]
把chromedriver.exe兼容性设置成win7试试

**Comment by byrain** [comment]
也遇到了这个问题

 centos7 docker运行

**Comment by lifenglsf** [comment]
> 把chromedriver.exe兼容性设置成win7试试

没有搜索到chromedriver.exe这个文件呢，文件在什么位置？python的package和repo目录都没有搜索到

**Comment by lifenglsf** [comment]
> 描述问题
> 
> 启动后到登录12306阶段循环报告以下错误：
> 
> 验证码识别坐标为256,77,184,149
> 256,77,184,149
> 验证码通过,开始登录..
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> url: /passport/web/login返回参数为空, 接口状态码: 302
> 
> 版本1.2.001下该问题依旧存在
> 
> 重现步骤
> 
> 只需要修改配置中的用户名密码，然后启动程序。
> 
> 步骤一
> 截图&日志
> 
> 被重定向的地址是
> https://www.12306.cn/mormhweb/logFiles/error.html
> 
> 日志输出
> [2019-12-17 10:44:00,815][ INFO] --- url: /passport/web/login 返回参数为空 (logger.py:61)
> 
> 环境信息
> 
> ubuntu18.4
> python3.7.1
> 订票小助手版本 1.2.001
> 额外的备注
> 
> Windows7下不出现该问题。

程序默认COOKIE_TYPE=3,把COOKIE_TYPE改为1，并配置CHROME_PATH和CHROME_CHROME_PATH可以正常登陆。COOKIE_TYPE=3需要自己打开浏览器登陆获取到RAIL_EXPIRATION、RAIL_DEVICEID，并配置好

**Comment by znone** [comment]
我用的时候，COOKIE_TYPE设置为1的，并且chrome和chromedriver和相关设置都正确了，否则程序跑不到登录那一步。
现在发现在windows7下查询热门时间的余票也出错了，感觉这个软件用不了了。

**Comment by wa278** [comment]
我同样出现了此问题，我确认我的chromedriver已经生效。我的环境是阿里云的ubuntu构建了py37的docker.

**Comment by yzbwork** [comment]
> 我同样出现了此问题，我确认我的chromedriver已经生效。我的环境是阿里云的ubuntu构建了py37的docker.

ip被限制的问题，你直接打开12306是不是页面会出现一个蓝色的提示框

**Comment by ltc-macrochen** [comment]
我是ORDER_MODEL为1（预售）时就会出现这个错误，应该是请求太频繁，被限制了IP；预售时没到时间感觉不应该不停的去尝试登录或者查询信息

**Comment by neroneroffy** [comment]
> 我是ORDER_MODEL为1（预售）时就会出现这个错误，应该是请求太频繁，被限制了IP；预售时没到时间感觉不应该不停的去尝试登录或者查询信息

确实是这样，我一直请求未开售的日期，刷票302，后来重启后登录都302，最后改了COOKIE_TYPE等于1，不刷未发售的日期，就可以了
