### ISSUE TITLE
12306 queryA 规则变化

### ISSUE THREAD

**Issue by goldencolor** [testerSunshine/12306#52]
https://kyfw.12306.cn/otn/leftTicket/queryA
里面的queryA会一直变化导致无法访问，是否有什么方案和规则？

**Comment by testerSunshine** [comment]
这个只能如果发现规则变化，目前手动抓包更改可以解决，还有种方法是去12306init页面去截取他的query 接口

**Comment by zjcnew** [comment]
> https://kyfw.12306.cn/otn/leftTicket/queryA
> 里面的queryA会一直变化导致无法访问，是否有什么方案和规则？

python3写的余票查询样例，可以试试。

[web.zip](https://github.com/testerSunshine/12306/files/2552914/web.zip)
