### ISSUE TITLE
预售票模式报错gcm

### ISSUE THREAD

**Issue by starcraftvs** [testerSunshine/12306#524]
**描述问题**
```
预售票模式下登录成功后一直报错：ERROR:gcm_channel_status_request.cc(145)] GCM channel request failed.
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Aimneat** [comment]
预售还未开始就会报这种信息

**Comment by testerSunshine** [comment]
https://github.com/testerSunshine/12306/issues/545
