### ISSUE TITLE
Python3报错expected string or bytes-like object

### ISSUE THREAD

**Issue by zhandouxiaojiji** [testerSunshine/12306#526]
**截图&日志**
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    select_ticket_info.select().main()
  File "/root/12306/init/select_ticket_info.py", line 121, in main
    l.reqLiftTicketInit()
  File "/root/12306/inter/LiftTicketInit.py", line 18, in reqLiftTicketInit
    matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', result, re.M|re.I);
  File "/usr/local/lib/python3.7/re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

**环境信息**
 - linux
 - python3.7.3
 - 订票小助手版本 1.2.002

**Comment by zhandouxiaojiji** [comment]
https://github.com/testerSunshine/12306/blob/008c7ecd420d563a7cfbd825e74560d8ff04adaa/inter/LiftTicketInit.py#L18
这一行改成matchObj = re.search('var CLeftTicketUrl = \'(.*)\'', str(result), re.M|re.I);后可以正常运行

**Comment by ybyangjian** [comment]
改了后能正常抢票吗？

**Comment by mnxzyw** [comment]
turn off proxy and proxy environment

**Comment by zhandouxiaojiji** [comment]
@ybyangjian 关掉代理可以，我中午刚抢了一张，哈哈

**Comment by wu-yy** [comment]
我看报的错里面的 result 是：result: {'code': 99999, 'message': '重试次数达到上限'}
