### ISSUE TITLE
查到票了，但没有提交，为啥？---后来过了3分11秒才抢到

### ISSUE THREAD

**Issue by bambi2016** [testerSunshine/12306#534]
正在第537次查询 停留时间：2.86 乘车日期: 2020-01-18 车次：1461 下单无票 无候补机会 耗时：900.627 106.41.0.62
正在第538次查询 停留时间：3.0 乘车日期: 2020-01-18 车次：1461 下单无票 无候补机会 耗时：452.598 122.224.186.223
11:55 07:00 19:05
车次: 1461 始发车站: 北京 终点站: 上海 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
11:55 07:00 19:05
车次: 1461 始发车站: 北京 终点站: 上海 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
11:55 07:00 19:05
车次: 1461 始发车站: 北京 终点站: 上海 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
11:55 07:00 19:05
车次: 1461 始发车站: 北京 终点站: 上海 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
url: /otn/leftTicket/submitOrderRequest返回参数为空, 接口状态码: 302
11:55 07:00 19:05
车次: 1461 始发车站: 北京 终点站: 上海 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
url: /otn/confirmPassenger/checkOrderInfo返回参数为空, 接口状态码: 302
车票提交通过，正在尝试排队
排队成功, 你排在: 10位, 当前余票还剩余: 125 张
不需要验证码
url: /otn/confirmPassenger/confirmSingleForQueue返回参数为空, 接口状态码: 302
排队等待时间预计还剩 -316 ms
排队等待时间预计还剩 -386 ms
排队等待时间预计还剩 -383 ms
排队等待时间预计还剩 -375 ms
排队等待时间预计还剩 -370 ms
排队等待时间预计还剩 -365 ms
排队等待时间预计还剩 -356 ms
排队等待时间预计还剩 -351 ms
排队等待时间预计还剩 -338 ms
排队等待时间预计还剩 -330 ms
排队等待时间预计还剩 -324 ms
排队等待时间预计还剩 -316 ms
排队等待时间预计还剩 -306 ms
排队等待时间预计还剩 -296 ms
排队等待时间预计还剩 -122 ms
排队等待时间预计还剩 -120 ms
排队等待时间预计还剩 -114 ms
排队等待时间预计还剩 -111 ms
排队等待时间预计还剩 -108 ms
排队等待时间预计还剩 -106 ms
排队等待时间预计还剩 -102 ms
排队等待时间预计还剩 -99 ms
排队等待时间预计还剩 -96 ms
排队等待时间预计还剩 -91 ms
排队等待时间预计还剩 -85 ms
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302
url: /otn/confirmPassenger/queryOrderWaitTime?random=1576807333316&tourFlag=dc&_json_att=返回参数为空, 接口状态码: 302

**Comment by bambi2016** [comment]
第82次排队中,请耐心等待
登录成功
欢迎 赵欣雅 登录
恭喜您订票成功，订单号为：E3979512, 请立即打开浏览器登录12306，访问‘未完成订单’，在30分钟内完成支付!

**Comment by testerSunshine** [comment]
最新已优化302这个问题，还是和你自己的网络环境有关
