### ISSUE TITLE
执行run.py运行程序验证码下载失败，一直报302

### ISSUE THREAD

**Issue by ltt1992** [testerSunshine/12306#535]
**描述问题**
执行run.py运行程序验证码下载失败，一直报302
```
**重现步骤**
```
步骤一
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 2
下单模式: 2
预售踩点时间:08:00:00
**************************************************
cookie获取中
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.06988953244274021&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
验证码获取失败
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.14028214909108416&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
验证码获取失败

**Comment by ltt1992** [comment]
环境信息
macos
检查当前版本为: 1.2.003
检查当前python版本为：3.7.3

**Comment by aa1678066774** [comment]
我的也是这样

**Comment by ltt1992** [comment]
正在找问题，多方咨询，哈哈，共同努力，为了回家。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aa1678066774"<notifications@github.com&gt;; 
发送时间: 2019年12月20日(星期五) 上午10:54
收件人: "testerSunshine/12306"<12306@noreply.github.com&gt;; 
抄送: " "<373827048@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [testerSunshine/12306] 执行run.py运行程序验证码下载失败，一直报302 (#535)




我的也是这样

**Comment by aa1678066774** [comment]
是不是云打码那个不行，我用的他们issue里面的

**Comment by aa1678066774** [comment]
用他们的调接口调不通

**Comment by ltt1992** [comment]
> 是不是云打码那个不行，我用的他们issue里面的

我也是用的那个云打码，你用的那个，能贴出来看看吗

**Comment by ltt1992** [comment]
> 用他们的调接口调不通

正在努力调，问下大佬们都咋弄的

**Comment by aa1678066774** [comment]
HOST = "106.12.33.19:33254"
REQ_URL = "/verify/base64/"
HTTP_TYPE = "http"

**Comment by ltt1992** [comment]
![image](https://user-images.githubusercontent.com/33643650/71227238-7b6b3700-2319-11ea-9ed6-6c42cd282b9c.png)
请问你们是这样配的吗，这里。

**Comment by ltt1992** [comment]
> HOST = "106.12.33.19:33254"
> REQ_URL = "/verify/base64/"
> HTTP_TYPE = "http"

我配置好以后，现在这个地方一直报没no chrome binary at /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome\Google Chrome

**Comment by aa1678066774** [comment]
图片看不到，你粘贴一下文本

**Comment by ltt1992** [comment]
> 图片看不到，你粘贴一下文本

 COOKIE_TYPE = 1
 # 如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
 # chromedriver配置版本只要和chrome的大版本匹配就行
 CHROME_PATH = "/Users/ltt/Downloads/chromedriver"

 # 为了docker37 准备的环境变量，windows环境可以不用管这个参数
 CHROME_CHROME_PATH = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome\Google Chrome"

**Comment by aa1678066774** [comment]
这个地方我配置的3

**Comment by ltt1992** [comment]
> 这个地方我配置的3
可以了，已经跑起来了，感谢感谢，

**Comment by aa1678066774** [comment]
我还是下载不了验证码，你这个地方怎么解决的

**Comment by aa1678066774** [comment]
cookie获取中
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
验证码获取失败
url: /otn/login/conf返回参数为空, 接口状态码: 302
url: /otn/login/conf返回参数为空, 接口状态码: 302
需要验证码
下载验证码...
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
验证码获取失败

**Comment by navygg** [comment]
按照作者的说法应该是被封了IP，我的也不行

**Comment by ltt1992** [comment]
> cookie获取中
> 需要验证码
> 下载验证码...
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.12247091592519&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> 验证码获取失败
> url: /otn/login/conf返回参数为空, 接口状态码: 302
> url: /otn/login/conf返回参数为空, 接口状态码: 302
> 需要验证码
> 下载验证码...
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302 url: /passport/captcha/captcha-image64?login_site=E&module=login&rand=sjrand&0.8787797232848942&callback=jQuery19108016482864806321_1554298927290&_=1554298927293返回参数为空, 接口状态码: 302
> 验证码获取失败
 
我改成3 然后登陆12306，把那两个字段拿出来了
  COOKIE_TYPE = 3
 # 如果COOKIE_TYPE=1，则需配置chromeDriver路径,下载地址http://chromedriver.storage.googleapis.com/index.html
 # chromedriver配置版本只要和chrome的大版本匹配就行
 CHROME_PATH = "/Users/ltt/Downloads/chromedriver"

 # 为了docker37 准备的环境变量，windows环境可以不用管这个参数
 CHROME_CHROME_PATH = "/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome\Google Chrome"
 # 如果COOKIE_TYPE=3, 则需配置RAIL_EXPIRATION、RAIL_DEVICEID的值
 RAIL_EXPIRATION = "1577033439142"
 RAIL_DEVICEID = "GF3yOjmSdA7TR0SatrZ136gzqpc5UxWVdlhCk6u4w1fyIq_I1cqOIP_TV0gsuc_ujCsuVYSFhbe_5H6CpPFslI1_koLmXxgq27ZOo4JlU8kpEujE3uE2X8cueC1vgqQxZdbIKUfmPOwqYUXN-0F76vI6SRTHdVNp"

**Comment by navygg** [comment]
README.md中有说：如果下载验证码过期或者下载失败的问题，应该是12306封ip的策略，多重试几次，12306现在封服务器(阿里云和腾讯云)ip比较严重，尽量不要放在服务器里面。目前12306对服务器ip比较敏感，大家还是在自己家里挂着吧

**Comment by ltt1992** [comment]
> README.md中有说：如果下载验证码过期或者下载失败的问题，应该是12306封ip的策略，多重试几次，12306现在封服务器(阿里云和腾讯云)ip比较严重，尽量不要放在服务器里面。目前12306对服务器ip比较敏感，大家还是在自己家里挂着吧

感谢感谢

**Comment by ltt1992** [comment]
感谢各位，都是为了回家。哈哈哈

**Comment by aa1678066774** [comment]
下载验证码成功
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
验证码识别坐标为256,77,256,149
256,77,256,149

**Comment by ltt1992** [comment]
> 下载验证码成功
> 您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
> 验证码识别坐标为256,77,256,149
> 256,77,256,149

改成他们最初的那个，就不提示了，

**Comment by yiailake** [comment]
url: /otn/login/checkUser返回参数为空, 接口状态码: 302
url: /otn/leftTicket/queryA?leftTicketDTO.train_date=2020-01-18&leftTicketDTO.from_station=GZQ&leftTicketDTO.to_station=WHN&purpose_codes=ADULT返回参数为空, 接口状态码: 302

**Comment by ltt1992** [comment]
问题已解决
