### ISSUE TITLE
12306 用户登录返回 302 修复方案

### ISSUE THREAD

**Issue by AnndaGH** [testerSunshine/12306#537]
**描述问题**
```
启动后用户登录持续报 url: /passport/web/login返回参数为空, 接口状态码: 302
```
**重现步骤**
```
在 TickerConfig.py 中编辑
USER = "xxx"
PWD = "xxx"
COOKIE_TYPE = 1
运行 python3 run.py r
```
**截图&日志**
...
cookie获取完成
需要验证码
下载验证码...
下载验证码成功
Corrupt JPEG data: 14 extraneous bytes before marker 0xd9
无需加载模型model.v2.0.h5
题目为['茶几']
1 茶几
2 茶几
3 热水袋
4 中国结
5 护腕
6 手掌印
7 冰箱
8 手掌印
验证码识别坐标为40,77,112,77
40,77,112,77
验证码通过,开始登录..
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
url: /passport/web/login返回参数为空, 接口状态码: 302
...

**环境信息**
 - centos 7.7 x64
 - python3.6.8
 - 订票小助手版本 1.2.003
 - google-chrome-stable-79.0.3945.88-1.x86_64
 - ChromeDriver 79.0.3945.36

**修复方案**
- 添加 chrome cookie 获取时配置指定 ua
编辑 config/getCookie.py 第24行加入以下代码
options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36')
![image](https://user-images.githubusercontent.com/19545970/71230793-fcc8c680-2325-11ea-802a-a1b4857e2eeb.png)
保存后正常运行脚本即可，测试了几次都是秒登

**Comment by yangsoon** [comment]
我试着改了一下 确实可以登录，你可以提一个pr 让作者合一下

**Comment by Sungen** [comment]
确实能解决问题，不然一大堆请求都是302

**Comment by bambi2016** [comment]
每个人使用的浏览器应该不一样吧？参数也都不同

**Comment by testerSunshine** [comment]
你的可以获取嘛？

**Comment by AnndaGH** [comment]
> 每个人使用的浏览器应该不一样吧？参数也都不同
我翻过几个Issue问题集中出现在linux上，因为cookie自动获取部分没有指定UA，默认携带的是Linux Headless UA直接请求到12306的，返回的cookie我觉得应该是做过标记的12306服务器能够筛选，也算是一种防爬防抢票机制。这个跟你每个人使用的浏览器无关，毕竟COOKIE_TYPE参数是1的时候都会调chrome也就统一了

**Comment by AnndaGH** [comment]
> 每个人使用的浏览器应该不一样吧？参数也都不同

我翻过几个Issue问题集中出现在linux上，因为cookie自动获取部分没有指定UA，默认携带的是Linux Headless UA直接请求到12306的，返回的cookie我觉得应该是做过标记的12306服务器能够筛选，也算是一种防爬防抢票机制。这个跟你每个人使用的浏览器无关，毕竟COOKIE_TYPE参数是1的时候都会调chrome也就统一了

**Comment by rickyscoder** [comment]
mark

**Comment by vonlyinno** [comment]
赞一个！把ua换成自己浏览器的就完美解决

**Comment by Fupengfei01** [comment]
mark

**Comment by appleftg** [comment]
mark
