### ISSUE TITLE
希望提供编译好的Docker镜像发布到Dockerhub,脚本执行错误,Docker失败

### ISSUE THREAD

**Issue by amColinzzz** [testerSunshine/12306#538]
您好,这个项目很好,但是pythone环境配置繁琐,既然提供了docker.sh脚本,麻烦能否提供编译好的docker镜像,发布到dockerhub.
目前使用docker.sh run,我这边会报错,错误代码如下:
` Could not find a version that satisfies the requirement matplotlib>=3.0.2 (from -r requirements.txt (line 11)) (from versions: 0.86, 0.86.1, 0.86.2, 0.91.0, 0.91.1, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1rc1, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 2.0.0b1, 2.0.0b2, 2.0.0b3, 2.0.0b4, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.0.2, 2.1.0rc1, 2.1.0, 2.1.1, 2.1.2, 2.2.0rc1, 2.2.0, 2.2.2, 2.2.3, 2.2.4)
No matching distribution found for matplotlib>=3.0.2 (from -r requirements.txt (line 11))
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'ticket' failed to build: The command '/bin/sh -c pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pyspider --no-cache-dir -r requirements.txt' returned a non-zero code: 1
`

**Comment by labulaka521** [comment]
没有找到这个版本号换一个

**Comment by wenhuwang** [comment]
@labulaka521 同问  我也是上面的问题，麻烦问一下需要换什么版本号？项目中提供了两个版本的dockerfile，默认使用python2.7的，如果要使用python3.7的在哪里可以配置？

**Comment by testerSunshine** [comment]
用37的那个
https://github.com/testerSunshine/12306/blob/master/Dockerfile37
