### ISSUE TITLE
希望能封装完善的Docker镜像.

### ISSUE THREAD

**Issue by amColinzzz** [testerSunshine/12306#540]
1.通常Docker-compose是为了关联多个docker容器的,但是我发现docker-compose.yml文件中只有一个镜像,为什么要这样?
2.通常Docker镜像会将单独的配置文件目录拉出来,这样可以-v只映射需要修改配置文件目录的地方,但是现在是整个app目录下的文件都要映射出来,而需要改动的,只有配置文件那一个目录
3.使用docker logs containers 命令无法查看命令,也不知道哪个文件是输出的日志.

希望大家一起努力封装一个完善的docker容器出来.

**Comment by testerSunshine** [comment]
https://github.com/testerSunshine/12306/pull/518 
大佬在这里完善了docker，可以在这issues讨论一下
