### ISSUE TITLE
登陆时验证码获取失败，codeImgUrlRsp返回为dict: {'code': 99999, 'message': '重试次数达到上限'}, 不是期望的str

### ISSUE THREAD

**Issue by heliharry** [testerSunshine/12306#541]
描述问题
登陆时，不能获取验证码，增加了打印输出codeImgUrlRsp，结果是dict
codeImgUrlRsp={'code': 99999, 'message': '重试次数达到上限'}

打开浏览器手动登陆没有问题。

截图&日志
当前配置：
乘车日期：2020-01-18
坐席：二等座
是否有票优先提交：True
刷新间隔: 随机(1-3S)
僵尸票关小黑屋时长: 5
下单接口: 1
下单模式: 2
预售踩点时间:08:00:00
**************************************************
cookie获取中
获取cookie: [{'RAIL_DEVICEID': 'esSLnzY5wyEaxt4REXPehq_tMnqC6HInGWPv16mT6aerZOcjXcMOxS9Z-zXwRQawSlhcLdJHCMY2enqQ1LlEmhmMABfJv4G1YD0JPB6hhCj7IbFzxZlkv_afNwJFx_sw5kzOLn_tQx9gi-8H-AWY7hWlOUOlJqUG'}, {'RAIL_EXPIRATION': '1577113934461'}]
cookie获取完成
需要验证码
下载验证码...
codeImgUrlRsp={'code': 99999, 'message': '重试次数达到上限'}
验证码获取失败
需要验证码
下载验证码...
codeImgUrlRsp={'code': 99999, 'message': '重试次数达到上限'}
验证码获取失败

环境信息
 - centos 8
 - 版本为: 1.2.004
 - python版本为：3.6.8

**Comment by testerSunshine** [comment]
建议你更换ip试试，这个是拉不到验证码导致的
