### ISSUE TITLE
为什么提示使用缓存中查找的联系人信息 非法参数！

### ISSUE THREAD

**Issue by 1033475569** [testerSunshine/12306#542]
![image](https://user-images.githubusercontent.com/49267989/71241599-f860d580-2346-11ea-847d-0ccd688fc835.png)

**Comment by bambi2016** [comment]
我也遇到类似的问题：xxx联系人尚未通过身份信息核验，不可购票，

**Comment by testerSunshine** [comment]
> 我也遇到类似的问题：xxx联系人尚未通过身份信息核验，不可购票，

提示不是很清楚吗？

**Comment by livingworld** [comment]
> > 我也遇到类似的问题：xxx联系人尚未通过身份信息核验，不可购票，
> 
> 提示不是很清楚吗？

@testerSunshine 我遇到同样的问题，由于是新添加的联系人，虽然xxx联系人身份信息已经通过核验，在官网平台或其他平台上，都能购买成功，唯独在这个 12306 购买项目代码中就无法成功，每次加载，都提示从缓存中查找联系人，是不是由于缓存信息太旧的缘故，望解答，谢谢。
