### ISSUE TITLE
请求频率过快修改配置无作用问题

### ISSUE THREAD

**Issue by qianjin1017** [testerSunshine/12306#543]
**描述问题**
```
ORDER_MODEL  = 1
实际上已经过了预售，请求频率过快导致ip不问题，12306网页访问不了。
```
**重现步骤**
```
把 ORDER_MODEL  = 1 
设置修改时间无效
```
**截图&日志**
if TickerConfig.ORDER_MODEL is 1:
            print(f"预售还未开始，阻塞中，预售时间为{TickerConfig.OPEN_TIME}, 当前时间为: {now.strftime('%H:%M:%S')}")

            sleep_time_s = 0.1  //这个地方时间是不可以修改一下
            sleep_time_t = 0.3
            # 测试了一下有微妙级的误差，应该不影响，测试结果：2019-01-02 22:30:00.004555，预售还是会受到前一次刷新的时间影响，暂时没想到好的解决方案
            while now.strftime("%H:%M:%S") < TickerConfig.OPEN_TIME:
                now = datetime.datetime.now()
                time.sleep(0.0001)
            print(f"预售开始，开启时间为: {now.strftime('%H:%M:%S')}")
        else:
            sleep_time_s = TickerConfig.MIN_TIME
            sleep_time_t = TickerConfig.MAX_TIME

        while 1:

**环境信息**
 - mac
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by testerSunshine** [comment]
预售目前是写死配置的，可以在这里自行修改
```
sleep_time_s = 0.1  //这个地方时间是不可以修改一下
sleep_time_t = 0.3
```
