### ISSUE TITLE
找了个时间做测试，但是查询无票，在官网上查看却有票，这是怎么回事

### ISSUE THREAD

**Issue by seaase** [testerSunshine/12306#55]
找了个时间做测试，但是查询无票，在官网上查看却有票，这是怎么回事

怀化-成都 车次坐席查询为空
正在第1次查询 随机停留时长：2.02 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：442ms
怀化-成都 车次坐席查询为空
正在第2次查询 随机停留时长：2.13 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：322ms
怀化-成都 车次坐席查询为空
正在第3次查询 随机停留时长：1.84 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：359ms
怀化-成都 车次坐席查询为空
正在第4次查询 随机停留时长：2.03 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：499ms
怀化-成都 车次坐席查询为空
正在第5次查询 随机停留时长：1.37 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：621ms
怀化-成都 车次坐席查询为空
正在第6次查询 随机停留时长：1.01 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：329ms
怀化-成都 车次坐席查询为空
正在第7次查询 随机停留时长：2.1 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：300ms
怀化-成都 车次坐席查询为空
正在第8次查询 随机停留时长：2.67 乘车日期: 2018-12-15 车次：K580 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：134ms
怀化-成都 车次坐席查询为空

**Comment by vanglis** [comment]
余票查询接口变了，需要自己抓包改下

发自我的 iPhone

**Comment by seaase** [comment]
解决了，感谢🙏

**Comment by dizzam** [comment]
> 解决了，感谢🙏

是怎么解决的，我遇到了同样的问题

**Comment by lwoodenheart** [comment]
是怎么解决的，我遇到了同样的问题

**Comment by seaase** [comment]
> 是怎么解决的，我遇到了同样的问题

/otn/leftTicket/queryX这个查询余票的接口经常会变，昨天是/otn/leftTicket/queryO，抓包修改

**Comment by seaase** [comment]
> > 解决了，感谢🙏
> 
> 是怎么解决的，我遇到了同样的问题

/otn/leftTicket/queryX这个查询余票的接口经常会变，昨天是/otn/leftTicket/queryO，抓包修改

**Comment by lwoodenheart** [comment]
"select_url": {  # 查询余票
        "req_url": "/otn/leftTicket/queryX?leftTicketDTO.train_date={0}&leftTicketDTO.from_station={1}&leftTicketDTO.to_station={2}&purpose_codes=ADULT"


修改了还是查询无票，需要开cdn嘛？
谢谢！

**Comment by lwoodenheart** [comment]
> > > 解决了，感谢🙏
> > 
> > 
> > 是怎么解决的，我遇到了同样的问题
> 
> /otn/leftTicket/queryX这个查询余票的接口经常会变，昨天是/otn/leftTicket/queryO，抓包修改

"select_url": { # 查询余票
"req_url": "/otn/leftTicket/queryX?leftTicketDTO.train_date={0}&leftTicketDTO.from_station={1}&leftTicketDTO.to_station={2}&purpose_codes=ADULT"

修改了还是查询无票，需要开cdn嘛？
谢谢！

**Comment by qinya0** [comment]
@testerSunshine 
我在查询网页的接口：/otn/leftTicket/init？xxx  请求中找到该参数
![image](https://user-images.githubusercontent.com/29814007/50774921-bffbef00-12cf-11e9-9722-fe5c100b16a8.png)
