### ISSUE TITLE
RROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from -r requirements.txt (line 10)) (from versions: none) ERROR: No matching distribution found for tensorflow==1.15.0 (from -r requirements.txt (line 10))

### ISSUE THREAD

**Issue by YeDongaidiiqu** [testerSunshine/12306#555]
RROR: Could not find a version that satisfies the requirement tensorflow==1.15.0 (from -r requirements.txt (line 10)) (from versions: none)
ERROR: No matching distribution found for tensorflow==1.15.0 (from -r requirements.txt (line 10))

**Comment by tiankola** [comment]
python换个版本

**Comment by OnePieceJoker** [comment]
文档上写的Python兼容版本为3.6~3.7

**Comment by al123xiaaaa** [comment]
Python 3.7.3 一样有这个问题
