### ISSUE TITLE
Docker运行报错

### ISSUE THREAD

**Issue by ldjqust** [testerSunshine/12306#564]
**描述问题**
```
项目下默认的dockerfile中python版本居然是2.7，之前一直以为本地mac电脑的问题，结果是这个原因，修改好python版本后，运行命令报错
```
**重现步骤**
```
sudo ./docker.sh run后报错
```
**截图&日志**

![87A44C9BD2F59A1B060C6CACC5059729](https://user-images.githubusercontent.com/19955456/71315849-6de0b900-24a1-11ea-9c81-c672425f1c6d.png)

**环境信息**
 - windows
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by hhzrz** [comment]
请参考 issue #608
