### ISSUE TITLE
怎么还是有302错误？

### ISSUE THREAD

**Issue by zz803abc** [testerSunshine/12306#587]
![image](https://user-images.githubusercontent.com/50546321/71354025-ae315b80-25b5-11ea-89b5-923f45306fae.png)

**Comment by zz803abc** [comment]
毛病找到了，是RAIL_EXPIRATION和RAIL_DEVICEID变了，换了新的就好了。

**Comment by lushishuai** [comment]
> 毛病找到了，是RAIL_EXPIRATION和RAIL_DEVICEID变了，换了新的就好了。
你好，请问怎么去找这两个参数的值呀
