### ISSUE TITLE
在高峰期查询到票后，下订单之前需要重新登录导致应用停止

### ISSUE THREAD

**Issue by guozhicong123** [testerSunshine/12306#59]
车次: K287 始发车站: 上海 终点站: 南昌 硬卧: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
用户未登录
联系人不在列表中，请查证后添加

日志打到这里应用就停止了

**Comment by guozhicong123** [comment]
姓名没有问题，但是在12306 官网手动买票在下单之前也是让我登录，不知楼主有没遇到这种情况

**Comment by Lancelothe** [comment]
> 姓名没有问题，但是在12306 官网手动买票在下单之前也是让我登录，不知楼主有没遇到这种情况

我也遇到了今天，解决了吗？？
