### ISSUE TITLE
运行docker-compose up --build -d 老是卡主在Pulling captcha (yinaoxiong/12306_code_server:amd64)

### ISSUE THREAD

**Issue by Goshirt** [testerSunshine/12306#592]
**描述问题**
```
运行docker-compose up --build -d 老是卡主在
Pulling captcha (yinaoxiong/12306_code_server:amd64)
```
**运行命令**
`docker-compose up --build -d`

**截图&日志**
![image](https://user-images.githubusercontent.com/26708885/71392065-acad7500-2641-11ea-929d-be50efd911f8.png)
```
[root@rabbitone 12306]# docker-compose up --build -d
Pulling captcha (yinaoxiong/12306_code_server:amd64)...
amd64: Pulling from yinaoxiong/12306_code_server
000eee12ec04: Already exists
ddc2d83f8229: Pull complete
735b0bee82a3: Downloading [>                                                  ]  280.9kB/28.02MB
8c69dcedfc84: Download complete
495e1cccc7f9: Downloading [===>                                               ]  156.3kB/2.157MB
668eabacaa9d: Download complete
b9084a5f0b4a: Download complete
ba8b7d0f0b68: Download complete
```

**环境信息**
 - centos7
 - python3.7.2
- docker19.03.5
- docker-compose1.25.0
 

**额外的备注**
- Add any other context about the problem here.

**Comment by CoderKwong** [comment]
翻墙可解

**Comment by bioinformatist** [comment]
设置一下docker镜像服务器地址咯，会好很多的，具体可参照这篇：
https://mp.weixin.qq.com/s/UyMLmaYfXgIHSWoMzQdgrQ
记得关注一波哦~

**Comment by Goshirt** [comment]
> 设置一下docker镜像服务器地址咯，会好很多的，具体可参照这篇：
> https://mp.weixin.qq.com/s/UyMLmaYfXgIHSWoMzQdgrQ
> 记得关注一波哦~


> 设置一下docker镜像服务器地址咯，会好很多的，具体可参照这篇：
> https://mp.weixin.qq.com/s/UyMLmaYfXgIHSWoMzQdgrQ
> 记得关注一波哦~

谢谢老哥了，之前我只是加了一个阿里云的镜像服务器地址
