### ISSUE TITLE
可以候补吗？ 为什么我浏览器查询有候补，程序里查询“下单无票 无候补机会”

### ISSUE THREAD

**Issue by JackEHolmes** [testerSunshine/12306#598]
**描述问题**
```
试了几趟车都是浏览器查看到有候补，程序查询的结果是“下单无票 无候补机会”
```
**重现步骤**
```

```
**截图&日志**

**环境信息**
 - centos
 - python3.7.3
 - 订票小助手版本 1.2.004

**额外的备注**

**Comment by linguo2625469** [comment]
我的可以候补到

**Comment by bioinformatist** [comment]
注意你的config文件是不是`TICKET_TYPE = 2`

**Comment by firstkaka** [comment]
> **描述问题**
> 
> ```
> 试了几趟车都是浏览器查看到有候补，程序查询的结果是“下单无票 无候补机会”
> ```
> 
> **重现步骤**
> 
> ```
> 
> ```
> 
> **截图&日志**
> 
> **环境信息**
> 
> * centos
> * python3.7.3
> * 订票小助手版本 1.2.004
> 
> **额外的备注**

我也遇到同样的问题，现在解决了么？1.2.004

**Comment by firstkaka** [comment]
> 注意你的config文件是不是`TICKET_TYPE = 2`

这个配置就是2，但是查询的结果是“下单无票 无候补机会”，实际上是有候补机会的。如果订单已经有候补了会提示什么呢

**Comment by firstkaka** [comment]
也遇到同样问题，各位有解决么，是版本的问题？ @linguo2625469 你的可以候补也是 1.2.004版本么
