### ISSUE TITLE
【墙裂推荐】程序员都在用的工具，快速抢票

### ISSUE THREAD

**Issue by zhouhannah** [testerSunshine/12306#599]
[程序员都在用的工具](https://github.com/xiaoming2028/Free-PAC/wiki/VPS%E4%B8%80%E9%94%AE%E8%84%9A%E6%9C%AC%E6%90%AD%E5%BB%BASSR%E6%95%99%E7%A8%8B%EF%BC%8CYoutube%E7%9C%8B4k%E8%A7%86%E9%A2%91%E6%97%A0%E5%8E%8B%E5%8A%9B)

**Comment by lk-timeout** [comment]
你是真的恶心，这样打广告好吗？这里面可以举报吗？
