### ISSUE TITLE
乘车证件类型有误？

### ISSUE THREAD

**Issue by huangdongjie** [testerSunshine/12306#6]
第 1 张车票： 乘客证件类型错误,值为<span style='color:red'>3</span>。
正在第26次查询  乘车日期: 2018-02-07  车次G4741,G2365,G1371,G1377,G4933 查询无票  代理设置 无  总耗时952ms
车次: G4933 始发车站: 上海 终点站: 长沙 一等座:有
正在尝试提交订票...
尝试提交订单...
出票成功
第 1 张车票： 乘客证件类型错误,值为<span style='color:red'>3</span>。
正在第27次查询  乘车日期: 2018-02-07  车次G4741,G2365,G1371,G1377,G4933 查询无票  代理设置 无  总耗时23ms
车次: G4933 始发车站: 上海 终点站: 长沙 一等座:有
正在尝试提交订票...
尝试提交订单...
出票成功
第 1 张车票： 乘客证件类型错误,值为<span style='color:red'>3</span>。
正在第28次查询  乘车日期: 2018-02-07  车次G4741,G2365,G1371,G1377,G4933 查询无票  代理设置 无  总耗时137ms
12306接口无响应，正在重试
车次: G4933 始发车站: 上海 终点站: 长沙 一等座:有
正在尝试提交订票...

**Comment by testerSunshine** [comment]
第 1 张车票： 乘客证件类型错误,值为3。 
这个日志没打过啊，怎么打出来的
