### ISSUE TITLE
运行一天多之后，出现`empty range for randrange() (4,4, 0)`

### ISSUE THREAD

**Issue by xelll** [testerSunshine/12306#606]
**描述问题**
```
运行一天多之后，出现`empty range for randrange() (4,4, 0)`
```
**重现步骤**
```
运行程序1天+
```
**截图&日志**
![image](https://user-images.githubusercontent.com/13636938/71427780-189de500-26f7-11ea-882b-edfddb0bfb1f.png)

**环境信息**
 - Ubuntu1804
 - python3.6
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Chandler-Lu** [comment]
macOS 同版本下出现相同问题

**Comment by husjhz** [comment]
MacOS类似的错误
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)
empty range for randrange() (4,2, -2)

**Comment by zhd173** [comment]
macOS 同版本下出现相同问题

**Comment by cuixing158** [comment]
win10 同样情况

**Comment by zlAdmin** [comment]
Centos7也是同样情况，基本跑两三个小时就出现

**Comment by laiyazhou** [comment]
ubuntu 下面也是

**Comment by dingjianhub** [comment]
Cent OS 7 23 点后正常停止，第二天早上起来，报同样错误。

**Comment by lawmillion** [comment]
centos也是这样的，用docker容器跑也是。

**Comment by hhzrz** [comment]
造成这个问题的原因是这行[代码](https://github.com/testerSunshine/12306/blob/d0754e4fcde842ad5cbe0e4b8283d33ffb47d6d3/myUrllib/httpUtils.py#L196)：这行代码在每次下单失败后，会从cdn列表中弹出(pop)一个新的ip来使用，然后在弹出之前没有检查cdn列表是否大于等于5，所以长时间运行后，cdn列表就会慢慢变少，最后列表项目可能会不够5个ip。
#677 这个PR会修复这个问题。

**Comment by dingjianhub** [comment]
> 造成这个问题的原因是这行[代码](https://github.com/testerSunshine/12306/blob/d0754e4fcde842ad5cbe0e4b8283d33ffb47d6d3/myUrllib/httpUtils.py#L196)：这行代码在每次下单失败后，会从cdn列表中弹出(pop)一个新的ip来使用，然而在弹出之前没有检查cdn列表是否大于等于5，所以长时间运行后，cdn列表就会慢慢变少，最后列表项目可能会不够5个ip。
> #677 这个PR会修复这个问题。

感谢解答~~

**Comment by xelll** [comment]
> 造成这个问题的原因是这行[代码](https://github.com/testerSunshine/12306/blob/d0754e4fcde842ad5cbe0e4b8283d33ffb47d6d3/myUrllib/httpUtils.py#L196)：这行代码在每次下单失败后，会从cdn列表中弹出(pop)一个新的ip来使用，然而在弹出之前没有检查cdn列表是否大于等于5，所以长时间运行后，cdn列表就会慢慢变少，最后列表项目可能会不够5个ip。
> #677 这个PR会修复这个问题。

thanks

**Comment by ghdevops123** [comment]
现在还是会报 empty range for randrange() (4,2, -2) 修复了吗？
