### ISSUE TITLE
车次坐席查询为空

### ISSUE THREAD

**Issue by zhangshiyi1994** [testerSunshine/12306#61]
北京-银川 车次坐席查询为空, 查询url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-01-31&leftTicketDTO.from_station=BJP&leftTicketDTO.to_station=YIJ&purpose_codes=ADULT, 可以手动查询是否有票

这个是否正常？

**Comment by testerSunshine** [comment]
你ip封了，可以考虑换一拨ip试试

**Comment by zhangshiyi1994** [comment]
我用的是公司的网，换ip有效果吗？
