### ISSUE TITLE
云打码一直失败

### ISSUE THREAD

**Issue by XYGR** [testerSunshine/12306#613]
**描述问题**
```
云打码一直失败，想配置本地打码但是教程写的又不详细，想加群一直没人通过。。。
```
**重现步骤**
```
步骤一
```
**截图&日志**

需要验证码
下载验证码...
下载验证码成功
您已设置使用云打码，但是服务器资源有限，请尽快改为本地打码
None
验证码校验失败

一直循环

**环境信息**
 - Mac
 - python3.7.4
 - 订票小助手版本 1.2.004
**额外的备注**

**Comment by Vict0r-Lee** [comment]
用本地模型

**Comment by Morty07** [comment]
他不是说了 本地模型的文档不详细 怎么用本地模型？

**Comment by zlAdmin** [comment]
enmm 我的现在也是这样，使用云打码有点问题

**Comment by zlAdmin** [comment]
可能是那个打码服务被封了，我换了120.24.62.193:80这个打码服务好使

**Comment by bigyShot** [comment]
> 可能是那个打码服务被封了，我换了120.24.62.193:80这个打码服务好使

感谢感谢嘿嘿,换了你的就可以用了

**Comment by Vict0r-Lee** [comment]
尝试了下本地模型搭建,也是一堆问题啊 
不会python用起来是很麻烦.

**Comment by XYGR** [comment]
经过数次摸索研究出了使用本地模型的方法
1.下载12306model(下载链接随意选择一个)把12306.image.model.h5和model.2.0.h5两个文件替换掉原本项目根目录(不知道不替换行不行的通)
2.修改requirements.txt里面的keras版本为2.3.0
3.执行pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt安装依赖
4.修改TickerConfig.py中的变量AUTO_CODE_TYPE为3
5.python3 run.py c
6.python3 run.py r

**Comment by Vict0r-Lee** [comment]
> 经过数次摸索研究出了使用本地模型的方法
> 1.下载12306model(下载链接随意选择一个)把12306.image.model.h5和model.2.0.h5两个文件替换掉原本项目根目录(不知道不替换行不行的通)
> 2.修改requirements.txt里面的keras版本为2.3.0
> 3.执行pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt安装依赖
> 4.修改TickerConfig.py中的变量AUTO_CODE_TYPE为3
> 5.python3 run.py c
> 6.python3 run.py r

AUTO_CODE_TYPE为3是云打码,应该改为2吧.

**Comment by XYGR** [comment]
> > 经过数次摸索研究出了使用本地模型的方法
> > 1.下载12306model(下载链接随意选择一个)把12306.image.model.h5和model.2.0.h5两个文件替换掉原本项目根目录(不知道不替换行不行的通)
> > 2.修改requirements.txt里面的keras版本为2.3.0
> > 3.执行pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt安装依赖
> > 4.修改TickerConfig.py中的变量AUTO_CODE_TYPE为3
> > 5.python3 run.py c
> > 6.python3 run.py r
> 
> AUTO_CODE_TYPE为3是云打码,应该改为2吧.
