### ISSUE TITLE
docker-build 环境错误

### ISSUE THREAD

**Issue by Riven-meng** [testerSunshine/12306#639]
**描述问题**
```
加群大家可能都是寻找各种问题无人回复 只好提个issues了
docker-compser build 镜像都获取之后 编译错误 应该像是源没有包
```
**重现步骤**
```
docker-compser build - 
```
**截图&日志**
![image](https://user-images.githubusercontent.com/39484064/71501162-b46c5400-28a3-11ea-8132-7ade1f8aeda3.png)

**环境信息**
 - linux
 - python3.7.1
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by Riven-meng** [comment]
### 已经自我解决；

**Comment by MovLe** [comment]
请问如何解决的
