### ISSUE TITLE
如何设置抢票的具体时间？

### ISSUE THREAD

**Issue by henryccl** [testerSunshine/12306#652]
如果说我想抢22号下午3点的票如何设置呢？我在大佬的介绍里面只看到了设置抢票的日期，没有具体时间，是我看漏了吗？

**Comment by LiuLiuniuniu** [comment]
你只需要填车次就好了啊

**Comment by henryccl** [comment]
哦哦  好的谢谢大佬------------------ 原始邮件 ------------------
发件人: "Sonder"<notifications@github.com>
发送时间: 2019年12月28日(星期六) 中午1:03
收件人: "testerSunshine/12306"<12306@noreply.github.com>;
抄送: "henryccl"<1341423478@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [testerSunshine/12306] 如何设置抢票的具体时间？ (#652)



你只需要填车次就好了啊
 
&mdash;
