### ISSUE TITLE
tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform. 

### ISSUE THREAD

**Issue by yingchunbai** [testerSunshine/12306#657]
**描述问题**
```
Mac 下 $ pip3 install -i https://pypi.douban.com/simple -r requirements.txt
报错如下:
tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.
```
**重现步骤**
```
步骤一
```
**截图&日志**

**环境信息**
 - Mac
 - python3.7.4
 - 订票小助手版本 1.1.101

**额外的备注**
- Add any other context about the problem here.

**Comment by wanghonglu** [comment]
大哥 你这个解决了吗，我也是这样
"tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform"
$ arch
x86_64
$ python --version
Python 3.7.2
我看那个链接上，x86-64 、Python 3.7就是用的tflite_runtime-1.14.0-cp37-cp37m-linux_x86_64.whl这个啊 没毛病啊
