### ISSUE TITLE
MAC环境安装依赖包报错

### ISSUE THREAD

**Issue by minekey** [testerSunshine/12306#660]
Installing collected packages: selenium, fake-useragent
  Found existing installation: selenium 3.141.0
    Uninstalling selenium-3.141.0:
      Successfully uninstalled selenium-3.141.0
  Rolling back uninstall of selenium
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/selenium'
Consider using the `--user` option or check the permissions.

Minekey:12306-master minekey$ pip3 install selenium
Requirement already satisfied: selenium in /usr/local/lib/python3.7/site-packages (3.141.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/site-packages (from selenium) (1.22)

**Comment by xshfsky** [comment]
<img width="570" alt="安装requirements报错" src="https://user-images.githubusercontent.com/8521539/71553808-8710d900-2a50-11ea-946e-66f015ebd23b.png">
这个问题怎么样简单高效解决

**Comment by xshfsky** [comment]
> <img alt="安装requirements报错" width="570" src="https://user-images.githubusercontent.com/8521539/71553808-8710d900-2a50-11ea-946e-66f015ebd23b.png">
> 
> 这个问题怎么样简单高效解决
解决setuptools=问题：版本更新 
pip install --upgrade setuptools

**Comment by minekey** [comment]
谢谢，已解决，需要在命令后面加上 --user
