### ISSUE TITLE
打码平台错误: 快豆不足,请充值., 请登录打码平台查看-http://www.ruokuai.com/client/index?6726

### ISSUE THREAD

**Issue by iOSGL** [testerSunshine/12306#67]
这个是必须要先充值才能用么？

**Comment by XComing** [comment]
是的，充1块差不多可以用一天了。

**Comment by lxtGH** [comment]
@XComing 这个如何算钱呢？？

**Comment by XComing** [comment]
> @XComing 这个如何算钱呢？？

http://www.ruokuai.com/client
字母数字混合，混合 4 位图像１张=10快豆
字母数字混合，混合 5 位图像１张=12快豆
字母数字混合，混合 6 位图像１张=15快豆
纯汉字，数字 4 位图像１张=40快豆
选择题，九宫格１张=30快豆

**Comment by lzz1023** [comment]
我的每个验证码都需要35的豆子，老贵了

**Comment by zyuyou** [comment]
注册个开发者账号, 修改下若快的soft_id和soft_key, 还可以返现 😂

**Comment by kun-guo** [comment]
@zyuyou 要支持作者 把该给的利润给作者

**Comment by RunZH** [comment]
> 注册个开发者账号, 修改下若快的soft_id和soft_key, 还可以返现 😂 , 感觉作者要打死我

怎么修改啊==

**Comment by tigerZhang86** [comment]
> 是的，充1块差不多可以用一天了。

1元2500个豆，你查询频率是多少，差不多用一天？
打码一次20个豆，100次就差不多了……

**Comment by Lancelothe** [comment]
> soft_key

同问，怎么修改的？？？

**Comment by Lancelothe** [comment]
> 注册个开发者账号, 修改下若快的soft_id和soft_key, 还可以返现 😂 , 感觉作者要打死我

同问怎么修改的？？？

**Comment by liuser** [comment]
使用若快，在刷票过程中，老是提示session过期，重新登录，刷了200多次，1000多个豆豆没了，请问有遇到过这种情况吗？

**Comment by Percygu** [comment]
运行时报错，ImportError: No module named yaml 是什么原因呢

**Comment by Lancelothe** [comment]
> 运行时报错，ImportError: No module named yaml 是什么原因呢

依赖包都装了吗？？？

**Comment by Keke921** [comment]
请问
Unicode-objects must be encoded before hashing
验证码校验失败,信息为空
这是为什么呀？

**Comment by sujianjob** [comment]
> 使用若快，在刷票过程中，老是提示session过期，重新登录，刷了200多次，1000多个豆豆没了，请问有遇到过这种情况吗？

我昨晚10点多调试好脚本，今天早上就提示豆豆不够了，充了11块

**Comment by wickey-w** [comment]
> > 注册个开发者账号，修改下若快的soft_id和soft_key，还可以返现 😂 ，感觉作者要打死我
> 
> 同问怎么修改的???我充值11元的豆子，两天就用完了

**Comment by givenhyh** [comment]
能不能自己改接口啊

**Comment by zhaojiafu** [comment]
现在若快这个打码平台好像打不开了？是不是不能用了？

**Comment by Valuebai** [comment]
若快倒闭了，不能用了

**Comment by marud1024** [comment]
若快倒闭了

**Comment by tianlong19910404** [comment]
File "run.py", line 4, in <module>
    from init import select_ticket_info
  File "/Users/tianlong/Desktop/develop/code/12306-master/init/select_ticket_info.py", line 10, in <module>
    import wrapcache
ImportError: No module named wrapcache
报了这个错 需要怎么解决 依赖都安装了啊

**Comment by ruitian** [comment]
若快倒闭了 有啥能补上么

**Comment by ruitian** [comment]
若快倒闭了 有啥能补上么

**Comment by yudancha** [comment]
我若快还有好几十快钱那，心疼
