### ISSUE TITLE
windows 下乱码

### ISSUE THREAD

**Issue by 674345386** [testerSunshine/12306#7]
~~

**Comment by 674345386** [comment]
![tim 20180115170303](https://user-images.githubusercontent.com/7128380/34934610-1000537a-fa16-11e7-8cd9-6aea21310761.png)

**Comment by testerSunshine** [comment]
设置编码为gb2312试试

**Comment by 674345386** [comment]
@testerSunshine 
。。更换不了
![default](https://user-images.githubusercontent.com/7128380/34945703-1fb09798-fa3f-11e7-82b3-efb3640b4523.png)

**Comment by liuning123** [comment]
@674345386 是在程序中设置
# -*- coding=gb2312 -*-

**Comment by y0umu** [comment]
@674345386 试试`chcp 65001`（使用UTF-8）或者`chcp 936`（使用GBK）

**Comment by lijun0326** [comment]
已修，等一个merge

**Comment by czln** [comment]
我也遇到了这个问题，不过我的系统语言是繁体中文， 终端改成cp65001也会报错 cp950不能解码简体中文字符，cp936就干脆不能用，感觉py2这个中文支持的问题有点无解啊，好像就只能把字符串一个个decode成utf8。糟心
