### ISSUE TITLE
抢到票回家了，可以安心上网了

### ISSUE THREAD

**Issue by oldedifier** [testerSunshine/12306#734]
Github真是一个好地方，各种轮子都有。
[百度网盘不限速客户端](https://github.com/peterq/pan-light)
[科学上网工具](https://github.com/xiaoming2028/FreeNet)
[功能强大的内网穿透代理服务器](https://github.com/cnlh/nps)

**Comment by cao-lianhui** [comment]
`设置乘车人数为: 0
查询到有余票，尝试提交订单
使用缓存中查找的联系人信息
系统忙，请稍后重试
`
大佬知道这个问题怎么解决吗。。。

**Comment by cao-lianhui** [comment]
大佬，问下，你抢了大概多久？是在提示 "建议抢票" 的情况下抢的吗

**Comment by cao-lianhui** [comment]
> Github真是一个好地方，各种轮子都有。
> [百度网盘不限速客户端](https://github.com/peterq/pan-light)
> [科学上网工具](https://github.com/xiaoming2028/FreeNet)
> [功能强大的内网穿透代理服务器](https://github.com/cnlh/nps)

大佬，问下，你抢了大概多久？是在提示 "建议抢票" 的情况下抢的吗
