### ISSUE TITLE
请问可不可以增加短信提醒

### ISSUE THREAD

**Issue by pppwaw** [testerSunshine/12306#754]
是否可以通过Twilio来进行短信提醒？
假如我写出来了，可以进行合并么？

**Comment by lbq1121** [comment]
你可以fork一份 进行二次开发 如果做的好的话 应该会考虑合并

**Comment by pppwaw** [comment]
Twilio不能发送中文短信

**Comment by pppwaw** [comment]
Twilio不能发送中文短信。。。。。。

**Comment by pppwaw** [comment]
Twilio不能发送中文短信。。。。。。
阿里云等服务商需要提交模版各类的，同时还需要审核。。。。。。
等大佬弄个充钱的api接口给我等调用吧
