### ISSUE TITLE
唯一抢票群vx：jess_andoid

### ISSUE THREAD

**Issue by wenfu92** [testerSunshine/12306#758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by louzeyu-04** [comment]
> **您的功能请求是否与问题有关？请描述。**
> 对问题的清楚简洁的描述。例如 当[...]时，我总是感到沮丧
> 
> **描述您想要的解决方案**
> 简明扼要地描述您要发生的事情。
> 
> **描述您考虑过**
> 的替代方案关于您考虑过的任何替代解决方案或功能的简洁明了的描述。
> 
> **其他上下文**
> 在此处添加有关功能请求的其他任何上下文或屏幕截图。



> **您的功能请求是否与问题有关？请描述。**
> 对问题的清楚简洁的描述。例如 当[...]时，我总是感到沮丧
> 
> **描述您想要的解决方案**
> 简明扼要地描述您要发生的事情。
> 
> **描述您考虑过**
> 的替代方案关于您考虑过的任何替代解决方案或功能的简洁明了的描述。
> 
> **其他上下文**
> 在此处添加有关功能请求的其他任何上下文或屏幕截图。

。。。
