### ISSUE TITLE
今年这个项目还可以成功抢到票吗，2021-01-12？

### ISSUE THREAD

**Issue by xzjby** [testerSunshine/12306#798]
如题

**Comment by lidy996** [comment]
同问

**Comment by liam-pat** [comment]
抢个屁，垃圾软件，log message  没写清楚，一直显示出票失败，真是浪费时间，这开发者的能力能到哪里、

**Comment by lidy996** [comment]
放弃了，自己写了个监控脚本

**Comment by liam-pat** [comment]
> 放弃了，自己写了个监控脚本

这个真抢不了，自己开发可能得花点时间，监控然后手动抢，怕是也抢不到、
这个作者写这个目的就是为了蹭热度，程序实用性一点也没有、

**Comment by lsq** [comment]
现在安装还一堆问题

**Comment by havethink** [comment]
[今天抢到了](https://github.com/havethink/FreePAC)

**Comment by i-guyue** [comment]
能用，要改几个地方
