### ISSUE TITLE
退出排队，重新刷票时，没有取消排队

### ISSUE THREAD

**Issue by WeiLong-lee** [testerSunshine/12306#8]
![qq 20180116102423](https://user-images.githubusercontent.com/21254410/34969021-a5878efe-faa7-11e7-8e71-62ce32d1299f.png)

**Comment by WeiLong-lee** [comment]
![qq 20180116102635](https://user-images.githubusercontent.com/21254410/34969040-bf76e562-faa7-11e7-880c-7c064d7ca266.png)

**Comment by testerSunshine** [comment]
已修正此功能
