### ISSUE TITLE
查到有票，但是出票失败

### ISSUE THREAD

**Issue by zxt2012bs** [testerSunshine/12306#80]
车次: G265 始发车站: 北京南 终点站: 沧州西 二等座: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
缓存中找到联系人信息: [xxxxxxxxxxx]
提交订单成功
排队成功, 当前余票还剩余: 85 张
验证码提交安全期，等待2.524MS
出票失败！

**Comment by zeal-github** [comment]
我也遇到同样的问题。
