### ISSUE TITLE
docker-compose运行一直在无止境的加入cdn，并且出现302

### ISSUE THREAD

**Issue by MinMonk** [testerSunshine/12306#806]
**主要有两个异常信息**

- 登陆失败 302
- No module named 'cv2'

**主要配置信息**
1. TICKET_TYPE=2
2. COOKIE_TYPE=3，手动在windows系统上登录后，从请求的header中抓取的**RAIL_EXPIRATION** 和 **RAIL_DEVICEID**
3. AUTO_CODE_TYPE=2， HOST配置的是captcha:80

**异常产生过程**

1. 解压源码包之后，修改TickerConfig.py中的配置（主要配置如上所述）；
2. 运行python3 run.py t，邮件发送成功（能收到测试邮件）
3. 运行`docker-compose up -d`
4. 一直打印加入cdn
5. 出现**第一个**异常日志：ticket     | url: /otn/login/init返回参数为空, 接口状态码: 302
6. 依旧循环打印 加入cdn；
7. 出现下方异常（**第二个异常信息**）之后就会进入一次新的循环
```
ticket     | 当前ip: 122.70.142.252, 延时: 828.804
ticket     | Traceback (most recent call last):
ticket     |   File "run.py", line 21, in <module>
ticket     |     from init import select_ticket_info
ticket     |   File "/usr/src/app/init/select_ticket_info.py", line 16, in <module>
ticket     |     from init.login import GoLogin
ticket     |   File "/usr/src/app/init/login.py", line 8, in <module>
ticket     |     from inter.GetRandCode import getRandCode
ticket     |   File "/usr/src/app/inter/GetRandCode.py", line 6, in <module>
ticket     |     from verify.localVerifyCode import Verify
ticket     |   File "/usr/src/app/verify/localVerifyCode.py", line 7, in <module>
ticket     |     import cv2
ticket     | ModuleNotFoundError: No module named 'cv2'
ticket exited with code 1
```
8. 在`ticket exited with code 1`之后，又开始了新的一轮循环，一直循环重试下去
**截图&日志**
![image](https://user-images.githubusercontent.com/27961039/114809168-44f1df00-9ddc-11eb-94fb-786b247ef567.png)

**环境信息**
- ubuntu18.04
 - Docker version 19.03.1, build 74b1e89
 - docker-compose version 1.25.1, build a82fef0
 - Python 3.6.9
 - 订票小助手版本 1.2.004

**Comment by zhnglicho** [comment]
在 requirements-docker37.txt  添加 pip install opencv-python， 重新build docker 
或者
进入ticket 容器 执行  pip install opencv-python  
可解决 cv2 导入问题

**Comment by MinMonk** [comment]
requirements-docker37.txt这个文件中维护的应该是名称和版本号，在Dockerfile37这个文件的47行

> RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements-docker37.txt

但是我不了解python，不知道在python3.7这个版本依赖的opencv-python库的版本号是多少

直接进入容器内部，执行`pip install opencv-python`执行一会儿进度条动一会儿就不动了。

**Comment by zhnglicho** [comment]
设置 AUTO_CODE_TYPE=3 应该就可以解决了







在 2021-04-17 16:34:50，"Joker" ***@***.***> 写道：

requirements-docker37.txt这个文件中维护的应该是名称和版本号，在Dockerfile37这个文件的47行

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r requirements-docker37.txt

但是我不了解python，不知道在python3.7这个版本依赖的opencv-python库的版本号是多少

直接进入容器内部，执行pip install opencv-python执行一会儿进度条动一会儿就不动了。

**Comment by MinMonk** [comment]
使用云打码(AUTO_CODE_TYPE=3)的话，我没有云服务器，可以设置成我本机搭建的打码地址么？

**Comment by zhnglicho** [comment]
容器 captcha （yinaoxiong/12306_code_server:amd64） 这个就是验证码识别的服务器， 应该在你本地的docker 中有运行

**Comment by MinMonk** [comment]
谢谢了，我刚刚试了下，是可以的。

那几乎问题就是出在ticket这个容器上。

**Comment by MinMonk** [comment]
谢谢了，我刚刚试了下，是可以的。

那几乎问题就是出在ticket这个容器上。
