### ISSUE TITLE
出现 登录失败: 核验方式不正确！

### ISSUE THREAD

**Issue by junjiantech** [testerSunshine/12306#819]
**描述问题**
```
出现 登录失败: 核验方式不正确！
```
**重现步骤**
`docker-compose up --build -d` 后查看日志 显示如下情况
![image](https://user-images.githubusercontent.com/66256045/132080521-91dfebeb-9dc7-439a-ba5d-77e1704d0aa6.png)

**环境信息**
 - Centos 7
 - python3.7.1

**额外的备注**

尝试重新登陆
需要验证码
下载验证码...
下载验证码成功
已设置本地打码服务器
验证码识别坐标为112,77,184,77,40,149
112,77,184,77,40,149
验证码通过,开始登录..
登录失败: 核验方式不正确！

**Comment by junjiantech** [comment]
RAIL_EXPIRATION 和 RAIL_DEVICEID 是与机器绑定的吗？ 必须的需要服务部署的机器上获取这两个参数嘛？

**Comment by BaiFree** [comment]
我也出现了这个问题，求解

**Comment by DuanYuFi** [comment]
> RAIL_EXPIRATION 和 RAIL_DEVICEID 是与机器绑定的吗？ 必须的需要服务部署的机器上获取这两个参数嘛？

这两个应该是cookie，但是我设置自己的cookie后仍然报这个错，不知道为什么，实在不行就用driver吧

**Comment by DuanYuFi** [comment]
刚刚我改成driver还是有这个问题，driver只是帮助获取一个cookie，但是没解决根本问题

**Comment by lizj666666** [comment]
可以**试下**用12306账号登陆 不要用手机号

**Comment by wlnRes** [comment]
> 可以**试下**用12306账号登陆 不要用手机号

也不行

**Comment by qixing176** [comment]
这个不要在云上跑，我在腾讯云上跑也有这个问题，但是我在windows本地跑就没有问题，成功登陆，去网上查了下说是腾讯云与阿里云容易被封ip。
还有最好用12306账号登录而不是用手机号登录，看到好多issue说用手机号登录会有问题

**Comment by NicknamedCoco** [comment]
> **描述问题**
> 
> ```
> 出现 登录失败: 核验方式不正确！
> ```
> 
> **重现步骤** `docker-compose up --build -d` 后查看日志 显示如下情况 ![image](https://user-images.githubusercontent.com/66256045/132080521-91dfebeb-9dc7-439a-ba5d-77e1704d0aa6.png)
> 
> **环境信息**
> 
> * Centos 7
> * python3.7.1
> 
> **额外的备注**
> 
> 尝试重新登陆 需要验证码 下载验证码... 下载验证码成功 已设置本地打码服务器 验证码识别坐标为112,77,184,77,40,149 112,77,184,77,40,149 验证码通过,开始登录.. 登录失败: 核验方式不正确！

大佬，我出现了和你一样的问题，你是怎么解决的

**Comment by stillmind** [comment]
> > **描述问题**
> > ```
> > 出现 登录失败: 核验方式不正确！
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **重现步骤** `docker-compose up --build -d` 后查看日志 显示如下情况 ![image](https://user-images.githubusercontent.com/66256045/132080521-91dfebeb-9dc7-439a-ba5d-77e1704d0aa6.png)
> > **环境信息**
> > 
> > * Centos 7
> > * python3.7.1
> > 
> > **额外的备注**
> > 尝试重新登陆 需要验证码 下载验证码... 下载验证码成功 已设置本地打码服务器 验证码识别坐标为112,77,184,77,40,149 112,77,184,77,40,149 验证码通过,开始登录.. 登录失败: 核验方式不正确！
> 
> 大佬，我出现了和你一样的问题，你是怎么解决的

各位大神，解决了吗？我这里也是，在mac上本地跑的python项目。
