### ISSUE TITLE
ip网络异常

### ISSUE THREAD

**Issue by WangCaijun** [testerSunshine/12306#84]
１．验证码登录通过
２．提示：车次坐席查询为空，ｉｐ网络异常
３．什么意思？不是ｉｐ被封吧？是请求接口不对？还是……我配置信息没写对？

**Comment by TestSmirk** [comment]
单个cdn节点异常.

**Comment by WangCaijun** [comment]
恩恩，是
不过主要原因还是我日期写错了，02-01写成了02-1...

**Comment by zhilianbi520** [comment]
几乎每条都ip网络异常。。怎么破？

**Comment by TestSmirk** [comment]
复制一下查询api是不是不让查了啊.

**Comment by WangCaijun** [comment]
![image](https://user-images.githubusercontent.com/20896408/50745882-6a8bf780-1267-11e9-827b-c3922647be63.png)

这是拿谷歌浏览器抓包抓到的，我是将queryX改为queryZ后就好用了

**Comment by WangCaijun** [comment]
虽说是好用了，不过有的cdn节点也会显示ip网络异常，而且次数还很多
不过只要有正常的情况，就说明咱配置没问题
要是一条成功的都没有的话，那多半是咱的配置有问题

**Comment by TestSmirk** [comment]
过段时间会好的.可能是ban了

**Comment by tonyleeecn** [comment]
目测是12306自己服务挂了。。  因为网页访问也是超时。

**Comment by zhilianbi520** [comment]
@WangCaijun 好的～

**Comment by Hawken94** [comment]
![image](https://user-images.githubusercontent.com/12959892/50812455-c7fa7400-134d-11e9-910c-18d16d17f263.png)
在腾讯云部署了，几乎每次都报 “ip网络异常”，是不是我的 ip 被禁了😂

**Comment by Hawken94** [comment]
@kun-guo 你是如何解决的呢，本地跑同样的参数不会报“ ip网络异常”

**Comment by kun-guo** [comment]
https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-02-03&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=CWQ&purpose_codes=ADULT

**Comment by Hawken94** [comment]
> https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-02-03&leftTicketDTO.from_station=IOQ&leftTicketDTO.to_station=CWQ&purpose_codes=ADULT

你发这个我不知道你在说什么

**Comment by kun-guo** [comment]
@TestSmirk 1.  ip 网络频率太高了 能不能优化；2. 乘客已经填写了，但是几乎都提示在常用联系人里没找到就挂了，代码是最新版本

**Comment by sherlockwhite** [comment]
全部都是IP网络异常

**Comment by WangCaijun** [comment]
全部都是吗？
没一条对的？
现在最新版本的程序，如果碰到ip异常会瞬间再次请求，直到成功后才进行随机时间等待

**Comment by sherlockwhite** [comment]
> 全部都是吗？
> 没一条对的？
> 现在最新版本的程序，如果碰到ip异常会瞬间再次请求，直到成功后才进行随机时间等待

最新版本的喔跑起来还是每条异常

**Comment by WangCaijun** [comment]
> > 全部都是吗？
> > 没一条对的？
> > 现在最新版本的程序，如果碰到ip异常会瞬间再次请求，直到成功后才进行随机时间等待
> 
> 最新版本的喔跑起来还是每条异常

我这里么得问题，最新版本的查询ａｐｉ是对的，那是不是你的配置有问题?
