### ISSUE TITLE
CPU 占用过高

### ISSUE THREAD

**Issue by Hawken94** [testerSunshine/12306#90]
OS: mac OS 10.13.6
version: python 2.7.15

进程CPU占用过高（第一个）
如图：
![image](https://user-images.githubusercontent.com/12959892/50732417-ecbbe380-11b5-11e9-886c-240936dd706b.png)

**Comment by Douboo** [comment]
我的也是，把脚本杀死后，python依然占用很高CPU。

**Comment by Douboo** [comment]
我也遇到这种情况

**Comment by WangCaijun** [comment]
![train_process_incpu](https://user-images.githubusercontent.com/20896408/50736249-01b86700-11f6-11e9-887b-144421656342.png)
我的ubuntu也是-_-……

**Comment by testerSunshine** [comment]
确实有这个问题，是查询线程缓存导致的，已做修改
https://github.com/testerSunshine/12306/commit/a78683bad29e67af19b16cb497b627c31eea1ce2
