### ISSUE TITLE
未能打开文件“tmpDFqUUu.PNG”，因为您没有查看它的权限。

### ISSUE THREAD

**Issue by AngryBigCat** [testerSunshine/12306#94]
在macOS 10.14.2系统下出现的问题，已经使用过`sudo python run.py`运行 
提示“输入对应的验证码：” 的时候，出现的系统弹窗提示，无法显示二维码
不知道大佬们有没有遇到该问题的解决办法

**Comment by MH-Blog** [comment]
这个代码块  在哪个文件里面呀   没有找到。。。感谢

**Comment by MH-Blog** [comment]
> 把代码里的'./tkcode'改成'./tkcode.png'，验证码图片就是项目所在目录里的tkcode.png，可以双击看图片。

请问
这个代码块 在哪个文件里面呀 没有找到。。。感谢

**Comment by wosenbo** [comment]
我提的 PR 可以解决这个问题。https://github.com/testerSunshine/12306/pull/108

**Comment by AngryBigCat** [comment]
@wosenbo pr请求被关了啊

**Comment by wosenbo** [comment]
@AngryBigCat 调用Mac命令打开图片，代码检测工具认为不安全。实际上这个只有自己运行，所以不必担心。
