### ISSUE TITLE
run.py 报错

### ISSUE THREAD

**Issue by WangFinn** [testerSunshine/12306#96]
Traceback (most recent call last):
  File "run.py", line 15, in <module>
    run()
  File "run.py", line 7, in run
    select_ticket_info.select().main()
  File "/home/finn/python/12306-master/init/select_ticket_info.py", line 47, in __init__
    self.arrival_time, self.take_time, self.order_model, self.open_time = self.get_ticket_info()
  File "/home/finn/python/12306-master/init/select_ticket_info.py", line 70, in get_ticket_info
    set_type = [seat_conf[x.encode("utf-8")] for x in ticket_info_config["set"]["set_type"]]
  File "/home/finn/python/12306-master/init/select_ticket_info.py", line 70, in <listcomp>
    set_type = [seat_conf[x.encode("utf-8")] for x in ticket_info_config["set"]["set_type"]]
KeyError: b'\xe4\xba\x8c\xe7\xad\x89\xe5\xba\xa7'
--------------------------------------------------------------------------------------------------------
----------Python 2.7.14 (default, Sep 18 2017, 11:31:52) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
-------------------------------------------------------------------------------------------------------
finn@finn-virtual-machine:~/python/12306-master$ sudo  pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt
The directory '/home/finn/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/finn/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: beautifulsoup4==4.5.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 1)) (4.5.3)
Requirement already satisfied: bs4==0.0.1 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: PyYAML==3.12 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 3)) (3.12)
Requirement already satisfied: six==1.10.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (1.10.0)
Requirement already satisfied: requests==2.18.4 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 5)) (2.18.4)
Requirement already satisfied: Pillow==5.0.0 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 6)) (5.0.0)
Requirement already satisfied: wrapcache==1.0.8 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 7)) (1.0.8)
Requirement already satisfied: ntplib==0.3.3 in /usr/local/lib/python3.6/dist-packages (from -r requirements.txt (line 8)) (0.3.3)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests==2.18.4->-r requirements.txt (line 5)) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests==2.18.4->-r requirements.txt (line 5)) (2018.11.29)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests==2.18.4->-r requirements.txt (line 5)) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests==2.18.4->-r requirements.txt (line 5)) (3.0.4)

**Comment by 1104049235** [comment]
我把sekect_ticket_info.py 文件 第70行修改为
set_type = ["硬座"，"硬卧"]
你可以试试

**Comment by WangFinn** [comment]
>           我把sekect_ticket_info.py 文件 第70行修改为
> set_type = ["硬座"，"硬卧"]
> 你可以试试

好的，O(∩_∩)O谢谢

**Comment by 1104049235** [comment]
> > ```
> >       我把sekect_ticket_info.py 文件 第70行修改为
> > ```
> > set_type = ["硬座"，"硬卧"]
> > 你可以试试
> 
> 好的，O(∩_∩)O谢谢

小事啦
