### ISSUE TITLE
查询到有余票，然后报乱码，退出

### ISSUE THREAD

**Issue by Cheneytt** [testerSunshine/12306#98]
配置：
station_dates:
    - "2019-01-16"
station_trains:
    - "K1107"
from_station: "信阳"
to_station: "南阳"
set_type:
  - "硬座"
is_cdn: 2
order_type: 2
order_model: 2

---------------------------------------------------
日志打印如下：

信阳-南阳 车次坐席查询为空,ip网络异常，查询url: https://kyfw.12306.cn/otn/leftTicket/queryZ?leftTicketDTO.train_date=2019-01-16&leftTicketDTO.from_station=XUN&leftTicketDTO.to_station=NFF&purpose_codes=ADULT, 可以手动查询是否有票
正在第6次查询 随机停留时长：2.95 乘车日期: 2019-01-16 车次：K1107 查询无票 cdn轮询IP：None当前cdn总数：0 总耗时：618ms
(u'08:43', u'13:55', u'05:12')
车次: K1107 始发车站: 信阳 终点站: 南阳 硬座: 有
设置乘车人数为: 1
查询到有余票，尝试提交订单
鏈煡鎵惧埌甯哥敤鑱旂郴浜�

**Comment by caoyi0905** [comment]
这个乱码应该是没有查到联系人信息，你需要检查一下12306的联系人是否填写正常

**Comment by yangtong5** [comment]
我的下完订单之后出现乱码 但是抢票成功了？  这个乱码怎么解决呢？？？

**Comment by caoyi0905** [comment]
@yangtong5 不用管，赶紧去12306去把钱付了

**Comment by Cheneytt** [comment]
@testerSunshine  select_ticket_info.py main 函数 自定义异常 print 的时候 ，print(e)  改成 print(e.message) 可解决乱码问题。
